### ISSUE TITLE
Moving pin by tap and hold

### ISSUE THREAD

**Issue by amay077** [amay077/Xamarin.Forms.GoogleMaps#10]
Depends #9

**Comment by XnainA** [comment]
Please support moving pin by tap and hold .
Your package help me a lot 👍

**Comment by amay077** [comment]
Okay,
I'll add Pin.IsDraggable property and Map.PinDragStart, PinDragEnd and PinDrag events.

Plz check this thread. 👀

**Comment by amay077** [comment]
@XnainA 

I deployed v1.5.0-beta1 to nuget - https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/1.5.0-beta1 .

This contains as follows:

* #10 Moving pin by tap and hold (Android / iOS only)
* #45 Support Map.MapClicked and MapLongClicked event (Android / iOS only)

Also I added samples for these.
Please check BasicMapPage and CustomPinsPage in [XFGoogleMapSample(dev branch)](https://github.com/amay077/Xamarin.Forms.GoogleMaps/tree/develop/XFGoogleMapSample) .

If you (and somebody) say "OK" then I'll deploy as stable version. 👌

**Comment by amay077** [comment]
v1.5.0 is now stable! 🎉
