### ISSUE TITLE
Camera is reseted to default location when map is on tabbedpage

### ISSUE THREAD

**Issue by deextercz** [amay077/Xamarin.Forms.GoogleMaps#101]
When I switch my application to third tab page camera position is reseted.
It is very interesting that switching to second page does not affect map camera position.
As you can see on this video: https://sendvid.com/mpfovxyl switching to third page affects map camera.
I think this relates to [#7](https://github.com/amay077/Xamarin.Forms.GoogleMaps/issues/7) but for sure I created this issue
Could you please confirm my idea?

**Comment by amay077** [comment]
Oh this is interesting.
Could you show me sample project for reproduce?

**Comment by deextercz** [comment]
Hello,
i uploaded my solution to https://github.com/deextercz/iMHD/tree/xamarin.forms

**Comment by deextercz** [comment]
Are you able to induce this issue?

**Comment by deextercz** [comment]
I created bug in xamarin, because it is alsi in xamarin.forms.map 
https://bugzilla.xamarin.com/show_bug.cgi?id=49057

**Comment by deextercz** [comment]
Should be this fixed in xamarin.forms.maps or in this project?

**Comment by deextercz** [comment]
I just investagated the problem and I think I got it.

[0:] Page No:1changed
12-26 22:17:40.334 W/FragmentManager( 5004): moveToState: Fragment state for FragmentContainer{ab1a12b8 #2 id=0x1 android:switcher:1:353799762} not updated inline; expected state 3 found 2
[0:] Page No:0changed
[0:] Page No:1changed
12-26 22:17:43.918 W/FragmentManager( 5004): moveToState: Fragment state for FragmentContainer{ab1a12b8 #2 id=0x1 android:switcher:1:353799762} not updated inline; expected state 3 found 2
[0:] Page No:2changed
12-26 22:17:46.750 I/Google Maps Android API( 5004): Google Play services package version: 10084070
12-26 22:17:46.750 W/f       ( 5004): Suppressed StrictMode policy violation: StrictModeDiskReadViolation
12-26 22:17:46.750 W/f       ( 5004): Suppressed StrictMode policy violation: StrictModeDiskWriteViolation
12-26 22:17:46.762 W/f       ( 5004): Suppressed StrictMode policy violation: StrictModeDiskReadViolation
12-26 22:17:46.762 D/dalvikvm( 5004): GC_CONCURRENT freed 1823K, 8% free 34916K/37796K, paused 1ms+2ms, total 9ms
12-26 22:17:46.766 W/f       ( 5004): Suppressed StrictMode policy violation: StrictModeDiskReadViolation
12-26 22:17:46.766 W/f       ( 5004): Suppressed StrictMode policy violation: StrictModeDiskWriteViolation
[0:] Page No:0changed
12-26 22:17:46.770 W/f       ( 5004): Suppressed StrictMode policy violation: StrictModeDiskReadViolation
12-26 22:17:46.818 D/GLHostConnection( 5004): Waiting for host to establish connection for PID 5004 (com.aulicon.imhd)
12-26 22:17:46.818 D/GLHostConnection( 5004): HostConnection::get() New Host Connection established 0xba57caa0, tid 5133
12-26 22:17:46.826 W/f       ( 5004): Suppressed StrictMode policy violation: StrictModeDiskReadViolation
12-26 22:17:46.826 W/f       ( 5004): Suppressed StrictMode policy violation: StrictModeDiskWriteViolation
12-26 22:17:46.870 D/dalvikvm( 5004): GC_CONCURRENT freed 1798K, 7% free 35166K/37796K, paused 0ms+1ms, total 21ms
12-26 22:17:46.870 D/dalvikvm( 5004): WAIT_FOR_CONCURRENT_GC blocked 20ms
12-26 22:17:46.874 D/dalvikvm( 5004): WAIT_FOR_CONCURRENT_GC blocked 6ms
12-26 22:17:46.918 D/dalvikvm( 5004): GC_FOR_ALLOC freed 1082K, 6% free 35760K/37796K, paused 6ms, total 6ms
12-26 22:17:46.922 I/dalvikvm-heap( 5004): Grow heap (frag case) to 38.985MB for 4194316-byte allocation
12-26 22:17:46.926 D/dalvikvm( 5004): GC_FOR_ALLOC freed 30K, 5% free 39826K/41896K, paused 7ms, total 7ms
12-26 22:17:46.934 D/dalvikvm( 5004): GC_CONCURRENT freed 142K, 5% free 39893K/41896K, paused 0ms+1ms, total 5ms
12-26 22:17:46.970 D/dalvikvm( 5004): GC_FOR_ALLOC freed 657K, 4% free 40541K/41896K, paused 11ms, total 11ms
12-26 22:17:47.038 D/dalvikvm( 5004): GC_FOR_ALLOC freed 6095K, 5% free 36034K/37796K, paused 5ms, total 5ms
12-26 22:17:47.082 D/dalvikvm( 5004): GC_FOR_ALLOC freed 723K, 6% free 36014K/38056K, paused 4ms, total 4ms
12-26 22:17:47.110 D/dalvikvm( 5004): GC_FOR_ALLOC freed 646K, 6% free 36017K/38056K, paused 5ms, total 5ms
12-26 22:17:47.142 D/dalvikvm( 5004): GC_FOR_ALLOC freed 519K, 6% free 36017K/38056K, paused 5ms, total 5ms
12-26 22:17:47.178 D/dalvikvm( 5004): GC_FOR_ALLOC freed 645K, 6% free 36020K/38056K, paused 5ms, total 5ms
12-26 22:17:47.226 D/dalvikvm( 5004): GC_FOR_ALLOC freed 647K, 6% free 36025K/38056K, paused 7ms, total 7ms
12-26 22:17:47.262 D/dalvikvm( 5004): GC_FOR_ALLOC freed 648K, 6% free 36029K/38056K, paused 4ms, total 4ms
12-26 22:17:47.306 D/dalvikvm( 5004): GC_FOR_ALLOC freed 645K, 6% free 36033K/38056K, paused 6ms, total 6ms
12-26 22:17:47.350 D/dalvikvm( 5004): GC_FOR_ALLOC freed 646K, 6% free 36037K/38056K, paused 5ms, total 5ms
On page 0 is MAP

so after click on Page0 there is executed garabage collector and it deletes all from memmory.
But it happens only when you click from page 2 to page 0 (if you have 3 tabs)
Could you help me with this?

**Comment by deextercz** [comment]
@amay077 how about this solution?

        public MapSpan VisibleRegion
        {
            get { return _visibleRegion; }
            internal set
            {
                if (_visibleRegion == value)
                    return;
                if (value == null)
                    throw new ArgumentNullException(nameof(value));
                OnPropertyChanging();
                _visibleRegion = value;
                OnPropertyChanged();
                InitialCameraUpdate = CameraUpdateFactory.NewBounds(value.ToBounds(), 0); # fix for #101
            }
        }


I don´t know the reason of using OnPropertyChanging(); and OnPropertyChanged(); maybe it could be removed.

**Comment by amay077** [comment]
Hi @deextercz ,
You can write same code in app side.

```csharp
public partial class BasicMapPage : ContentPage
{
    public BasicMapPage()
    {
        InitializeComponent();

        map.CameraChanged += (sender, e) =>
        {
            map.InitialCameraUpdate = CameraUpdateFactory.NewCameraPosition(e.Position);
        };
    }
}
```

``OnPropertyChanging`` and ``OnPropertyChanged`` are needed because these are notifying ``VisibleRegion`` property before changing and after changed.

**Comment by deextercz** [comment]
Hello @amay077 ,
I tried your solution with 1.8.0-beta5, but it freezes on my splash screen.
Mentioned my solution works.
Is there possibility to merge my changes and reopen PR #172 ?

**Comment by amay077** [comment]
Could you open a new issue first?
