### ISSUE TITLE
Traffic layer on Google Maps

### ISSUE THREAD

**Issue by prajithmp** [amay077/Xamarin.Forms.GoogleMaps#103]
Can we overlay google traffic layer on Xamarin.Forms.GoogleMaps, or is there any workaround to implement this feature.

same as of google map api traffic layer
Eg . https://developers.google.com/maps/documentation/javascript/examples/layer-traffic

**Comment by deextercz** [comment]
Hello,
I just created pullrequest for your issue.
https://github.com/amay077/Xamarin.Forms.GoogleMaps/pull/104
Could you please check that it is working for all platform? I was able to test it just on Android

**Comment by amay077** [comment]
Thanks!
I'll review it.

**Comment by amay077** [comment]
I deployed [1.7.0-beta3](https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/1.7.0-beta3) that includes this.
Please check it.

**Comment by deextercz** [comment]
It looks like it is working, please close this issue.

**Comment by amay077** [comment]
👍
