### ISSUE TITLE
Remove osbolete things

### ISSUE THREAD

**Issue by deextercz** [amay077/Xamarin.Forms.GoogleMaps#107]
I found things that are marked as deprecated, but still used in solution.
Like in this file https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/master/Xamarin.Forms.GoogleMaps/Xamarin.Forms.GoogleMaps/Pin.cs#L59
https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/master/Xamarin.Forms.GoogleMaps/Xamarin.Forms.GoogleMaps.Android/Extensions/MapViewExtensions.cs#L37

Could you go throw and replace it, or write comment why it is deprecated.

**Comment by amay077** [comment]
> https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/master/Xamarin.Forms.GoogleMaps/Xamarin.Forms.GoogleMaps/Pin.cs#L59

You can use ``Map.PinClicked`` instead of ``Pin.Clicked``.
Because ``Pin.Clicked`` is need handling all of pins.
I think ``Pin.Clicked`` not so good.

**Comment by amay077** [comment]
> https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/master/Xamarin.Forms.GoogleMaps/Xamarin.Forms.GoogleMaps.Android/Extensions/MapViewExtensions.cs#L37

This is for keeping downward compatibility.

``MapView.Map`` is [Xamarin Google Play Services - Maps](https://www.nuget.org/packages/Xamarin.GooglePlayServices.Maps/)'s member.

In older versions:
``MapView.Map`` is available or deprecated.

In newer versions:
``MapView.Map`` is deleted. If call this then throw ``MissingMethodException ``.

X.F.GoogleMaps should support both cases.

**Comment by deextercz** [comment]
OK, now I got it, the reason of backward compatibility.
Regarding pin clicked event if I replace 
public event EventHandler Clicked;
with
public event EventHandler<PinClickedEventArgs> PinClicked;
it will be ok?

**Comment by amay077** [comment]
Yes, you got it. 👍
