### ISSUE TITLE
Google maps on UWP/Windows Phone

### ISSUE THREAD

**Issue by deextercz** [amay077/Xamarin.Forms.GoogleMaps#109]
Hello,
have you ever been thinking about GMaps .Net?
http://www.independent-software.com/gmap-net-tutorial-maps-markers-and-polygons/
I think it could be good for your project more than Bing maps, dont you mind?
If not would you mind to provide Xamarin.Forms.Maps for Windows phone?

**Comment by amay077** [comment]
I don't have plan to supporting GMap.NET.
Because this is not native API(probably javascript API).
Also this does not support UWP.
