### ISSUE TITLE
Some Pin images from view are not rendered

### ISSUE THREAD

**Issue by deextercz** [amay077/Xamarin.Forms.GoogleMaps#114]
Hello,
I have a custom Pin View like this
`<?xml version="1.0" encoding="UTF-8"?>
<StackLayout xmlns="http://xamarin.com/schemas/2014/forms"
			 xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
			 WidthRequest="40"
			 HeightRequest="40"
			 x:Class="iMHD.Extensions.CustomPin">
  <AbsoluteLayout VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand">
    <Grid>
      <Image x:Name="PinImage" Source="symbol_fore_close.png" WidthRequest="40" HeightRequest="40" />
      <Label Text="{Binding PinText}" TextColor="Red" HorizontalTextAlignment="Center" FontSize="12"
        BackgroundColor="Transparent" WidthRequest="30" HeightRequest="30" Margin="0, 10, 0, 0" />
    </Grid>
  </AbsoluteLayout>
</StackLayout>
`
Sometimes there is rendered just label not an image

![capture1](https://cloud.githubusercontent.com/assets/23039506/20367054/207cc718-ac4e-11e6-9e82-74f124174f76.png)
Could you please help me to find out what is going on?
I am able to provide whole solution to induce this issue

**Comment by rpcarleto** [comment]
Same problem here.

**Comment by deextercz** [comment]
My logic is event based so It is executed after map appeared.

**Comment by deextercz** [comment]
It looks like using icon FromView is not reliable, using fromBundle or FromStream is much better.
If you can use it I would recommend that.

**Comment by Gavrielo** [comment]
I get this too, @rpcarleto   could you show the method you used for view appearing on the CustomPinView class?
I have this :
```
	public partial class CustomPinView : StackLayout
	{
        string _imageSource;
		public CustomPinView(string pinName)
		{
			try
			{
				InitializeComponent();
				BindingContext = this;
			}
			finally
			{
                CustomPinViewSource.Source = pinName;
			}
		}
       }
```
