### ISSUE TITLE
Quick Map Styling - setMapStyle

### ISSUE THREAD

**Issue by sirfilipef** [amay077/Xamarin.Forms.GoogleMaps#117]
Can we set a style like this?
https://developers.google.com/maps/documentation/android-api/styling

**Comment by deextercz** [comment]
It look like that it is easy to implement, if you have time feel free to inplement it.
I dont have right now time for implementation. If you will be not able to do it i will do it later.

**Comment by amay077** [comment]
Interesting!

Can we use same json in Goodle Maps iOS SDK?

* https://developers.google.com/maps/documentation/ios-sdk/styling

**Comment by sirfilipef** [comment]
I think is the same json.
https://snazzymaps.com/

**Comment by sirfilipef** [comment]
I think is the same json.
https://snazzymaps.com/

**Comment by nunofaria007** [comment]
Xamarin.Forms latest nugets depends on Xamarin.Android.Support.v4 23.3.0 while the Play Services 9.6  binding (which includes this feature) depends on Xamarin.Android.Support.v4 24.2.1 or later

**Comment by amay077** [comment]
Hi @nunofaria007,
If we want to use styling then should I update Xamarin.Android.Support.v4 package?

**Comment by nunofaria007** [comment]
For styling, the newest Xamarin.GooglePlayServices.* nugets are needed, which in turn require the latest Xamarin.Android.Support.v4, which seems to be incompatible with any latest Xamarin.Forms nuget (including pre-releases). So i guess for now this isn't accomplishable on Xamarin.Forms :(

**Comment by amay077** [comment]
Thanks @nunofaria007 ,
I agree with you.
We have better wait until the latest "stable" Xamarin.Forms package.

...And we should consider keeping compatibility for old version users.

**Comment by nunofaria007** [comment]
Regarding compatibility, do you think in the future you could create a new branch with the latest features available, for those who keep up with Xamarin.Forms new releases?

**Comment by amay077** [comment]
I will keep current dependency versions in X.F.GoogleMaps v1.x.
Perhaps in v2.x, I will change dependency versions to Xamarin.Forms v2.3.3 or greater.

But if possible, I want to provide GoogleMaps new features(e.g. styling) to latest Xamarin.Forms version users with keep compatibility.

**Comment by deextercz** [comment]
Could you create a branche lets say next change these dependency and rebase on master?

**Comment by amay077** [comment]
Yes.
I will create branch and announce when start developing "vNext".
But not the time yet.
I will complement current GoogleMaps API features to X.F.GoogleMaps first.

**Comment by rizaanlakay** [comment]
Hi, is there been any new developments around getting styling into this project? I really enjoy working with this mapping package you created.

**Comment by amay077** [comment]
I'm ready for implements this by #239 .
Wait a while!

**Comment by amay077** [comment]
I released [Xamarin.Forms.GoogleMaps v2.1.0-beta5](https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/2.1.0-beta5) .

<img src="https://user-images.githubusercontent.com/401369/27045670-998a4b9e-4fdc-11e7-93e0-40026718a708.png" width="300" />
<img src="https://user-images.githubusercontent.com/401369/27045686-ae2fcb32-4fdc-11e7-96d8-0ba9baca61b2.png" width="300" />

**Comment by amay077** [comment]
Released in https://github.com/amay077/Xamarin.Forms.GoogleMaps/releases/tag/v2.1.0-beta5
