### ISSUE TITLE
White square under current location iOS

### ISSUE THREAD

**Issue by alagaros** [amay077/Xamarin.Forms.GoogleMaps#118]
When going to the users current location there is a white square underneath the blue dot. I'm fairly sure this isn't intended.

All I am doing now is initialising the plugin in the AppDelegate. And loading a map using XAML into a ContentPage.

![image](https://cloud.githubusercontent.com/assets/16825568/20526126/feba676a-b0c2-11e6-8a23-87ef5117c22f.png)

Only tested on simulator, might also happen on real devices.

**Comment by mwerickson** [comment]
I am seeing the same behavior on iOS both on real devices and simulator  (1.7.0 and XF 2.3.2.127)

**Comment by amay077** [comment]
Is [Google APIs Maps iOS Library](https://www.nuget.org/packages/Xamarin.Google.iOS.Maps/) the same as this?
Is there someone who try it?

**Comment by deextercz** [comment]
I am not able to reproduce that, are you using FromView or FromBundle?

**Comment by deextercz** [comment]
https://code.google.com/p/gmaps-api-issues/issues/detail?id=7315 it is simulator issue, probably it should not be displayed on real device.

**Comment by amay077** [comment]
Thanks @deextercz ,
I'm clear.
Thus this issue has closed.

**Comment by timdmaxey** [comment]
I'm listening to the location how are you guys even getting the blue dot to show up? I'm getting the location, can move the map to the user's GPS location, but no blue dot??
