### ISSUE TITLE
Maps with Sample does not build

### ISSUE THREAD

**Issue by JKennedy24** [amay077/Xamarin.Forms.GoogleMaps#119]
A file called Variables.cs is missing from the project XFGoogleMapSample.local

https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/master/XFGoogleMapSample/XFGoogleMapSample/XFGoogleMapSample.local.csproj#L102

is missing from 

https://github.com/amay077/Xamarin.Forms.GoogleMaps/tree/master/XFGoogleMapSample/XFGoogleMapSample

It probably hasnt been checked in

**Comment by amay077** [comment]
Sorry, I didn't write "How to build sample apps" yet.

Please rename from ``Variable_sample.cs`` to ``Variable.cs``,
And put your Google Maps API Keys to ``Variable.cs``.

``Variable.cs`` is added in ``.gitignore``.
This way is prevent your API keys from your accidentally commit to git repository.

**Comment by JKennedy24** [comment]
Thats great. That works perfectly. Thanks
