### ISSUE TITLE
Android: Selecting pin from logic causes error

### ISSUE THREAD

**Issue by kochizufan** [amay077/Xamarin.Forms.GoogleMaps#12]
In Android sample project, adding New York pin and pushing "Select New York" button causes errors.

Error is at Android's MapRenderer#UpdateSelectedPin

```
        void UpdateSelectedPin(Pin pin)
        {
            if (pin == null)
            {
                foreach (var marker in _markers)
                {
                    marker.HideInfoWindow();
                }
            }
            else
            {
                // lookup pin
                Marker targetMarker = null;
                foreach (var marker in _markers)
                {
                    if ((string)pin.Id != marker.Id) <= Here
                        continue;

                    targetMarker = marker;
                    break;
                }

                if (targetMarker != null)
                    targetMarker.ShowInfoWindow();
            }
        }
```
and said "Specified cast is not valid".

Full error message is:

> System.InvalidCastException: Specified cast is not valid.
>   at Xamarin.Forms.GoogleMaps.Android.MapRenderer.UpdateSelectedPin (Xamarin.Forms.GoogleMaps.Pin pin) [0x00075] in /Users/xxxx/github/Xamarin.Forms.GoogleMaps/Xamarin.Forms.GoogleMaps/Xamarin.Forms.GoogleMaps.Android/MapRenderer.cs:408
>   at Xamarin.Forms.GoogleMaps.Android.MapRenderer.OnElementPropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs e) [0x00127] in /Users/xxxx/github/Xamarin.Forms.GoogleMaps/Xamarin.Forms.GoogleMaps/Xamarin.Forms.GoogleMaps.Android/MapRenderer.cs:313
>   at at (wrapper delegate-invoke) <Module>:invoke_void_object_PropertyChangedEventArgs (object,System.ComponentModel.PropertyChangedEventArgs)
>   at Xamarin.Forms.BindableObject.OnPropertyChanged (System.String propertyName) [0x0000a] in C:\BuildAgent2\work\aad494dc9bc9783\Xamarin.Forms.Core\BindableObject.cs:137
>   at Xamarin.Forms.Element.OnPropertyChanged (System.String propertyName) [0x00000] in C:\BuildAgent2\work\aad494dc9bc9783\Xamarin.Forms.Core\Element.cs:370
>   at Xamarin.Forms.BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindablePropertyContext context, System.Object value, Boolean currentlyApplying, SetValueFlags attributes, Boolean silent) [0x000f4] in C:\BuildAgent2\work\aad494dc9bc9783\Xamarin.Forms.Core\BindableObject.cs:581
>   at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, SetValueFlags attributes, SetValuePrivateFlags privateAttributes) [0x0014b] in C:\BuildAgent2\work\aad494dc9bc9783\Xamarin.Forms.Core\BindableObject.cs:378
>   at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value, Boolean fromStyle, Boolean checkAccess) [0x0005f] in C:\BuildAgent2\work\aad494dc9bc9783\Xamarin.Forms.Core\BindableObject.cs:531
>   at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value) [0x00000] in C:\BuildAgent2\work\aad494dc9bc9783\Xamarin.Forms.Core\BindableObject.cs:83
>   at Xamarin.Forms.GoogleMaps.Map.set_SelectedPin (Xamarin.Forms.GoogleMaps.Pin value) [0x00008] in /Users/xxxx/github/Xamarin.Forms.GoogleMaps/Xamarin.Forms.GoogleMaps/Xamarin.Forms.GoogleMaps/Map.cs:74
>   at XFGoogleMapSample.PinsPage+<PinsPage>c__AnonStorey0.<>m__5 (System.Object sender, System.EventArgs e) [0x00044] in /Users/xxxx/github/Xamarin.Forms.GoogleMaps/XFGoogleMapSample/XFGoogleMapSample/PinsPage.xaml.cs:99
>   at Xamarin.Forms.Button.Xamarin.Forms.IButtonController.SendClicked () [0x00020] in C:\BuildAgent2\work\aad494dc9bc9783\Xamarin.Forms.Core\Button.cs:122
>   at Xamarin.Forms.Platform.Android.AppCompat.ButtonRenderer+ButtonClickListener.OnClick (Android.Views.View v) [0x0000b] in C:\BuildAgent2\work\aad494dc9bc9783\Xamarin.Forms.Platform.Android\AppCompat\ButtonRenderer.cs:261
>   at Android.Views.View+IOnClickListenerInvoker.n_OnClick_Landroid_view_View_ (IntPtr jnienv, IntPtr native__this, IntPtr native_v) [0x00011] in /Users/builder/data/lanes/3415/7db2aac3/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Android.Views.View.cs:1806
>   at at (wrapper dynamic-method) System.Object:efa38258-6397-42b4-862f-3f6eaaac9efc (intptr,intptr,intptr)

**Comment by kochizufan** [comment]
Tested in And4.1.1 GenyMotion and And6.0.0 LG Nexus5X

**Comment by amay077** [comment]
Thanks for fixing!
