### ISSUE TITLE
#80 Disable MapToolbar in Android

### ISSUE THREAD

**Issue by hieumoscow** [amay077/Xamarin.Forms.GoogleMaps#120]
Hi, 
Is there a way for us to re enabled this back on Android for Map version 1.7.0? 
Is there a similar feature on iOS? 

Thank you plenty for your help!

**Comment by deextercz** [comment]
Hello,
I think it is possibke in Uisettings in your map

**Comment by hieumoscow** [comment]
Yeh, just found out its 
NativeMap.UiSettings.MapToolbarEnabled = true;
However this seems the options seems unavailable on iOS
Thanks

**Comment by deextercz** [comment]
I think this option is natively avaliable only for android. If not you can
add it for iOS
čt 24. 11. 2016 v 9:54 odesílatel Nguyen Nhu Hieu <notifications@github.com>
napsal:

**Comment by amay077** [comment]
Yes, iOS doesn't have MapToolbarEnabled.
You can access using [Custom Renderer](https://developer.xamarin.com/guides/xamarin-forms/custom-renderer/) or [Effects](https://developer.xamarin.com/guides/xamarin-forms/effects/) in your android project.

**Comment by dirkmouton** [comment]
Is it maybe possible to have a setting where this can be enabled for Android?
