### ISSUE TITLE
Error when change build to SDK Assemblies Only

### ISSUE THREAD

**Issue by leosoareslima** [amay077/Xamarin.Forms.GoogleMaps#124]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets: Error: Error executing task LinkAssemblies: error XA2006: Reference to metadata item 'Android.Gms.Maps.GoogleMap Android.Gms.Maps.MapView::get_Map()' (defined in 'Xamarin.Forms.GoogleMaps.Android, Version=1.7.0.4, Culture=neutral, PublicKeyToken=null') from 'Xamarin.Forms.GoogleMaps.Android, Version=1.7.0.4, Culture=neutral, PublicKeyToken=null' could not be resolved.

It's work perfectly when linker disabled

**Comment by amay077** [comment]
I can not reproduce it.

I changed linker setting to "Link SDK assemblies only" in XFGoogleMapSample.Droid project.
Re-build and ran on my emulator successfully.

![2016-11-25 20 43 50](https://cloud.githubusercontent.com/assets/401369/20624452/6a87a450-b350-11e6-8686-d773b1c27b47.png)

Do you have any more informations?

**Comment by amay077** [comment]
This is no longer response.
I closed it.

**Comment by SvenCarstensen** [comment]
I can reproduce this problem on my System.
If i switch from "Don't link" to "SDK Assemblies only" at Relase config, 
i get the same error.

<img width="942" alt="bildschirmfoto 2016-12-22 um 09 03 31" src="https://cloud.githubusercontent.com/assets/4954662/21419036/91fea0da-c825-11e6-98b9-19f13703d315.png">

**Comment by matteopiccioni** [comment]
I have the same problem in release config.
I have to  switch from "SDK Assemblies only" to "Don't link" at Relase Linker config

`/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets: 
Error: Error executing task LinkAssemblies: error XA2006: 
Could not resolve reference to 'Android.Gms.Maps.GoogleMap Android.Gms.Maps.MapView::get_Map()' 
(defined in assembly 'Xamarin.Forms.GoogleMaps.Android, Version=1.8.0.5, Culture=neutral, PublicKeyToken=null')
 with scope 'Xamarin.GooglePlayServices.Maps, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. 
When the scope is different from the defining assembly, it usually means that the type is forwarded.`
