### ISSUE TITLE
MapSpan.WithZoom doesn't work

### ISSUE THREAD

**Issue by leaguefun** [amay077/Xamarin.Forms.GoogleMaps#133]
How can I start the map by current location instead instead of "Rome" right after the map control loaded ? thanks

**Comment by amay077** [comment]
You can set initial location by ``Map.MoveToRegion`` in your page constructor.

ref: https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/41350ca25c241b91f3ad6cbac40b9456cb4de17c/XFGoogleMapSample/XFGoogleMapSample/CustomPinsPage.xaml.cs#L142

**Comment by leaguefun** [comment]
Thx, but no matter what zoom level i specified with the MoveToRegion(),	its always using the default setting ....

**Comment by RickTheHat** [comment]
I'm also seeing Rome no matter what I do too

**Comment by deextercz** [comment]
Where are you using move to region?

**Comment by RickTheHat** [comment]
Here's the code that I'm using:

**XAML**
            <maps:Map x:Name="MyMap"
                      HorizontalOptions="FillAndExpand"
                      VerticalOptions="FillAndExpand"
                      IsShowingUser="true" />
**CODE BEHIND IN CONSTRUCTOR** 
			// set initial map pin
			var _initialPin = new Pin();
			_initialPin.Position = new Position(37.1, -95.7);
			MyMap.MoveToRegion(MapSpan.FromCenterAndRadius(_initialPin.Position, Distance.FromMiles(1)).WithZoom(8), true);

			Init().ConfigureAwait(false);
		}

**Init().ConfigureAwait(false);**
Then in my Init() method is where I start building multiple pins for the map. Once I get those pins added to the map, I re-center and then call the "MoveToRegion" method again as below:
				// get radius from center
				_radiusFromCenter = GetGreatestDistanceBetweenCenterPinAndOtherPinsInKilometers(_centerPin, _otherPins);
				_otherPins.ForEach(MyMap.Pins.Add);
				MyMap.MoveToRegion(MapSpan.FromCenterAndRadius(_centerPin.Position, Distance.FromMiles(_radiusFromCenter + 0.3)));

* I still see "Rome" but I expected to see the map start at 37.1 / -95.7 *

**Comment by amay077** [comment]
I tried follows code in Page constructor.

```
var initialPos = new Position(37.1, -95.7);
//map.MoveToRegion(MapSpan.FromCenterAndRadius(initialPos, 
    Distance.FromMiles(1)), true);   // <-- works fine
map.MoveToRegion(MapSpan.FromCenterAndRadius(initialPos, 
    Distance.FromMiles(1)).WithZoom(8), true); // <-- doesn't work
```

**Not use ``.WithZoom(8)`` --> Works fine**
![untitled3](https://cloud.githubusercontent.com/assets/401369/20857637/a50ace6a-b975-11e6-80a1-7368bd34c259.gif)

**Use ``.WithZoom(8)`` --> Doesn't work**
![untitled4](https://cloud.githubusercontent.com/assets/401369/20857638/a8045578-b975-11e6-9a18-c5ecf03d4367.gif)


I don't have been to use ``MapSpan.WithZoom`` method. :sweat:

**Comment by deextercz** [comment]
I think it is caused because public static MapSpan FromCenterAndRadius(Position center, Distance radius) is static method.
Even if this will create new instance of MapSpan and on this you will call public MapSpan WithZoom(double zoomFactor) where properties should be set right?
I am not able now to test it and debug it.
Could zou think about that?

**Comment by FWJay** [comment]
I'm getting Rome on my device, but it's starting with whatever I set as Custom location on the iOS sdk

**Comment by LukasThijs** [comment]
Well you are using a emulator :) you need to send your location to the device just like with android:

http://imgur.com/a/w2vwm


This will give the device a user pinpoint, also try using a physical in these cases.

**Comment by JeanCollas** [comment]
That is the code I use, just after the init components, called :

    public ConstructorOfPage() {
        Context=LoadContext();
        InitializeComponent();
        MapSpan ms = null;
        try { ms = MapSpan.FromCenterAndRadius(Context.MapRegion.Center, Context.MapRegion.Radius); } catch { }
        InitRegion = ms;
        InitMoveToRegion()

[...]

        MapSpan InitRegion { get; set; }
        private async void InitMoveToRegion()
        {
            await Task.Delay(2000);
            if (InitRegion != null)
                MainMap.MoveToRegion(InitRegion);
        }

Works well...

**Comment by JeanCollas** [comment]
My pull request https://github.com/amay077/Xamarin.Forms.GoogleMaps/pull/151 should help you.
It allows binding the Map Region, so you can initialize with a fixed or binded MapSpan value.

**Comment by amay077** [comment]
You can use ``Map.InitialCameraUpdate`` , ``MoveCamera`` and ``AnimateCamera`` instead of ``MoveToRegion``.
