### ISSUE TITLE
Suggestion - Web Map Service (WMS) support

### ISSUE THREAD

**Issue by happyfr34k** [amay077/Xamarin.Forms.GoogleMaps#135]
It would be really helpful to have a WMS support.

**Comment by amay077** [comment]
I don't have plan for it.
Because Native Google Maps API doesn't support [WMS spec](http://www.opengeospatial.org/standards/wms).
We can only use [custom tile layers](https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/master/XFGoogleMapSample/XFGoogleMapSample/TilesPage.xaml.cs).
