### ISSUE TITLE
Some combinations of PinPages button causes strange behavior

### ISSUE THREAD

**Issue by kochizufan** [amay077/Xamarin.Forms.GoogleMaps#14]
Some combinations of pushing PinPages buttons causes strange behavior.

For example,

* Add pin to Tokyo => Select Tokyo by tapping marker => Clear Selection => Dialog says "Pin is not selected"
** iOS: incorrect
** Android: incorrect

* Add pin to New York => Select New York by button => Remove pin of New York => Add pin to New York again => Select New York by button again => Not selected
** iOS: incorrect
** Android: incorrect

* Add pin to New York => Select New York by button => Clear pins => Add pin to New York again => Clear selection once => Nothing occurs => Clear selection again => Dialog says "Pin is not selected"
** iOS: incorrect
** Android: incorrect

Other examples will be added as comment if I will find.

**Comment by amay077** [comment]
Thank you for testing.

I should consider about "Map.SelectedPinChanged" event. 
First case's reason is Map.SelectedPin property does not update when tapping marker.
I think similar reasons about second and third cases.

**Comment by amay077** [comment]
Fix this issues in develop branch. - https://github.com/amay077/Xamarin.Forms.GoogleMaps/tree/develop
Please try this again if possible.

**Comment by amay077** [comment]
Also update nuget package ver 1.1.1-beta1 -  https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/1.1.1-beta1
(This is pre-release version.)

**Comment by kochizufan** [comment]
It looks fixed.

**Comment by amay077** [comment]
Thanks!
I should write unit test immediately.

**Comment by amay077** [comment]
Fixed at v1.1.1
