### ISSUE TITLE
Is it possible to make it show inline directions betweens sadder and daddr

### ISSUE THREAD

**Issue by FWJay** [amay077/Xamarin.Forms.GoogleMaps#145]
I'd like a feature where we can generate a path between one chosen geo-coordinate to another and display it within the window. how easy would it be to enable this?

**Comment by deextercz** [comment]
I think it should be possible, I saw somethink like this on this page: https://iris.bmhd.cz/ If you click on vehicle it will paint a route.

**Comment by amay077** [comment]
This is no longer response.
I closed it.
