### ISSUE TITLE
Map.MoveToRegion does not incorperate radius (or does so incorrectly)

### ISSUE THREAD

**Issue by JKennedy24** [amay077/Xamarin.Forms.GoogleMaps#146]
Running the following code:

```
var centerP = new Position(lat, long);
MapSpan.FromCenterAndRadius(centerP, 400);
MyMap.MoveToRegion(center, false);
```

Gives different zoom levels for all 3 platforms.

Does anyone know why this is? Is the radius being accounted for?

**Comment by amay077** [comment]
I checked in Android and iOS.
MapSpan.FromCenterAndRadius returns same value.

And I looks ``MoveToRegion`` implementations are same.

* [Android](https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/5d483e85ef8e64fdb5047e23b36e20862d79df21/Xamarin.Forms.GoogleMaps/Xamarin.Forms.GoogleMaps.Android/MapRenderer.cs#L159)
* [iOS](https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/5d483e85ef8e64fdb5047e23b36e20862d79df21/Xamarin.Forms.GoogleMaps/Xamarin.Forms.GoogleMaps.iOS/MapRenderer.cs#L214)

I think this is native API's behavior by each platform.

**Comment by JKennedy24** [comment]
Yes and [UWP](https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/master/Xamarin.Forms.GoogleMaps/Xamarin.Forms.GoogleMaps.UWP/MapRenderer.cs#L148)

This must be the API's behavior. I'll close for now
