### ISSUE TITLE
java.Lang.IllegalArgumentException: hue outside range

### ISSUE THREAD

**Issue by LukasThijs** [amay077/Xamarin.Forms.GoogleMaps#148]
Hey,

I don't know if this is known behavior, but when using this component it will crash when trying to add a custom colored pin with the color red or anything that is quite red (Color.Maroon for example).

I have made a forum post on the xamarin forums trying to fix this issue and finally managed to solve it the link is here [link post](https://forums.xamarin.com/discussion/84238/java-lang-illegalargumentexception-hue-outside-range#latest)

I don't know if this component is the one causing the issue, but maybe you can take a look into it :)

Cheers and thanks for the awesome component!

Luuk

**Comment by amay077** [comment]
I got it.

This is Native GoogleMaps Android API's design

* [BitmapDescriptorFactory  |  Google APIs for Android  |  Google Developers](https://developers.google.com/android/reference/com/google/android/gms/maps/model/BitmapDescriptorFactory.html#defaultMarker(float))

> The hue of the marker. Value must be greater or equal to 0 and less than 360.

[Hue - Wikipedia](https://en.wikipedia.org/wiki/Hue) is a "degree", which means 360 is equal to 0.

## NOTICE

Hue is not color, this is part of color component.
So ``BitmapDescriptorFactory.DefaultMarker(Color.Maroon)`` and ``View.BackgroundColor = Color.Maroon`` is **not** same in Android.

**Comment by amay077** [comment]
I fixed it.

**Comment by LukasThijs** [comment]
Thanks for fixing the issue and the brief explanation!

**Comment by LukasThijs** [comment]
When will this be added to the pre-release?

**Comment by ilyabelkin** [comment]
If anyone needs to colour their pins red before the fix is released, here's the value that will pass validation and look red: BitmapDescriptorFactory.DefaultMarker(Color.FromHex("FF1100"))

Similarly, FFDDCC will also work.

Cheers!

**Comment by amay077** [comment]
I released [1.7.1-beta3](https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/1.7.1-beta3) that contains fixing this.

(But I forgot added to release notes :disappointed_relieved: .)

**Comment by ilyabelkin** [comment]
Thank you, the fix works!
