### ISSUE TITLE
Supports XAML Previewer for Visual Stuidio/Xamarin Studio

### ISSUE THREAD

**Issue by FWJay** [amay077/Xamarin.Forms.GoogleMaps#153]
Is it possible to make ti work with the Xamarin Forms preview window like Maps would? the error currently says
> Invalid XAML: Could not create a native instance of the type 'Google.Maps.MapView': the native class hasn't been loaded. It si possible to ignore this condition by setting ObjCRunTime.Class.ThrowOnInitFailure to false

This will help me design the elements on the page around the map

**Comment by amay077** [comment]
I don't support XAML preview in Visual Studio or Xamarin Studio.

(I don't know how to support it.)

**Comment by FWJay** [comment]
why not just show nothing, right now it gets an error there and the whole page doesn't work. could you try returning a null page or a blank page if it is in the previewer?

**Comment by amay077** [comment]
I found the solution for me -  [Xamarin.Forms XAML Previewer - Determine if in Design Mode in Code Behind and XAML similar to Blend — Xamarin Forums](https://forums.xamarin.com/discussion/68440/xamarin-forms-xaml-previewer-determine-if-in-design-mode-in-code-behind-and-xaml-similar-to-blend)

I'll try apply to X.F.GoogleMaps.

**Comment by amay077** [comment]
I made it.
Render empty rectangle(fillColor = #008080) when ``FormsGoogleMaps.Init`` not called.
Also contains XAML Previewer for Visual Studio/Xamarin Studio.

![2017-01-10 20 56 48](https://cloud.githubusercontent.com/assets/401369/21805414/648379e4-d777-11e6-8dbe-572b5170684a.png)

**Comment by FWJay** [comment]
Thanks! what build is it?

**Comment by amay077** [comment]
Yes, [1.7.1-beta4](https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/1.7.1-beta4) including this.

Probably you should do listed operations:

* Update Xamarin.Forms nuget package(each projects) to 2.3.3.x
* Clean and Rebuild each projects
* Restart Xamarin Studio

**Comment by amay077** [comment]
No problem?
Okay closed it.
