### ISSUE TITLE
Label tap event

### ISSUE THREAD

**Issue by LukasThijs** [amay077/Xamarin.Forms.GoogleMaps#154]
I wonder is there a possibility to attach a tap-event to the label that pops up when you click the Pin?

I tried adding this functionality by trying to inherit the pin class and overriding the label property with a label + gesturereconizer. Only the sad thing is the Pin class is sealed which does not allow me to inherit at all.

Is there any plans to add this functionality or is there a way to trigger this behavior?

**Comment by JeanCollas** [comment]
It is the windowinfoclicked event

**Comment by LukasThijs** [comment]
Well when looking into the maps objects events I don't see this InfoWindowClicked event. How can I find this in this component?

**Comment by JeanCollas** [comment]
Sorry I don't know about the nugets packages, I work directly from the repository. The package may be at an older version. If you stick to nugets, @amay077 will probably answer much better :)

**Comment by LukasThijs** [comment]
OK thanks for answering, yeah I am using the Nuget package which should be on par with the current repository. 

Anyway could you give me a example piece of code how to trigger the event? So I can test it myself.

Thanks in advance!

Luuk

**Comment by JeanCollas** [comment]
https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/master/XFGoogleMapSample/XFGoogleMapSample/PinsPage.xaml.cs
line 177

**Comment by amay077** [comment]
Hi @LukasThijs  ,

``InfoWindowClicked`` is contained in ver [1.7.2-beta2](https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/1.7.1-beta2).

But this is "pre-release".
You should ☑ Show Pre-release packages in nuget package manager.

**Comment by LukasThijs** [comment]
Hi @amay077 

Great! I was already about to do that :)! 

I will update it to the latest pre-release, thanks alot!

Cheers,

Luuk
