### ISSUE TITLE
What is the reason to prefer a global map pin clicked event?

### ISSUE THREAD

**Issue by JeanCollas** [amay077/Xamarin.Forms.GoogleMaps#155]
I am trying to understand the reason why you put a global event instead "preferred" over individual events.
Is it related to binding or just "more convenient"? (I don't have a religion about it, however I think both ways should be accessible (why not?)

The idea of a global event handler is good if all pins are of the same type, however for some "classes" of pin with different behavior, it seems easier to handle it on a "per pin" basis.

**Comment by amay077** [comment]
Are your opinions shown below code?

```
Pin pinA = new Pin();
pinA.Clicked += (sender, args) => { /* Handle PinA click */ };
pinA.InfoWindowClicked += (sender, args) => { /* Handle PinA InfoWindow click */ };

Pin pinB = new Pin();
pinB.Clicked += (sender, args) => { /* Handle PinB click */ };
pinB.InfoWindowClicked += (sender, args) => { /* Handle PinB InfoWindow click */ };
```

**Comment by JeanCollas** [comment]
I am not sure to understand your answer, what do you mean? :) (I agree you can do it, but you marked it as obsolete, that is what I don't understand)

**Comment by amay077** [comment]
> global event handler is good if all pins are of the same type

Yes, many cases are all pins = same behavior.
My reason is this.

And one more thing,
Individual Pin event is difficult to manage event subscribe(``+=``) and unsubscribe(``-=``).  
Global event is [very easy](https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/master/XFGoogleMapSample/XFGoogleMapSample/PinsPage.xaml.cs#L115).

**Comment by JeanCollas** [comment]
Yes, I see, just depending on cases one or the other are more appropriate. However regarding the event handlers subscriptions/unsub, I guess Commands have a much better behavior :)

**Comment by amay077** [comment]
I suggest [Xamarin.Forms.GoogleMaps.Bindings](https://github.com/nuitsjp/Xamarin.Forms.GoogleMaps.Bindings/blob/master/Sample/GoogleMaps.Bindings/GoogleMaps.Bindings/Views/PinsPage.xaml#L48) that provide Command for Pin's action with XAML.
