### ISSUE TITLE
Additional Geocoder API like City

### ISSUE THREAD

**Issue by lindblomc** [amay077/Xamarin.Forms.GoogleMaps#157]
I need to access the Admin / City name of a location but current implementation of Geocoder API only returns address lines in GetAddressesForPositionAsync

I would like to see API to return Admin area / City also.
Eg. GetCityForPositionAsync

Thanks
/Claes

**Comment by amay077** [comment]
Hi @lindblomc ,

Sorry, Geocoder is a "free gift".
This is only for keep compatibility with [Xamarin.Forms.Maps](https://developer.xamarin.com/api/type/Xamarin.Forms.Maps.Geocoder/).
My motivation is negative for supports geocoders.
