### ISSUE TITLE
Invoke click on pin

### ISSUE THREAD

**Issue by deextercz** [amay077/Xamarin.Forms.GoogleMaps#159]
Purpose of this task is programatically click on pin.
When I search for pin and pin is found I want to view infoWindow with details about pin.

**Comment by JeanCollas** [comment]
I think you just need to set the selected pin to have this behavior ;)

**Comment by deextercz** [comment]
Yes, sure but this funcionality is easy, you are able to use Tag where you can store some identifier.

**Comment by deextercz** [comment]
You were right, thank you.
