### ISSUE TITLE
Error in Xamarin.UWP

### ISSUE THREAD

**Issue by JonAlco** [amay077/Xamarin.Forms.GoogleMaps#165]
>	Intermark.UWP.exe!Intermark.UWP.App.InitializeComponent.AnonymousMethod__5_1(object sender, Windows.UI.Xaml.UnhandledExceptionEventArgs e) Línea 53	C#

in MainPage

`

        {
            this.InitializeComponent();

            Xamarin.FormsGoogleMaps.Init("MI KEY");

            LoadApplication(new Intermark.App());
        }

`

Please help me.

**Comment by JeanCollas** [comment]
A full stacktrace would probably be more useful :)

**Comment by amay077** [comment]
This is no longer response.
Could you provide more information for reproduce?

**Comment by amay077** [comment]
I closed it.
If you have any problems then re-open it.
