### ISSUE TITLE
User current location pin not showing up anymore?

### ISSUE THREAD

**Issue by LukasThijs** [amay077/Xamarin.Forms.GoogleMaps#167]
Hey,

I am using your component for a while now and it seems to work fine and all. But I have installed the latest pre-release to fix the red color bug and now the showuserpin is not showing up anymore.

It won't navigate to the current location as well I hope you can take a look into it.

Cheers,

Luuk

**Comment by deextercz** [comment]
Have xou set IsShowingUser to true?
Also if you are using emulator have you set location?

**Comment by LukasThijs** [comment]
Yes I did , and I also send in the location with the android emulator by longitude en latitude

**Comment by deextercz** [comment]
Try older versions to determine where is the bug

**Comment by LukasThijs** [comment]
Fixed, installed the newest latest pre-release and also restarted the buggy emulator :) Thanks closing this one!
