### ISSUE TITLE
Adding/removing more GroundOverlay's crash on Android

### ISSUE THREAD

**Issue by lindblomc** [amay077/Xamarin.Forms.GoogleMaps#171]
I have implemented Overlays in my app and first time I add an overlay it works without any issues on Android and iOS.

However, if I want to change the overlay to another Android will crash and on iOS nothing happens. I have tried clearing overlays before adding new GroundOverlay but also just adding new GroundOverlay with same result.

Here is a short snippet of code to show how I replace overlay on a command from UI.

`// Remove current overlay
Map.GroundOverlays.Clear();

// Add new overlay
                _overlay = new GroundOverlay()
                {
                    Bounds = new Bounds(new Position(mapOverlay.Bounds.SouthWest.Latitude, mapOverlay.Bounds.SouthWest.Longitude),
                                        new Position(mapOverlay.Bounds.NorthEast.Latitude, mapOverlay.Bounds.NorthEast.Longitude)),
                    Icon =OverlayImage,
                    Transparency = 0.5f,
                    Tag = _viewModel.CurrentForecastDate
                };

                forecastMap.GroundOverlays.Add(_overlay);`

**Stacktrace**:
[AndroidRuntime] java.lang.NullPointerException
[AndroidRuntime] 	at com.google.a.a.ae.a(Unknown Source)
[AndroidRuntime] 	at com.google.maps.api.android.lib6.e.do.<init>(Unknown Source)
[AndroidRuntime] 	at com.google.maps.api.android.lib6.e.dn.a(Unknown Source)
[AndroidRuntime] 	at com.google.maps.api.android.lib6.e.fg.<init>(Unknown Source)
[AndroidRuntime] 	at com.google.maps.api.android.lib6.e.ev.a(Unknown Source)
[AndroidRuntime] 	at com.google.android.gms.maps.internal.j.onTransact(SourceFile:182)
[AndroidRuntime] 	at android.os.Binder.transact(Binder.java:387)
[AndroidRuntime] 	at com.google.android.gms.maps.internal.IGoogleMapDelegate$zza$zza.addGroundOverlay(Unknown Source)
[AndroidRuntime] 	at com.google.android.gms.maps.GoogleMap.addGroundOverlay(Unknown Source)

**Comment by amay077** [comment]
Could you give me complete code for reproduce?
How did you create ``OverlayImage`` ? (e.g.``BitmapDescriptorFactory.FromBundle``, ``DefaultMarker``, ``FromStream`` or ``FromView``)

 If you use ``FromBundle``, you should set [build action to "AndroidAsset"](https://github.com/amay077/Xamarin.Forms.GoogleMaps/issues/169#issuecomment-272695540) .

**Comment by lindblomc** [comment]
Hi,
BitmapDescriptor was created by BitmapDescriptorFactory.FromStream
I finally found the issue but could not report back on Friday when GitHub was unreachable.

I was trying to use MVVM with as little code behind as possible in the view and needed to call DisplayActionSheet to select layer in the map. It resulted in a bad workaround that probably locked the thread or that wrong thread was calling the map component.
I discarded that bad solution and did the logic in the view instead.

You can probably close this issue.

Best regards
/Claes

**Comment by amay077** [comment]
Thanks, I closed this.
