### ISSUE TITLE
IsVisible property for pins

### ISSUE THREAD

**Issue by FWJay** [amay077/Xamarin.Forms.GoogleMaps#173]
is it possible to have an IsVisible bindable property for pins so that they can be hidden and shown based on a filter? right now I have to set their coordinates to Antarctica to filter them

**Comment by amay077** [comment]
``IsVisible`` property is not support.

Native GoogleMaps Android API has [``Marker.Visibility``](https://developers.google.com/android/reference/com/google/android/gms/maps/model/Marker), 
but Native GoogleMaps iOS SDK does not have visibility in [GMSMaker](https://developers.google.com/maps/documentation/ios-sdk/reference/interface_g_m_s_marker)(or GMSOverlay) class.

Maybe if we want to hide to GMSMarker then set ``null`` to [``GMSMarker.map``](https://developers.google.com/maps/documentation/ios-sdk/reference/interface_g_m_s_overlay.html#adf140b1a471eec414d7bd3917beb3ef0) (same as remove pin).

I'll try it.

**Comment by FWJay** [comment]
thanks!

**Comment by amay077** [comment]
I released [1.8.0-beta1](https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/1.8.0-beta1) that contains ``Pin.IsVisible`` property.
Also added to [sample](https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/master/XFGoogleMapSample/XFGoogleMapSample/PinsPage.xaml.cs#L116).

![2017-01-19 20 53 08](https://cloud.githubusercontent.com/assets/401369/22106033/38f0d2bc-de8a-11e6-99f8-621b2854e524.png)

**Comment by amay077** [comment]
No problem?
Okay closed it.
