### ISSUE TITLE
User location button click event listener

### ISSUE THREAD

**Issue by ekomsctr** [amay077/Xamarin.Forms.GoogleMaps#176]
Hi, is it possible to handle the click event on the locate user button? I need to do some distance calculations after it is being clicked.

Thanks

**Comment by amay077** [comment]
I can not provide click event of locate buttons.
Because it shown by native Google Maps SDK and I can not handling button click.

**Comment by deextercz** [comment]
I think it could be possible https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap.OnMyLocationButtonClickListener

**Comment by amay077** [comment]
Thanks @deextercz ,
I found in iOS side!

* https://developers.google.com/maps/documentation/ios-sdk/reference/protocol_g_m_s_map_view_delegate-p.html#ac0e0171b811e839d9021800ca9fd33f4

**Comment by amay077** [comment]
I released [1.8.0-beta2](https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/1.8.0-beta2) what contains ``Map.MyLocationButtonClicked`` event.
Also added sample for it.

* https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/master/XFGoogleMapSample/XFGoogleMapSample/BasicMapPage.xaml.cs#L76-L84

**Comment by amay077** [comment]
No problem?
Okay closed it.
