### ISSUE TITLE
I can not use it

### ISSUE THREAD

**Issue by amolitos** [amay077/Xamarin.Forms.GoogleMaps#177]
I can use Xamarin.Forms.Maps without problems but if I want to use Xamarin.Foms.GoogleMaps only shows me:
![16196785_1345413415528829_1354373689_o](https://cloud.githubusercontent.com/assets/15843598/22163621/2a33d80c-df19-11e6-996f-7f7004283f12.jpg)

My packages:
![use](https://cloud.githubusercontent.com/assets/15843598/22163714/8fd53c6e-df19-11e6-921e-e66b43076057.png)

**Comment by deextercz** [comment]
This is expected behaviour

**Comment by amolitos** [comment]
Ok, then how do I do it to be displayed?

**Comment by amay077** [comment]
You should call ``Xamarin.FormsGoogleMaps.Init`` in your ``MainActivity.cs(Android)`` and ``AppDelegate.cs(iOS)``

* https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/master/XFGoogleMapSample/Droid/MainActivity.cs#L24
* https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/master/XFGoogleMapSample/iOS/AppDelegate.cs#L16

Also setting Google Maps API Key each platforms.

* https://github.com/amay077/Xamarin.Forms.GoogleMaps#usage

**Comment by davidtavarez** [comment]
Same problem here.

**Comment by davidtavarez** [comment]
Oh! I just remove, clean and add again (1.7.1). This was before:

`Xamarin.FormsMaps.Init(this, savedInstanceState);`

But Xamarin Studio was still compiling. Now I changed it for:

`Xamarin.FormsGoogleMaps.Init(this, savedInstanceState);`

Working fine.

**Comment by amay077** [comment]
``Xamarin.FormsMaps.Init`` is **XAMARIN OFFICIAL** Map component's method.

``Xamarin.FormsGoogleMaps.Init`` is **MY PRODUCT** Map component(called Xamarin.Forms.GoogleMaps)'s method. 👍
