### ISSUE TITLE
[UWP]Show/Hide Zoom In/Out buttons property

### ISSUE THREAD

**Issue by davidtavarez** [amay077/Xamarin.Forms.GoogleMaps#180]
# FEATURE REQUEST

## SUMMARY

Capacity to show/hide controls

## DETAILS

UI controls should be manage like Google Maps does.

```
UiSettings.setZoomControlsEnabled(true)
```

[Controls and Gestures](https://developers.google.com/maps/documentation/android-api/controls#zoom_controls)
## PLATFORMS

- [x] Android
- [ ] iOS
- [x] UWP

**Comment by amay077** [comment]
Hi @davidtavarez ,

I can't found how to disable zoom control in UWP(Bing map).
Probably I will implement for Android and iOS only.

**Comment by deextercz** [comment]
According to this: https://social.msdn.microsoft.com/Forums/en-US/a647e305-a05e-4cf8-a33b-13e4388dbfba/remove-zoom-or-map-type-controls?forum=bingmapswindows8 
Set ShowNavigationBar to false.

**Comment by amay077** [comment]
Thanks @deextercz ,

Let me show my plan:

### New API

```
Map.UiSettings.ZoomControlsEnabled = true/false
```

### Implementations - wraps each native APIs

* Android - ``UiSettings.setZoomControlsEnabled(true / false)``
* iOS - No operation because Google Maps SDK for iOS does not have Zoom In/Out buttons
* UWP - ``ShowNavigationBar(true / false)``

**Comment by deextercz** [comment]
I searched again a little bit and for UWP it looks like solution is MapControl Template
http://stackoverflow.com/questions/38547023/mapcontrol-template10?rq=1
http://stackoverflow.com/questions/34329963/how-make-controls-on-map-like-in-windows-map-app

**Comment by amay077** [comment]
I released [Xamarin.Forms.GoogleMaps 2.1.0-beta2](https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/2.1.0-beta2) that contains #8.

You can use ``Map.UiSettings.ZoomControlsEnabled = false`` for hiding zoom controls in UWP.
