### ISSUE TITLE
Circle around userpin gigantic on iOS

### ISSUE THREAD

**Issue by LukasThijs** [amay077/Xamarin.Forms.GoogleMaps#182]
Hey,

Again great component and thanks for updating it this frequently! I have got a qeustion right now I have iOS code running and well but when I move to the user the circle (blue one) on iOS is gigantic. About 500+ radius around it. Is there any way I can reduce the size?

This is my move to user code:

  ```
     page.ShowMessage("Bezig met locatie ophalen");
                var locator = CrossGeolocator.Current;
                locator.DesiredAccuracy = 50;
                var location = await locator.GetPositionAsync(timeoutMilliseconds: 1000);
                _userPosition = new Position(location.Latitude, location.Longitude);
                map.MoveToRegion(MapSpan.FromCenterAndRadius(_userPosition, Distance.FromMeters(100)).WithZoom(1));
                

```

Thanks and cheers in advance!

Luuk

**Comment by deextercz** [comment]
I think it could be related to GPS signal, could you try it with better signal / emulator?

**Comment by amay077** [comment]
``Map.IsShowingUser`` is a Google Maps SDK for iOS's stuff.

* [myLocationEnabled | GMSMapView Class Reference](https://developers.google.com/maps/documentation/ios-sdk/reference/interface_g_m_s_map_view.html?hl=ja#a04faba924be73a0ea5bb9ae300da1c9a)

We could not control the blue circle.
