### ISSUE TITLE
Center the map on my position on appearing

### ISSUE THREAD

**Issue by matteopiccioni** [amay077/Xamarin.Forms.GoogleMaps#190]
Hello,
when the map is shown, I need to center the view on my position. 
There is a way to reproduce what happens when i hit the 'Showing user' button ?

I try to use CrossGeolocator, but it is really slow compared to 'Showing user' button

Thanks!

**Comment by amay077** [comment]
Hi @matteopiccioni ,

Location determining needs long time.
If you want to pan to your location when page showed, you should determine your location in previous page.

Let me show sample **IMAGE** codes:

```csharp
class FirstPage : Page {
    async void button1_Clicked() {
        var location = await CrossGeolocator.GetMyLocation();
        await this.Navigation.PushAsync(new SecondPage(location));
    }
}

class SecondPage : Page {
    SecondPage(Position initialLocation) {
        InitializeComponent();
        map.MoveToRegion(MapSpan.FromCenterAndRadius(initialLocation, Distance.FromMeters(5000)), false);
    }
}
```

**Comment by matteopiccioni** [comment]
Ok, I understand
Thanks
