### ISSUE TITLE
Supports CameraMoveStarted/CameraMoved and more events

### ISSUE THREAD

**Issue by amay077** [amay077/Xamarin.Forms.GoogleMaps#195]
# FEATURE REQUEST / SUGGESTION

## SUMMARY

Google Maps Android API has brand new events of camera and CameraChange is now deprecated.

This is continued from #60 

## DETAILS

[GoogleMap.setOnCameraChangeListener](https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap.html?setOnCameraChangeListener(com.google.android.gms.maps.GoogleMap.OnCameraChangeListener)) is deprecated.

I should consider to create events listed bellow:

* Map.CameraMoveStarted
* Map.CameraMoved
* Map.CameraMoveCancelled
* Map.CameraIdled

But I can't found ``CameraMoved`` and ``CameraMoveCancelled`` event in [Google Maps iOS SDK](https://developers.google.com/maps/documentation/ios-sdk/reference/protocol_g_m_s_map_view_delegate-p?hl=ja).

## PLATFORMS

- [x] Android
- [x] iOS
- [?] UWP 

I think UWP support is difficultly.

**Comment by amay077** [comment]
New events (e.g. CameraMoveStarted) can not use in Xamarin.Forms 2.3.x because:

* Xamarin.Forms 2.3.x depends Xamarin.Android.Support.v4 (= 23.3.0)
* But latest Xamarin Google Play Services 32.961.0 needs Xamarin.Android.Support.v4 (>= 24.2.1)

I'm waiting for Xamarin.Forms 2.4.

**Comment by ravero** [comment]
I think we could start with the Map.CameraIdled. The CameraChanged event generates tons of calls and I think that there are several scenarios where we need to identify when the user stops moving the map.

**Comment by deextercz** [comment]
In my project I have workaround

        private async void GoogleMapOnCameraChanged(object sender, CameraChangedEventArgs eventArgs)
        {
            var oldCameraPosition = eventArgs.Position;

            //Camera update
            GoogleMap.InitialCameraUpdate = CameraUpdateFactory.NewCameraPosition(eventArgs.Position);

            if (GoogleMap.VisibleRegion == null)
            {
                return;
            }

            if (oldCameraPosition == eventArgs.Position)
            {
                await RefreshVehiclesFromCache();
            }
        }

**Comment by eopeter** [comment]
Xamarin 2.4 is now stable. Can this work get some priority?
