### ISSUE TITLE
Ground overlay opacity inverser between Android and iOS

### ISSUE THREAD

**Issue by lindblomc** [amay077/Xamarin.Forms.GoogleMaps#197]
# FEATURE REQUEST / SUGGESTION
When adding a ground overlay to the map with an opacity the actual opacity/transparency value is inverse on iOS compared with Android.

Example 25% Opacity is 0.75 on iOS and 0.25 on Android.

Change Map component to handle this difference so that the API is always the same.

For my solution I have defined a constant that depends on platform
float GROUNDOVERLAY_TRANSPARENCY = (Device.OS == TargetPlatform.iOS) ? 0.75f : 0.25f;

**Comment by amay077** [comment]
Oh, thanks for reporting.
It is bug.

**Comment by amay077** [comment]
I released [1.8.0-beta5](https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/1.8.0-beta5) what contains it.
