### ISSUE TITLE
Remove ZoomControls on Android

### ISSUE THREAD

**Issue by lindblomc** [amay077/Xamarin.Forms.GoogleMaps#198]
# FEATURE REQUEST / SUGGESTION
Remove the ZoomControls on Android, they are basically never needed since Android startet to support multitouch and pinch zoom.

Alternatively add property for ZoomControls

Today the only way to hide them is to turn off zooming in map but the side effect is that the map cannot be zoomed.

**Comment by amay077** [comment]
Hi @lindblomc ,
Is this same as #180 ?

**Comment by lindblomc** [comment]
Hi,
Ah yes, it seems to be exactly the same issue.

Best regards
/Claes

**Comment by amay077** [comment]
Alright, If you have any comments, please join #180 .
I closed it.
