### ISSUE TITLE
Using custom tile

### ISSUE THREAD

**Issue by amay077** [amay077/Xamarin.Forms.GoogleMaps#2]
## iOS

* [TileLayer  |  Google Maps SDK for iOS  |  Google Developers](https://developers.google.com/maps/documentation/ios-sdk/tiles)

## Android

* [TileProvider  |  Google APIs for Android  |  Google Developers](https://developers.google.com/android/reference/com/google/android/gms/maps/model/TileProvider)

**Comment by kochizufan** [comment]
Is this started? If not, I try to do it for my study.. is there any idea of interface?

**Comment by amay077** [comment]
This is not started yet.

My plan is...

## API for users 

```
// Add
interface ITileLayer { // mapped for adroid:TileProvider, ios:GMSTileLayer
}

// Add
interface IUrlTileLayer : ITileLayer { // mapped for adroid:UrlTileProvider, GMSURLTileLayer
    Url GetTileUrl(int x, int y, int zoom);
}
```

```
class Map {
   public IList<ITileLayer> TileLayers { get { return _tileLayers } } // Add
}
```

user usage:

```
class MyUrlTileLayer : IUrlTileLayer {
    public Url GetTileUrl(int x, int y, int zoom) {
        return /* your custom tile url (ex: openstreetmap) */
    }
}
```

```
map.TileLayers.Add(new MyUrlTileLayer());
```

## Implementations

```
class Map {
    readonly ObservableCollection<ITileLayer> _tileLayers = new ObservableCollection<ITileLayer>();
}
```

Handle ``_tileLayers.CollectionChanged`` in native side.
This approach is same as Pins, Polygons, Circles.

## REFERENCE

* [TileLayer  |  Google Maps SDK for iOS  |  Google Developers](https://developers.google.com/maps/documentation/ios-sdk/tiles)
* [TileOverlay  |  Google Maps Android API  |  Google Developers](https://developers.google.com/maps/documentation/android-api/tileoverlay?hl=ja)

**Comment by kochizufan** [comment]
According to my memory, 

* android:TileProvider
* android:UrlTileProvider
* ios:GMSURLTileLayer

's interfaces are sync, but

ios:GMSTileLayer

's interface is async..

So, my opinion, how about unify them as

* android:UrlTileProvider, ios:GMSURLTileLayer => Sync Interface
* android:TileProvider, ios:GMSTileLayer => Async interface

How do you feel?

**Comment by amay077** [comment]
> * android:UrlTileProvider, ios:GMSURLTileLayer => Sync Interface
> * android:TileProvider, ios:GMSTileLayer => Async interface

I think android:TileProvider is Sync interface.
Because this has ``Tile getTile(int x, int y, int zoom)`` method.
This means ``getTile`` should return ``Tile`` synchronously.

For the time being, we need android:UrlTileProvider and ios:GMSURLTileLayer.
Would you defer a design of sync and async tile interfaces?
(Actually, I don't know use cases of async interface.)

How about this?
```
// Now
interface ITileLayer { }  // common base tile interface(not defined sync or async).
interface IUrlTileLayer : ITileLayer { }  // useful for any tile map sources. only for url customizing.


// Future
interface ISyncTileLayer : ITileLayer {} // define some members for get tile synchronously.
interface IAsyncTileLayer : ITileLayer {} // define some members for get tile asynchronously. 
```

**Comment by kochizufan** [comment]
すんません、海外の人も入って来やすいよう？英語で書いてましたが、この件英語下手すぎてうまく伝わってない感じなので日本語で書きます。

元SDKのインタフェースは、URL返す場合はiOS/Androidとも同期で、画像を返す場合はAndroidは同期、iOSは非同期（というかcallback）インタフェースになってます。
なのでこれを、Xamarin.Forms版ではURL返す場合は同期で、画像を返す場合はcallbackインタフェースに統一してはどうか、というのが趣旨でした。

とりあえずはURL版だけ準備するのが早いかもしれませんが...

**Comment by amay077** [comment]
いえ、こちらこそ、英語むずいですね（汗

> 画像を返す場合はAndroidは同期、iOSは非同期（というかcallback）インタフェースになってます。

なるほど納得です。
Android 版には非同期インターフェースが存在しないんですよね（画像を返す前の加工に時間がかかったらどうなるんだという）。

> 画像を返す場合はcallbackインタフェースに統一してはどうか、というのが趣旨でした。

そうですね。その場合 C# なので Task<Image> を返す形がふさわしいと思います。

```
interface IImageTileLayer : ITileLayer {
    Task<Image> GetTile(/* some parameters */);
} 
```

これなら sync 用と async 用の２つのインターフェースを作らなくてもよいかもしれませんね。

ただ、まずは URL版だけでいいかなと思っています。

**Comment by amay077** [comment]
ちょっと謎なのが、Andoid の ``Tile getTile`` が、内部実装として

**Comment by amay077** [comment]
あ、間違えて Close してしまった

**Comment by amay077** [comment]
ちょっと謎なのが、Andoid の Tile getTile が、内部実装として、別のスレッドから呼び出されているのかどうかです。

iOS の方は Sync 版が明確に用意されているので意図が分かりますが、Android の方はないので、どのようにマップさせるか、（Googleの人に聞かないと）正解が分からない気がします。

**Comment by kochizufan** [comment]
UrlはSystem.Uriでいいですか？

**Comment by amay077** [comment]
Yes!

**Comment by kochizufan** [comment]
ちょっとはじめてみましたが、ITileLayerはいいとして、UrlTileLayerはクラスにして、コンストラクタでTile生成ロジック食わせる方がいいかなと感じました。
というのは、TileLayerとUrlTileLayerはインタフェースが全然異なりますが、ネイティブ実装は内部実装があるのでその違いを内部実装で吸収してますけども、Xamarin.Forms向けのクラスだと内部実装が書けないので、TileLayer向けのインタフェースを定義したITileLayerと、UrlTileLayer向けのインタフェースを定義してITileLayerを継承したIUrlTileLayerだと、UrlTileLayerでは必要ないTileLayer向けのメソッドのダミーをユーザが書かないといけないことになるので...
UrlTileLayerをクラスにすると、ダミーメソッドをこちらで書けるので、ユーザを混乱させないかなと...

**Comment by amay077** [comment]
↓こんな感じですよね。良いと思います。

```
// define
public class UrlTileLayer : ITileLayer {
    public UrlTileLayer(Func<int, int, int, Uri> makeTileUri) { }
}

--

// usage
map.TileLayers.Add(new UrlTileLayer((int, int, int) => 
{
    return /* your custom tile url (ex: openstreetmap) as System.Uri */
}));
````

**Comment by kochizufan** [comment]
あめいさん
#19でTileサンプル含めできました...と言いつつ、Androidでは順調に動いてるんですが、iOSで何故か、サンプルのトップページ（タイル関係ない、各ページへのリンクページ）でボタンが反応しなくなってしまいました。タイルページだけでなく全ページへのリンクが効きません。コンソールにエラーも出てません。Xamarin.Forms経験が少ないので、こうなるとお手上げで...プルリク送っておいて何ですが、ちょっと何が悪いのか教えてもらえないでしょうか...

**Comment by kochizufan** [comment]
とりあえずURL版だけ作りましたが、
* 画像返す版
* タイルサイズのサポート
* clearCacheのサポート
* zIndexのサポート
* opacityのサポート
* fadeInのサポート
あたり必要かなと思うのですが、このチケットで続けた方がいいでしょうか、項目ごと別チケット切りましょうか。

あと、Propertyのネイティブ側への伝搬はサンプルたくさんある感じがするのですが、clearCacheのようなメソッドの伝搬ってプロジェクト内にサンプルありましたでしょうか。

**Comment by amay077** [comment]
> このチケットで続けた方がいいでしょうか
とりあえず、このチケットでは、最小限の（現状の）機能実装でよいと思います。

> あと、Propertyのネイティブ側への伝搬はサンプルたくさんある感じがするのですが、clearCacheのようなメソッドの伝搬ってプロジェクト内にサンプルありましたでしょうか。

``Map.MoveToRegion`` では、 MessagingCenter を使っていますが、これは冗長な気がしますね。
``UrlTileLayer.ClearCache()`` のケースだと、

1. ``ITileLayer`` に ``OnClearCache`` のようなイベントを用意
2. ``ITileLayer.ClearCache()`` 呼び出しで ``OnClearCache`` を発火
3.  ネイティブ側の ``MapRenderer`` の ``TileLayers.Add`` 時に ``ITileLayer`` に ``OnClearCache`` を購読してネイティブ側の ``clearCache`` を呼ぶ。（ ``TileLayers.Remove`` 時に購読解除）

って感じですかね。
ただこれは #9 を対応するとそれが参考になるので、その後でもいいです。

**Comment by amay077** [comment]
PR をマージしました。
v1.3.0-beta1 で公開予定です。
ありがとうございました。

**Comment by amay077** [comment]
Include in v1.3.0
