### ISSUE TITLE
GroundOverlay Out of memory on Android

### ISSUE THREAD

**Issue by lindblomc** [amay077/Xamarin.Forms.GoogleMaps#201]
## SUMMARY
My application can switch GroundOverlays and when clicking on a button the application loads image from webserver 2000x2000 pixels at the moment. On Galaxy S5 I constantly get Out of memory error on the third image. 

I have seen this problem before in native Android development but problem disapeared when using Universal Image Loader.

### Xamarin.Forms.GoogleMaps

* 1.8.0-beta3

### Xamarin.Forms

* 2.3.3.180

## PLATFORMS

- [x] Android (Android 5.0)
- [ ] iOS
- [ ] UWP

## STEPS FOR REPRODUCE
Load image from webserver and creating BitmapDescriptor by
`BitmapDescriptorFactory.FromStream(new System.IO.MemoryStream(bytes));`

```
var overlay = new GroundOverlay()
{
    Bounds = new Bounds(new Xamarin.Forms.GoogleMaps.Position(mapOverlay.Bounds.SouthWest.Latitude, mapOverlay.Bounds.SouthWest.Longitude),
                        new Xamarin.Forms.GoogleMaps.Position(mapOverlay.Bounds.NorthEast.Latitude, mapOverlay.Bounds.NorthEast.Longitude)),
    Icon = overlayImage,
    IsClickable = false,
    Transparency = GROUNDOVERLAY_TRANSPARENCY
};

forecastMap.GroundOverlays.Add(overlay);
```

Problem occurs on device and not in Android emulator but that most likely depends on Android 6.0 and different RAM size.

> [AndroidRuntime] Shutting down VM
> [AndroidRuntime] FATAL EXCEPTION: main
> [AndroidRuntime] Process: se.msb.brandrisk, PID: 2017
> [AndroidRuntime] java.lang.OutOfMemoryError: Failed to allocate a 16000012 byte allocation with 5035028 free bytes and 4MB until OOM
> [AndroidRuntime] 	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
> [AndroidRuntime] 	at android.graphics.Bitmap.nativeCreateFromParcel(Native Method)
> [AndroidRuntime] 	at android.graphics.Bitmap.access$000(Bitmap.java:37)
> [AndroidRuntime] 	at android.graphics.Bitmap$1.createFromParcel(Bitmap.java:1645)
> [AndroidRuntime] 	at android.graphics.Bitmap$1.createFromParcel(Bitmap.java:1637)
> [AndroidRuntime] 	at adm.onTransact(:com.google.android.gms.DynamiteModulesB:101)
> [AndroidRuntime] 	at android.os.Binder.transact(Binder.java:380)
> [AndroidRuntime] 	at tzd.a(:com.google.android.gms:242)
> [AndroidRuntime] 	at trl.a(:com.google.android.gms:1252)
> [AndroidRuntime] 	at trn.a(:com.google.android.gms:184)
> [AndroidRuntime] 	at trf.a(:com.google.android.gms:6164)
> [AndroidRuntime] 	at tzc.onTransact(:com.google.android.gms:106)
> [AndroidRuntime] 	at android.os.Binder.transact(Binder.java:380)
> [AndroidRuntime] 	at com.google.android.gms.maps.model.internal.zza$zza$zza.zzc(Unknown Source)
> [AndroidRuntime] 	at com.google.android.gms.maps.model.BitmapDescriptorFactory.fromBitmap(Unknown Source)
> [AndroidRuntime] 	at mono.java.lang.RunnableImplementor.n_run(Native Method)
> [AndroidRuntime] 	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
> [AndroidRuntime] 	at android.os.Handler.handleCallback(Handler.java:739)
> [AndroidRuntime] 	at android.os.Handler.dispatchMessage(Handler.java:95)
> [AndroidRuntime] 	at android.os.Looper.loop(Looper.java:145)
> [AndroidRuntime] 	at android.app.ActivityThread.main(ActivityThread.java:5832)
> [AndroidRuntime] 	at java.lang.reflect.Method.invoke(Native Method)
> [AndroidRuntime] 	at java.lang.reflect.Method.invoke(Method.java:372)
> [AndroidRuntime] 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
> [AndroidRuntime] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
> (write summary of your bug report.)
> 
# OTHERS

(free format)

**Comment by amay077** [comment]
We have not received the requested information. 
If you are still experiencing this issue please provide all the requested information and re-open the issue report. 
Thanks!
