### ISSUE TITLE
Send camera update on VisibleRegion changed

### ISSUE THREAD

**Issue by deextercz** [amay077/Xamarin.Forms.GoogleMaps#211]
# BUG / PROBREM REPORT

When Visible region is changed camera position is not reflected

## SUMMARY

When I move on map somewhere VisibleRegion is changed, but camera position is not reflected.
It should be reflected.
This issue relates to #101

### Xamarin.Forms.GoogleMaps

1.8.0-beta5

### Xamarin.Forms

2.3.3.180

## PLATFORMS

- [x] Android
- [ ] iOS
- [ ] UWP

## STEPS FOR REPRODUCE

1. Create app with map as tabbed page (at least 3 tabs)
2. Switch from tab 1 to 3 and back to 1
3. Camera is reseted to initial location

**Comment by amay077** [comment]
> Create app with map as tabbed page (at least 3 tabs)

What kind of implementation did you use for Tabbed Page?

* [XAML with a Page Collection](https://developer.xamarin.com/guides/xamarin-forms/user-interface/navigation/tabbed-page/#Populating_a_TabbedPage_with_a_Page_Collection)
* [C# code]()
* [XAML with a Template](https://developer.xamarin.com/guides/xamarin-forms/user-interface/navigation/tabbed-page/#Populating_a_TabbedPage_with_a_Template)

Could you show me sample app for reproduce based on [XFGoogleMapSample](https://github.com/amay077/Xamarin.Forms.GoogleMaps/tree/master/XFGoogleMapSample)?

**Comment by amay077** [comment]
> Could you show me sample app for reproduce based on XFGoogleMapSample?

OK, I made sample for reproduce in [issue_211 branch](https://github.com/amay077/Xamarin.Forms.GoogleMaps/tree/issue_211/XFGoogleMapSample/XFGoogleMapSample).

![untitled_1](https://cloud.githubusercontent.com/assets/401369/22626985/5d27be3c-ebfc-11e6-85e4-a3a85a7d1fda.gif)

And I added [my suggested solution](https://github.com/amay077/Xamarin.Forms.GoogleMaps/issues/101#issuecomment-277462013), then works fine.

![untitled](https://cloud.githubusercontent.com/assets/401369/22626986/640098dc-ebfc-11e6-9530-f0137332dde7.gif)

**Comment by deextercz** [comment]
Hello @amay077 your solution is now working for me.
I have own map derived from Map where I am extending some methods like IsInVisibleRegion and etc and there I implemented you solution. It is wrong implementation so I moved to instance of my custom map and it is working.
But my last question before closing these issues is why not implement this solution to VisibleRegion?

**Comment by amay077** [comment]
```csharp
public MapSpan VisibleRegion
{
    get { return _visibleRegion; }
    internal set
    {
        if (_visibleRegion == value)
            return;
        if (value == null)
            throw new ArgumentNullException(nameof(value));
        OnPropertyChanging();
        _visibleRegion = value;
        OnPropertyChanged();
+        InitialCameraUpdate = CameraUpdateFactory.NewBounds(value.ToBounds(), 0);
    }
}
```

I don't hope update ``InitialCameraUpdate`` when VisibleRegion changed(also CameraChanged).
Because somebody might need to hold on initial camera position.
(e.g. Somebody might want to update ``InitialCameraUpdate`` when user pin clicked.)

I don't hope restrict usage of ``InitialCameraUpdate``.

**Comment by deextercz** [comment]
Thank you, closing as won't fix
