### ISSUE TITLE
Decouple 'IsShowingUser' from displaying the Location Button

### ISSUE THREAD

**Issue by woellij** [amay077/Xamarin.Forms.GoogleMaps#219]
### SUMMARY

I'd vote for decoupling showing the 'LocationButton' from the 'IsShowingUser' property and instead introduce another Property for that. (e.g. 'IsShowingUserPositionButton')

### DETAILS
    
In iOS Renderer:

void UpdateIsShowingUser()
        {
            ((MapView)Control).MyLocationEnabled = ((Map)Element).IsShowingUser;
            ((MapView)Control).Settings.MyLocationButton = ((Map)Element).IsShowingUser;
        }

In my use case I very much want to show the user's location on the map - but NOT the button (i have my own Button for that properly handling requesting permission at the right time etc.)

### PLATFORMS

which platform do you want?

- [x] Android
- [x] iOS
- [ ] UWP

**Comment by amay077** [comment]
Hi @woellij ,
Thanks for your requesting.

I have a plan to #8 which has separated each settings.

Your suggestion ``IsShowingUserPositionButton `` is same as ``UiSetting.isMyLocationButtonEnabled``.
But I should make ``Map.MyLocationEnabled`` which can only enable/disable the "blue marker" shown.

**Comment by EmmanVazz** [comment]
+1

**Comment by amay077** [comment]
I released [Xamarin.Forms.GoogleMaps 2.1.0-beta2](https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/2.1.0-beta2) that contains #8 .

You can use separated twice properties.

* ``map.UiSettings.MyLocationButtonEnabled`` - location button
* ``map.MyLocationEnabled`` - tracking location

**Comment by ViktorBylbas** [comment]
Don`t working.
map.MyLocationEnabled = true - the "blue marker" disable
