### ISSUE TITLE
Add a pin on user current location

### ISSUE THREAD

**Issue by babnitch** [amay077/Xamarin.Forms.GoogleMaps#220]
### SUMMARY

Could you please help me with  an  example  on how  to  get the  current location of  the user when the map loads and add  my in on  that  location?
I'm not able to make it work in your sample , MyLocationButtonClicked 
I'm coding on a mac, and  i'm interested in a solution for IOS

### PLATFORMS

- [ ] Android
- [x] iOS
- [ ] UWP

**Comment by amay077** [comment]
Xamarin.Forms.GoogleMaps does not provides getting location manually. 

You can use GeolocatorPlugin which provides getting GPS location in each platforms.

* [jamesmontemagno/GeolocatorPlugin: Geolocation plugin for Xamarin and Windows](https://github.com/jamesmontemagno/GeolocatorPlugin)

**Comment by deextercz** [comment]
@babnitch IsShowingUser is not good enough for you?

**Comment by amay077** [comment]
Closed because no longer response.
