### ISSUE TITLE
reflect Pin IsVisible to show/hide pin

### ISSUE THREAD

**Issue by deextercz** [amay077/Xamarin.Forms.GoogleMaps#231]
Pin has 
`
public static readonly BindableProperty IsVisibleProperty;
`
but even if I set value to false pin is still rendered

----
## FEATURE REQUEST / SUGGESTION

Pin should be rendered only based on this value.

### DETAILS

For example I have many groups of Pins and I want to display just part of them

### PLATFORMS

which platform do you want?

- [x] Android
- [x] iOS
- [x] UWP

**Comment by amay077** [comment]
I can't reproduce.
``Pin.IsVisible`` is works fine in Android / iOS.

![untitled2](https://cloud.githubusercontent.com/assets/401369/22864265/7dd613d2-f191-11e6-8a8c-8d653600d0e2.gif)

Do I understand your reporting correctly?

**Comment by deextercz** [comment]
Yes, you are correct it looks like that is working only if pins are added and after that modified
If you use this code:
```
var pin = new Pin()
{
Position = new Position(vehicle.Lat, vehicle.Lon),
IsVisible = false
};
GoogleMap.Pins.Add(pin);
```

It does not work

**Comment by amay077** [comment]
I understand!
It's a bug.
``Pin.IsVisible`` does not used when native marker created.
Thanks you for reporting.

**Comment by amay077** [comment]
Ok, I fixed it.
Please waiting for release.

**Comment by amay077** [comment]
I did it.
I released [1.8.0-beta6](https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/1.8.0-beta6) which contains fix for this!

**Comment by deextercz** [comment]
I checked it and it works thank you

**Comment by emrahy** [comment]
`Pin pi = new Pin();
pi.Position = new Position(39.386407, 32.445372);
pi.Label = "TEST";
pi.IsVisible = false;
pi.Icon = BitmapDescriptorFactory.FromView(new HaritaPinView("58"));
map.Pins.Add(pi);`

It does not work. 
Problem: "pi.Icon = BitmapDescriptorFactory.FromView(new HaritaPinView("58"));"
How can we solve this problem?

**Comment by ericc0504** [comment]
> `Pin pi = new Pin(); pi.Position = new Position(39.386407, 32.445372); pi.Label = "TEST"; pi.IsVisible = false; pi.Icon = BitmapDescriptorFactory.FromView(new HaritaPinView("58")); map.Pins.Add(pi);`
> 
> It does not work.
> Problem: "pi.Icon = BitmapDescriptorFactory.FromView(new HaritaPinView("58"));"
> How can we solve this problem?

I am now having exactly the same issue. Is there any update?
