### ISSUE TITLE
Move Pin InfoWindow position to another location

### ISSUE THREAD

**Issue by deextercz** [amay077/Xamarin.Forms.GoogleMaps#234]
I want to be able move info window around the pin icon.
----
## FEATURE REQUEST / SUGGESTION
Please implement something like margin or etc if it is possible.
If pin is heading down (rotation is set to 180 I think) info window overflows the pin.

### DETAILS

![2017-02-15 13_01_22-xde](https://cloud.githubusercontent.com/assets/23039506/22973839/ac3c8e14-f37f-11e6-99ec-39e6f9ee9974.png)

```
// usage of your requested feature to use
```

### PLATFORMS

which platform do you want?

- [x] Android
- [x] iOS
- [ ] UWP

**Comment by amay077** [comment]
I found ``InfoWindowAnchor`` property in Google Maps API.

* [Android] - [Marker  |  Google APIs for Android  |  Google Developers](http://bit.ly/2kKe2F1)
* [iOS] - [GMSMarker Class Reference  |  Google Maps SDK for iOS  |  Google Developers](https://developers.google.com/maps/documentation/ios-sdk/reference/interface_g_m_s_marker.html?hl=ja#a6668957ca7b6857355ee6cd9ab944a92)

Probably we can offset to infoWindow's anchor by this property.

**Comment by amay077** [comment]
Thanks @deextercz ,
I added cosmetic improvements for sample ( https://github.com/amay077/Xamarin.Forms.GoogleMaps/commit/dd0709c1789d042288741602b3e138088623b9a4 , https://github.com/amay077/Xamarin.Forms.GoogleMaps/commit/3bca539e458c86cea300e0507bddfca86fd31d38 ) .

![screenshot_1491494843](https://cloud.githubusercontent.com/assets/401369/24764238/ab35a2ae-1b2e-11e7-83ab-cd6d07cb9e45.png)

**Comment by amay077** [comment]
I released [v1.8.0](https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/1.8.0) that contained it.
