### ISSUE TITLE
Extend BitmapDescriptorFactory support with fromPath

### ISSUE THREAD

**Issue by deextercz** [amay077/Xamarin.Forms.GoogleMaps#235]
When my app is generating images on the fly it stores to some location.
----
## FEATURE REQUEST / SUGGESTION

Extend support to load image from path on both platforms

### DETAILS

I was trying to use FromStream, but it does not work for me.

On Android I have Dependency injection where I create custom image, after that I convert it to memory stream it throws Java.Lang.NullPointerException: bitmap
I checked if content is returned correctly and it is.

        public Stream DrawTextToBitmap(string text)
        {
            //var sdCardPath = Application.Context.FilesDir.Path;
            //var filePath = System.IO.Path.Combine(sdCardPath, $"marker_{text}.png");

            Resources resources = Application.Context.Resources;
            float scale = resources.DisplayMetrics.Density;
            Bitmap bitmap = BitmapFactory.DecodeResource(resources, Resource.Drawable.marker);
            bitmap = bitmap.Copy(Bitmap.Config.Argb8888, true);

            Canvas canvas = new Canvas(bitmap);

            float x = (float) bitmap.Height / 2;
            float y = (float) bitmap.Width / 2;
            Paint paint = new Paint();

            paint.Color = Color.Green;
            paint.TextSize = 12 * scale;
            canvas.DrawText(text, 10, 25, paint);

            var stream = new MemoryStream();
            bitmap.Compress(Bitmap.CompressFormat.Png, 100, stream);
            return stream;
        }

### PLATFORMS

which platform do you want?

- [x] Android
- [x] iOS
- [?] UWP

**Comment by amay077** [comment]
We can use [PCL Storage](https://github.com/dsplaisted/PCLStorage) which provides cross-platform file access via Path(Also can get ``Stream`` from Path).

I think it's enough for this use case.

**Comment by deextercz** [comment]
After some investigation Exception is occuring in PinLogic.cs

if (outerItem.Icon != null)
{
    opts.SetIcon(outerItem.Icon.ToBitmapDescriptor());
}

**var marker = NativeMap.AddMarker(opts);**

**Comment by adamhill** [comment]
Our app also get this error. We are getting our file from the PCL resources. On Android we randomly get the Java NullPointerException: bitmap, in iOS we haven't seen it.

**Comment by amay077** [comment]
I made sample for ``BitmapFactory.FromStream`` with local file using PCLStorage.
I can shown the "Xamagon" in Android and iOS.

![screenshot_1487590148](https://cloud.githubusercontent.com/assets/401369/23123470/cde3af5e-f7ab-11e6-8877-153969aa8650.png)

This sample is in [issue_240 branch](https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/issue_240/XFGoogleMapSample/XFGoogleMapSample/CustomPinsPage.xaml.cs#L152).

```cs
// Read png from device local file
var folder = FileSystem.Current.LocalStorage;
var pngFile = await folder.GetFileAsync($"xamagon.png");
var pngStream = await pngFile.OpenAsync(FileAccess.Read);
_pinTokyo.Icon = BitmapDescriptorFactory.FromStream(pngStream);
```

**Comment by deextercz** [comment]
Regarding fromStream in android I found solution https://forums.xamarin.com/discussion/21843/strange-imagesource-behavior-on-android-skimagedecoder-factory-returned-null
Trick is in `Position = 0;  `
