### ISSUE TITLE
Content of Pin is not reflected in UI immediately on PinClicked Event

### ISSUE THREAD

**Issue by deextercz** [amay077/Xamarin.Forms.GoogleMaps#240]
When you click on pin and you want to change content of pin it is not reflected immediately.
If you click again on pin there is new content loaded.

----
### SUMMARY

UI should be rendered after event is handled

### DETAILS

    ...
          GoogleMap.PinClicked += GoogleMapOnPinClicked;
    ...

        private async void GoogleMapOnPinClicked(object sender, PinClickedEventArgs pinClickedEventArgs)
        {
            pinClickedEventArgs.Pin.Address = "New name";
        }

After this code content of Address is still with old content
If you click again on pin content of pin is set to "New name"

![pin clicked event](https://cloud.githubusercontent.com/assets/23039506/23063780/a0ab491c-f50c-11e6-9011-279cba687883.gif)

### PLATFORMS

which platform do you want?

- [x] Android
- [x] iOS
- [?] UWP

**Comment by amay077** [comment]
I can not reproduce it.
Works fine on Android and iOS like below capture and code.

![untitled2](https://cloud.githubusercontent.com/assets/401369/23124249/607fde70-f7af-11e6-84b2-270d3dab7098.gif)

```c#
int counter = 0;
map.PinClicked += (_, e) => 
{
    counter++;
    e.Pin.Address = counter.ToString();
    e.Handled = false;
};
```

Could you reproduce on XFGoogleMapSample?

**Comment by deextercz** [comment]
@amay077 thank you for help.
It was caused because my event was async and I was using there await.
