### ISSUE TITLE
Disable click in map view

### ISSUE THREAD

**Issue by EmmanVazz** [amay077/Xamarin.Forms.GoogleMaps#248]
We want to disable clicking in the map view. We are using the view as a background for something and don't want the click even to do anything. On Xamarin Forms setting the IsEnabled flag to false works on iOS but not on droid. 

VERSIONS
* Xamarin.Forms.GoogleMaps - 1.7.1
* Xamarin.Forms - 2.3.4192-pre2

PLATFORMS
- [x] Android
- [ ] iOS
- [ ] UWP

HOW TO REPRODUCE
1. Create a map view with a pin
2. Set IsEnabled to false
3. Try clicking on pin

**Comment by amay077** [comment]
Ahh, this is Google Maps API's design.
I think view.setEnable is independent with maps any gesture and pin clicking.

You can disable Pin clicking below code.

```
map.PinClicked += (sender, e) => 
{
    e.Handled = !map.IsEnabled;
};
```

**Comment by EmmanVazz** [comment]
That work as expected, thanks!
