### ISSUE TITLE
Can a FromBundle BitmapDescriptor be anchored in the vertical centre?

### ISSUE THREAD

**Issue by urnfield0** [amay077/Xamarin.Forms.GoogleMaps#249]
### SUMMARY

Can a FromBundle BitmapDescriptor be anchored in the vertical centre, instead of at the bottom?

### DETAILS

Sorry, this is a question, not a feature request or bug, but I didn't know where else to ask it. Is there somewhere better?

I'm using circular images for Pin icons, using a FromBundle BitmapDescriptor. I'd like the vertical centre of the circlular image to be over the Pin's position, but the image is rendered with the bottom of the image over the Pin position. Is there any way to change the anchor point? I haven't been able to find a way.

I know it can be done using a FromView BitmapDescriptor, but I experience degraded performance and random crashes on Android with this BitmapDescriptor type.

Many thanks.

### PLATFORMS

which platform do you want?

- [x] Android
- [x] iOS
- [ ] UWP

**Comment by amay077** [comment]
Hi @urnfield0 ,

Would you like ``Pin.Anchor`` property?
You can try it in [XFGoogleMapSample/PinsPage.xaml](https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/master/XFGoogleMapSample/XFGoogleMapSample/PinsPage.xaml.cs#L126).

**Comment by urnfield0** [comment]
Thank you, that's exactly what I want. And Pin.IsVisible will be really useful too.

And I'll be sure to look at the current source before bothering you in future.

Looking forward to release 1.8 of your excellent and ever-improving library!
