### ISSUE TITLE
Do not invoke SendCameraChanged if VisibleRegion is null

### ISSUE THREAD

**Issue by deextercz** [amay077/Xamarin.Forms.GoogleMaps#251]
## BUG / PROBREM REPORT
When I am initializing map on UWP there is fired event camera changed even if Visible region is null

### SUMMARY
Expected behaviour is do not send if visible region is null.
I am able handle this in my code, but I beleive that it should be handled in this project

### VERSIONS

* Xamarin.Forms.GoogleMaps - 1.8.0-beta6
* Xamarin.Forms - 2.3.3.193

### PLATFORMS

- [ ] Android
- [ ] iOS
- [x] UWP

**Comment by deextercz** [comment]
This is probably my misstake, I am adding pins even if Visible region is still null, but could we do something with faster loading VisibleRegion?

**Comment by amay077** [comment]
We have not received the requested information. 
If you are still experiencing this issue please provide all the requested information and re-open the issue report. 
Thanks!
