### ISSUE TITLE
Community chat

### ISSUE THREAD

**Issue by deextercz** [amay077/Xamarin.Forms.GoogleMaps#252]
Hello,
sometimes I miss there feature to ask you @amay077 or somebody else directly for something or I dont want create issue.
I suggest to create community chat for example slack, it is free and simple to use.
What do you think about this?

**Comment by stefancvetkovic** [comment]
I'm in. Please feel free to contact me here. My nick on slack is cvelle89.

Best regards,

**Comment by deextercz** [comment]
I thought we could create a team so I created xf-googlemaps.slack.com, if you are interested you can join, just let me your email address and I will invite you.

**Comment by dw2kim** [comment]
I'm down, too. My nick on slack is:
dw2kim

**Comment by stefancvetkovic** [comment]
Great! My nick is cvelle89
please add me to the group. See you there.

**Comment by deextercz** [comment]
Actually i need email address i am not able to invite by nick name

**Comment by stefancvetkovic** [comment]
stefan.cv5@gmail.com 💃

**Comment by dw2kim** [comment]
dw2kim@gmail.com

**Comment by amay077** [comment]
Hi @deextercz ,
Thank you create slack channel.
May I make it as "official community chat"?

**Comment by deextercz** [comment]
Yes I think you can

**Comment by amay077** [comment]
Thanks @deextercz ,
I will try deploy your suggested automatic invitation site to my azure account.

**Comment by amay077** [comment]
I created gitter room as official community for Xamarin.Forms.GoogleMaps.

https://gitter.im/Xamarin-Forms-GoogleMaps/public

Anyone can join, please welcome.

(@deextercz , Thanks to the action of until now.)
