### ISSUE TITLE
UWP rotate pin image

### ISSUE THREAD

**Issue by deextercz** [amay077/Xamarin.Forms.GoogleMaps#253]
## FEATURE REQUEST / SUGGESTION
Bing maps does not support pin rotation so the only way how to rotate pin is rotate image.
Could we make feature to rotate pin?

### SUMMARY

I want to create feature that will reflect pin rotation as on android and iOS.

### PLATFORMS

which platform do you want?

- [ ] Android
- [ ] iOS
- [x] UWP

**Comment by amay077** [comment]
I think it is difficult. Bing maps SDK is very cheep.
