### ISSUE TITLE
Custom iOS Map Renderer -> null nativeMap

### ISSUE THREAD

**Issue by belandsoft** [amay077/Xamarin.Forms.GoogleMaps#254]
### SUMMARY

I'm using custom map renderer following the xamarin repo sample:
https://github.com/xamarin/xamarin-forms-samples/blob/master/CustomRenderers/Map/Pin/iOS/CustomMapRenderer.cs#L37

but i'm facing a problem where on iOS/CustomMapRenderer.cs i have always 

`var nativeMap = Control as MKMapView;`

 returning null on row 37, so my app crashes on following rows.

### VERSIONS

Current:
* Xamarin.Forms.GoogleMaps - 1.8.0-beta6
* Xamarin.Forms - 2.3.4.192-pre2

but tested on earlier version (stable one) too and it's the same.

### PLATFORMS

- [ ] Android
- [x] iOS
- [ ] UWP

### MORE INFO
I want to learn more about:

`var nativeMap = Control as MKMapView;`

is this instruction dependent on Xamarin.Forms.GoogleMaps or not?

**Comment by belandsoft** [comment]
It was my mistake, not a bug

**Comment by Yogeshk25** [comment]
When I write my own renderer by deriving from existing custom renderer in iOS project. Execution control never goes in to that renderer. I am using latest version of nuget package.

**Comment by Abhiprao** [comment]
Hi @andreabellitto ,
                                 Can you please tell me that how did you solve that null reference  exception which is caused by nativeMap, Because I'am getting the same exception.
