### ISSUE TITLE
Pin rotation is always heading to compas rotation not map rotation

### ISSUE THREAD

**Issue by deextercz** [amay077/Xamarin.Forms.GoogleMaps#255]
### SUMMARY

Expected behaviour is that pin is rotated to map azimuth not phone azimuth.
Pins should have fixed rotation even if I will rotate the map.
I hope that you know how I thougt that.

If this is feature could you help me how to do that to fix pin position/rotation?
### VERSIONS

* Xamarin.Forms.GoogleMaps - 1.8.0-beta6
* Xamarin.Forms - 2.3.3.193

### PLATFORMS

- [x] Android
- [x] iOS
- [ ] UWP

### HOW TO REPRODUCE

(Let me show how to reproduce with steps or codes)

1. Use gesture to rotate map

### ACTUAL IMAGES
![rotation](https://cloud.githubusercontent.com/assets/23039506/23586952/6899df74-01a1-11e7-96fa-8b836bf7bff2.gif)
----

**Comment by deextercz** [comment]
This is expected behaviour
![rotation2](https://cloud.githubusercontent.com/assets/23039506/23587106/1abbf842-01a5-11e7-953d-fc61c79e81b2.gif)

Pins are not changing rotation even if you rotate map

**Comment by amay077** [comment]
Probably you need the [Marker.setFlat(true)](http://bit.ly/2msMnfS) property.
I add to plan as new feature it. 👍

**Comment by deextercz** [comment]
Thank you I think I will be able to add this property, maybe today.
Will you release a new version soon?
