### ISSUE TITLE
NativeItem is null when deleting PushPin

### ISSUE THREAD

**Issue by deextercz** [amay077/Xamarin.Forms.GoogleMaps#259]
### SUMMARY

Application crashes when

### VERSIONS

* Xamarin.Forms.GoogleMaps - 1.8.0-beta6
* Xamarin.Forms - 2.3.3.193
* 

### PLATFORMS

- [ ] Android
- [ ] iOS
- [x] UWP

![bug](https://cloud.githubusercontent.com/assets/23039506/23623291/ccee2b28-02a1-11e7-83a2-fc0c6752defb.png)

**Comment by JKennedy24** [comment]
Has this issue been resolved at some point?

The source code for UWP now reads:

```
        protected override PushPin DeleteNativeItem(Pin outerItem)
        {
            var nativePushpin = outerItem.NativeObject as PushPin;

            if (nativePushpin == null)
            {
                return null;
            }
```

I'm not sure when that was added

I think the linked android issue is a different issue

**Comment by amay077** [comment]
We have not received the requested information. 
If you are still experiencing this issue please provide all the requested information and re-open the issue report. 
Thanks!
