### ISSUE TITLE
Add ZIndex

### ISSUE THREAD

**Issue by Pingar5** [amay077/Xamarin.Forms.GoogleMaps#264]
### SUMMARY

Both iOS and Android have ZIndex on pins. It would be great if there was a binding for it.

### DETAILS

It would allow you to choose which pins are displayed on top of other markers.

```
Pin p = new Pin();
p.zIndex = 5;
```

### PLATFORMS

which platform do you want?

- [x] Android
- [x] iOS
- [ ] UWP

**Comment by amay077** [comment]
I released [Xamarin.Forms.GoogleMaps 2.0.0-beta2](https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/2.0.0-beta2) that includes ``Pin.ZIndex`` property.
Also [add to sample](https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/73252a8be473b8d9739d0929c2f5dc5c8f628e0d/XFGoogleMapSample/XFGoogleMapSample/CustomPinsPage.xaml.cs#L174-L183), you can try it!
