### ISSUE TITLE
How to customize InfoWindow in Xamarin.iOS

### ISSUE THREAD

**Issue by hungbqit** [amay077/Xamarin.Forms.GoogleMaps#266]
Please help me to implement CustomMapRenderer for Xamarin iOS project.  
I'm following this sample: https://github.com/xamarin/xamarin-forms-samples/blob/master/CustomRenderers/Map/Pin

**Comment by deextercz** [comment]
Why you just dont use this project?
https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/master/Xamarin.Forms.GoogleMaps/Xamarin.Forms.GoogleMaps.iOS/MapRenderer.cs

**Comment by hungbqit** [comment]
I want to custom google maps InfoWindow (add image, link, icon...).
The sample: **https://github.com/xamarin/xamarin-forms-samples/blob/master/CustomRenderers/Map/Pin** is OK on Xamarin Android with GG Maps; but not working with Xamarin iOS
`var nativeMap = **Control** as MKMapView;`
=> type of Control is MapView and i don't know how to continue... please help!!!

**Comment by deextercz** [comment]
There already exist issue that contains your idea https://github.com/amay077/Xamarin.Forms.GoogleMaps/issues/70
and for ios you want this http://stackoverflow.com/questions/16746765/custom-info-window-for-google-maps

**Comment by amay077** [comment]
As @deextercz said, 
Duplicate with https://github.com/amay077/Xamarin.Forms.GoogleMaps/issues/70 .
Please any comment or post 👍  in #70 .

**Comment by v725** [comment]
Is it possible to add interactive information box or a view that pops up when you select a pin on the map? That contains images, button, links etc.?Im using xamarin.forms.googlemaps.Please need help asap.Thanks
