### ISSUE TITLE
XFGoogleMapsSample fails to build

### ISSUE THREAD

**Issue by idan-rubin** [amay077/Xamarin.Forms.GoogleMaps#267]
----
### SUMMARY

XFGoogleMapSample solution fails to build with the following errors:
* CS0103	The name 'Variables' does not exist in the current context	XFGoogleMapSample.Droid	C:\Users\idan\Xamarin.Forms.GoogleMaps-master\XFGoogleMapSample\Droid\MyApp.cs	9	Active
* CS1061	'Pin' does not contain a definition for 'Flat' and no extension method 'Flat' accepting a first argument of type 'Pin' could be found (are you missing a using directive or an assembly reference?)	XFGoogleMapSample

### PLATFORMS

N/A

### HOW TO REPRODUCE

(Let me show how to reproduce with steps or codes)

1. Open Visual Studio 2015 and build XFGoogleMapsSample

**Comment by deextercz** [comment]
It is not bug, it is caused, because you have not changed file name of Variables_sample.cs to Variables.cs also you need to enter your API key

**Comment by idan-rubin** [comment]
Thank you.
