### ISSUE TITLE
Map shows blank in IOS, running sample project

### ISSUE THREAD

**Issue by richieferns** [amay077/Xamarin.Forms.GoogleMaps#268]
(This is template for issue. Please choose from feature request or bug report or others then write.)

----
### SUMMARY

(write summary of your feature request or suggestion)

### DETAILS

(write details/usecases with text, codes and images)

```
// usage of your requested feature to use
```

### PLATFORMS

which platform do you want?

- [x] Android
- [x] iOS
- [ ] UWP

----
### SUMMARY

(write summary of your bug report.)

### VERSIONS

* Xamarin.Forms.GoogleMaps - x.x.x
* Xamarin.Forms - x.x.x
* 

### PLATFORMS

- [ ] Android
- [x] iOS
- [ ] UWP

### HOW TO REPRODUCE

(Let me show how to reproduce with steps or codes)

1. 
2. 
3. 

```csharp
// code for reproduce
```

### ACTUAL IMAGES

(Let me show your actual problem images/stacktrace. If you want to capture simulator screen to animation GIF, I recomend to [LICEcap](http://www.cockos.com/licecap/).)

![something_image](your_image.png) 

```
// paste stacktrace
```

----

## OTHERS

(free format)

**Comment by deextercz** [comment]
Could you please write more detailed info?
Are you running real device or simulator?
I am running with simulator and it is working for me.

**Comment by richieferns** [comment]
I am running it on simulator(Iphone 6 IOS 10.2)

**Comment by deextercz** [comment]
It is caused, because you have not specified API key.
![screen shot 2017-03-16 at 9 46 03 am](https://cloud.githubusercontent.com/assets/23039506/23988329/0dcc118a-0a2e-11e7-92e4-e2b0bf157087.png)

![screen shot 2017-03-16 at 9 49 45 am](https://cloud.githubusercontent.com/assets/23039506/23988328/0dc87d54-0a2e-11e7-8196-458434e79aaa.png)

**Comment by richieferns** [comment]
I did specify the Api Key, in App.delegate ..
something Xamarin.FormsGoogleMaps.Init(MapsApiKey);
where MapsApiKey has the valid google key

**Comment by deextercz** [comment]
Try following Build->Clean All
Remember API key for iOS is different than for iOS

**Comment by richieferns** [comment]
still the same, have added a new API key for IOS,
and the package name added under identifier.. in the IOS application

![simulator screen shot 16-mar-2017 2 59 04 pm](https://cloud.githubusercontent.com/assets/20200767/23989703/82444d54-0a59-11e7-91ba-29c3b2b28fe1.png)

**Comment by richieferns** [comment]
Map is now showing, had to enable **Google Maps SDK for iOS** from Google console

**Comment by valentasm1** [comment]
I just want add more precise information since i had similar situation.
You need to select "Google Maps SDK for iOS" from url and press enable. 
https://console.developers.google.com/apis/library
