### ISSUE TITLE
When IsShowingUser is enabled I am unable to stop listening GPS location

### ISSUE THREAD

**Issue by deextercz** [amay077/Xamarin.Forms.GoogleMaps#269]
When IsShowingUser is enabled and I pause my app I expect to pause also listening GPS.
There should be implemented some funcionality to stop using gps location.

----
### SUMMARY
Implement feature to stop using GPS

### DETAILS

I don´t know now, how it should be implemented

### PLATFORMS

which platform do you want?

- [x] Android
- [x] iOS
- [x] UWP

**Comment by deextercz** [comment]
Probably it was my misstake i can not reproduce now

**Comment by ignasbagdonas** [comment]
I have this issue on Android, and can't find any workaround. It pause listening when gps isn't setted (flashing in toolbar), but when it setted possition (not flashing location icon in android toolbar) it doesn't stop listening on app sleep. On app sleep I always set Map.MyLocationEnabled = false;
