### ISSUE TITLE
Map for UWP is not showing in Release mode

### ISSUE THREAD

**Issue by deextercz** [amay077/Xamarin.Forms.GoogleMaps#270]
### SUMMARY

When I try to run UWP app in debug mode it works, if I switch to Release it is not showing.
I am able to reproduce in X.F.GoogleMaps Sample.
Also in debug mode I can see MapServiceToken not specified even if it is

### VERSIONS

* Xamarin.Forms.GoogleMaps - 1.8.0-beta6
* Xamarin.Forms - 2.3.3.190
* 

### PLATFORMS

- [ ] Android
- [ ] iOS
- [x] UWP

**Comment by amay077** [comment]
I reproduced too, but I don't know solution. Need a little more time.

**Comment by JKennedy24** [comment]
I think you need to register the assemblies in App.xaml.cs like so:

         var rendererAssemblies = new[]
                {
                    typeof(Xamarin.Forms.GoogleMaps.UWP.MapRenderer).GetTypeInfo().Assembly

                };
                Xamarin.Forms.Forms.Init(e, rendererAssemblies);

from: [https://forums.xamarin.com/discussion/comment/232356/#Comment_232356](https://forums.xamarin.com/discussion/comment/232356/#Comment_232356)

I haven't fully tested it yet, but I'm pretty sure it would work. 

you may want to update the documentation on usage

**Comment by amay077** [comment]
Good job 👍  !

I'll add to your code to my sample apps and update README.

**Comment by JKennedy24** [comment]
Looks good. Can probably close this bug off now
