### ISSUE TITLE
Pin.Label showing property

### ISSUE THREAD

**Issue by metzing** [amay077/Xamarin.Forms.GoogleMaps#272]
### SUMMARY

Request of the following feature: bool Pin.LabelShowing [sets whether the Label of this Pin is displayed or not]

### DETAILS

What I would like to achieve is that the Labels of all my Pins are displayed in the same time. Right now I believe the behavior is the selected Pin's Label is displayed, and the other's aren't. It would also be great, if the selected Pin's label could be "turned off". If the property is null, the current behavior remains.

Sample code:

foreach (var item in DataCollection){
    var pin = new Pin();
    pin.Label = item.Name;
    pin.LabelShowing = true;
    //...
}

I would be happy to implement this in the source, just wanted your opinion on it first, so that if it is completely impossible I would know beforehand.

### PLATFORMS

which platform do you want?

- [x] Android
- [x] iOS
- [ ] UWP

**Comment by amay077** [comment]
Hi @metzing ,
Sorry we can't implement for this issue.
Because this behavior is Google Maps API's design.

**Comment by Xenetics** [comment]
So I had an issue where I wanted to movetoregion() when pin was clicked but I didn't want to loose the functionality of the label by setting handled to true. So what I did was just call the Pin_Clicked again after I handle it the first time. Note that this does not work with the animate on movetoregion() set to true.

```csharp
       void Pin_Click(Object sender, PinClickedEventArgs args)
        {
                if (args.Handled != true)
                {
                    args.Handled = true;
                    var latlong = 360 / (Math.Pow(2, pinClickZoom));
                    map.MoveToRegion(new MapSpan(args.Pin.Position, latlong, latlong), false); // Animation needs to be false or this method does not work
                    
                    Pin_Click(sender, args);
                }
                else
                {
                    args.Handled = false;
                }
        }
```
Not sure if this helps you at all but I thought I would share.

Good Luck
