### ISSUE TITLE
[Android]Crash app with "java.lang.ClassCastException" when PushModalAsync

### ISSUE THREAD

**Issue by LukasThijs** [amay077/Xamarin.Forms.GoogleMaps#273]
Hey when pushing a modal page ontop of the map page it will cause Android 6.0 devices and higher to crash. This is very unfortunate if you consider the fact that Android 6.0 will be the standard.

### DETAILS

Error message is : java.lang.ClassCastException: com.google.maps.api.android.lib6.impl.am cannot be cast to android.view.ViewGroup

### PLATFORMS

which platform do you want?

- [x] Android
- [ ] iOS
- [ ] UWP

**Comment by amay077** [comment]
Could you try reproduce on original "Xamarin.Forms.Maps"?
I suspects this is the original behavior or Xamarin.Forms's bug.

**Comment by LukasThijs** [comment]
Hey,

Well I can't do that right now and this weekend :( accidently shutdown my working pc at work with all the code.

Well they did change something in the latest Xamarin pre releases does it still work on your 6.0 devices and up ?

Cheers

**Comment by LukasThijs** [comment]
Hey Amay077,

Well I am at the office and I will test the behavior right now. I will post a update when I am done!

**Comment by LukasThijs** [comment]
*Update* 

I have made a blank Xamarin.Forms app with the latest Xamarin.Forms + Xamarin.Forms.Maps both version  v2.3.4.221-pre6.

When I push a page modally on the map page it will not crash. When using your Nuget it will crash.

Hopefully you can take a look into the issue :)


Thanks in advance

**Comment by dw2kim** [comment]
Any updates on this bug?

**Comment by MisterJimson** [comment]
Also running into this.

**Comment by stephenmante** [comment]
Also running into this.
Try to update xamarin.forms to v2.4 - this error is already fixed
See in this link: https://bugzilla.xamarin.com/show_bug.cgi?id=59127#c4
