### ISSUE TITLE
Zoom on Current GPS Position

### ISSUE THREAD

**Issue by mpghelli** [amay077/Xamarin.Forms.GoogleMaps#275]
## FEATURE REQUEST / SUGGESTION

Zoom on Current GPS Position

### DETAILS

Hi. I saw that GoogleMaps component plots blue pin in the current position when the GPS is on.
I Want to Zoom in that position without user have to click on "My Location Button".
I think i should use MoveToRegion method to that, but not found any method to return the current position.

### PLATFORMS

- [x] Android
- [x] iOS

**Comment by deextercz** [comment]
You have to implement own gps watcher and if location changes, change camera view. For example use geolocator to get location

**Comment by amay077** [comment]
Your question is similar as #220 .

Xamarin.Forms.GoogleMaps does not provides getting location manually.
You can use Geolocator plugin and call ``Map.MoveToRegion`` or ``Map.MoveCamera / AnimateCamera`` .
