### ISSUE TITLE
HasRotationEnabled doesn't work for iOS in version 1.8.0

### ISSUE THREAD

**Issue by urnfield0** [amay077/Xamarin.Forms.GoogleMaps#278]
### SUMMARY

HasRotationEnabled doesn't work for iOS

The line with the bug is Xamarin.Forms.GoogleMaps/Xamarin.Forms.GoogleMaps.iOS/MapRenderer.cs:274

`((MapView)Control).Settings.ZoomGestures = ((Map)Element).HasRotationEnabled;`

### VERSIONS

* Xamarin.Forms.GoogleMaps - 1.8.0
* Xamarin.Forms - 2.3.4.231

### PLATFORMS

- [ ] Android
- [x] iOS
- [ ] UWP

### HOW TO REPRODUCE

1. Create a screen with a map
2. Set the HasRotationEnabled property to false
3. Run the app on an iPhone
4. Use two fingers to rotate the map

**Comment by amay077** [comment]
Just released [v1.8.1](https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/1.8.1) what fixed it.
