### ISSUE TITLE
build with Link All SDK Assemblies  Fails

### ISSUE THREAD

**Issue by soile1991** [amay077/Xamarin.Forms.GoogleMaps#280]
### SUMMARY

i get this error when i build with Link only SDK Assemblies 

### VERSIONS

* Xamarin.Forms.GoogleMaps - 1.8.0
* Xamarin.Forms - 2.3.4.231
* 

### PLATFORMS

- [x] Android
- [ ] iOS
- [ ] UWP

/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets: Error: Error executing task LinkAssemblies: error XA2006: Could not resolve reference to 'System.Void Android.Gms.Maps.Model.Polygon::set_Holes(System.Collections.Generic.IList`1<System.Collections.Generic.IList`1<Android.Gms.Maps.Model.LatLng>>)' (defined in assembly 'Xamarin.Forms.GoogleMaps.Android, Version=1.8.0.7, Culture=neutral, PublicKeyToken=null') with scope 'Xamarin.GooglePlayServices.Maps, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. When the scope is different from the defining assembly, it usually means that the type is forwarded. (test.Droid)

**Comment by amay077** [comment]
``Polygon::set_Holes`` is deleted in latest Xamarin.GooglePlayServices.Maps.

Please try downgrade Xamarin.Forms to 2.3.3- .

**Comment by amay077** [comment]
Could you try [v1.8.2-beta1](https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/1.8.2-beta1) ?

**Comment by soile1991** [comment]
I tried in debug mode with link sdk assemblies only in works ok but in release mode with link sdk assemblies only i get this error 
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets: Error: Error executing task LinkAssemblies: error XA2006: Could not resolve reference to 'Android.Gms.Maps.GoogleMap Android.Gms.Maps.MapView::get_Map()' (defined in assembly 'Xamarin.Forms.GoogleMaps.Android, Version=1.8.1.0, Culture=neutral, PublicKeyToken=null') with scope 'Xamarin.GooglePlayServices.Maps, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. When the scope is different from the defining assembly, it usually means that the type is forwarded. (test.Droid)

**Comment by amay077** [comment]
I just released [Xamarin.Forms.GoogleMaps 2.0.0-beta1](https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/2.0.0-beta1).
This includes Xamarin.Forms 2.3.4+ and Xamarin.GooglePlayservices.Maps 42+ supports.
Could you try it?

**Comment by soile1991** [comment]
Works like a charm, thank you very much !!
