### ISSUE TITLE
Group pins by zoom level

### ISSUE THREAD

**Issue by mpghelli** [amay077/Xamarin.Forms.GoogleMaps#282]
## FEATURE REQUEST / SUGGESTION

Group pins by zoom level

### DETAILS

Hi, I have some pins on the map of my country.

I want to when the user has higher zoom level, it automatically group all visible pins in a summary pin, that is, if in Visible Region i had 40 pins, in higher zoom level it will plot just one pin with that number inside. Is there some way to do that?

Thanks

### PLATFORMS

which platform do you want?

- [x] Android
- [x] iOS
- [ ] UWP

**Comment by amay077** [comment]
Probably you want it is [Marker clustering](https://developers.google.com/maps/documentation/javascript/marker-clustering).

We have a issue #123 what about implementing marker clustering.

**Comment by mpghelli** [comment]
Why don't incorporate that resource on the Xamarin.Forms.GoogleMaps package?

**Comment by amay077** [comment]
Continue discus in #123 .
Close it.

**Comment by mpghelli** [comment]
Please. It is so much better if we can work with cluster native on Xamarin.Forms.GoogleMaps. Within it all resources, including Polygons too.

**Comment by andreslon** [comment]
@mpghelli +1 , the clustering option is required on Xamarin.Forms.GoogleMaps
