### ISSUE TITLE
LinkAssemblies issue

### ISSUE THREAD

**Issue by kostadinSpiridonov** [amay077/Xamarin.Forms.GoogleMaps#284]
### SUMMARY

I get this error when i build with Link only SDK Assemblies.
MSB4018: The "LinkAssemblies" task failed unexpectedly.

### VERSIONS

* Xamarin.Forms.GoogleMaps - 1.7.1
* Xamarin.Forms - 2.3.4.224
* Xamarin.GooglePlayServices.xxx - 32.961.0

### PLATFORMS

- [x] Android
- [ ] iOS
- [ ] UWP

C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1575,5): error MSB4018: The "LinkAssemblies" task failed unexpectedly.
C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1575,5): error MSB4018: Java.Interop.Tools.Diagnostics.XamarinAndroidException: error XA2006: Could not resolve reference to 'Android.Gms.Maps.GoogleMap Android.Gms.Maps.MapView::get_Map()' (defined in assembly 'Xamarin.Forms.GoogleMaps.Android, Version=1.7.1.0, Culture=neutral, PublicKeyToken=null') with scope 'Xamarin.GooglePlayServices.Maps, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. When the scope is different from the defining assembly, it usually means that the type is forwarded. ---> Mono.Cecil.ResolutionException: Failed to resolve Android.Gms.Maps.GoogleMap Android.Gms.Maps.MapView::get_Map()

**Comment by amay077** [comment]
It seems same as #280

**Comment by kostadinSpiridonov** [comment]
The problem here is in Android.Gms.Maps.GoogleMap Android.Gms.Maps.MapView::get_Map() not in  'System.Void Android.Gms.Maps.Model.Polygon::set_Holes.

**Comment by amay077** [comment]
Could you try [v1.8.2-beta1](https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/1.8.2-beta1) ?

**Comment by kostadinSpiridonov** [comment]
I tried, but it doesn't work.

**Comment by amay077** [comment]
😭

**Comment by amay077** [comment]
Sorry, I misunderstood.
You say ``MapView::get_Map()`` but I resolved about ``set_Holes()``.

I think we can't support Xamarin.GooglePlayServices.xxx  29.x and 32+ both.

**Comment by kostadinSpiridonov** [comment]
Whick version of  Xamarin.GooglePlayServices and Xamarin.Forms.GoogleMaps can I use?
Thank you

**Comment by mamnarock** [comment]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets: Error: Error executing task LinkAssemblies: error XA2006: Could not resolve reference to 'Android.Gms.Maps.GoogleMap Android.Gms.Maps.MapView::get_Map()' (defined in assembly 'Xamarin.Forms.GoogleMaps.Android, Version=1.8.1.0, Culture=neutral, PublicKeyToken=null') with scope 'Xamarin.GooglePlayServices.Maps, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. When the scope is different from the defining assembly, it usually means that the type is forwarded. (client.Droid)

**Comment by godspede** [comment]
Can confirm the same issue with the latest version of GooglePlayServices, including after updating to the beta.

Java.Interop.Tools.Diagnostics.XamarinAndroidException: error XA2006: Could not resolve reference to 'Android.Gms.Maps.GoogleMap Android.Gms.Maps.MapView::get_Map()' (defined in assembly 'Xamarin.Forms.GoogleMaps.Android, Version=1.8.1.0, Culture=neutral, PublicKeyToken=null') with scope 'Xamarin.GooglePlayServices.Maps, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. When the scope is different from the defining assembly, it usually means that the type is forwarded. ---> Mono.Cecil.ResolutionException: Failed to resolve Android.Gms.Maps.GoogleMap Android.Gms.Maps.MapView::get_Map()
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   --- End of inner exception stack trace ---
   at Java.Interop.Tools.Diagnostics.Diagnostic.Error(Int32 code, Exception innerException, String message, Object[] args)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	

Working around it for now by reverting back to latest stable and setting Linking to none.

**Comment by amay077** [comment]
I just released [Xamarin.Forms.GoogleMaps 2.0.0-beta1](https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/2.0.0-beta1).
This includes Xamarin.Forms 2.3.4+ and Xamarin.GooglePlayservices.Maps 42+ supports.
Could you try it?
