### ISSUE TITLE
Referrrer setting for custom tile

### ISSUE THREAD

**Issue by woojung3** [amay077/Xamarin.Forms.GoogleMaps#289]
### SUMMARY

Currently "Custom tile support" only supports public url, like "https://cyberjapandata.gsi.go.jp/xyz/std/{zoom}/{x}/{y}.png".

We are planning to use private url which needs specific referrer to be set. It would be very appreciated if Forms.GoogleMaps supports referrer setting.

### DETAILS

For example,

var tileLayer = TileLayer.FromTileUri((int x, int y, int zoom) => 
    new Uri($"https://cyberjapandata.gsi.go.jp/xyz/std/{zoom}/{x}/{y}.png")
);
map.TileLayers.Add(tileLayer);
map.TileLayers.Referrrer = "some_private_site.com";

Something Like this?

### PLATFORMS

which platform do you want?

- [x] Android
- [x] iOS
- [ ] UWP

**Comment by amay077** [comment]
Hi @woojung3 ,
Your suggestion is nice 👍  but I think can not implement it.
Because TileLayer is depend on Google Maps API.
Google Maps API does not provide how set to referrer.

**Comment by woojung3** [comment]
Okay @amay077 , I got it.
Thank you for your kind reply.

**Comment by amay077** [comment]
Thanks for your comments.
