### ISSUE TITLE
Gesture Recognizers

### ISSUE THREAD

**Issue by mattmusc** [amay077/Xamarin.Forms.GoogleMaps#290]
# How to add a gesture Recognizer

Hi, first many thanks for the plugin. It is really helpful.

I would like to handle the `UIScreenEdgePanGesture` event or at least a Pan Event, from left and right edges of the screen.
However, when I implement the recognizer in the custom map renderer, the callback does not get called.

Here is the code:
```
leftEdgeGestureRecognizer = new UIScreenEdgePanGestureRecognizer();
leftEdgeGestureRecognizer.Edges = UIRectEdge.Left;
AddGestureRecognizer(leftEdgeGestureRecognizer);
leftEdgeGestureRecognizer.AddTarget(() => HandleEdgePanGesture(leftEdgeGestureRecognizer));
```

I tried also to implement this functionality in Xamarin.Forms, subclassing `Xamarin.Forms.GoogleMaps.Map` but there is no method `AddGestureRecognizer`.

Any way to solve this? Why the recognizers don't work? Why there is not `AddGestureRecognizer` to the Xamarin.Forms Google Maps wrapper?

Thanks.

**Comment by amay077** [comment]
We have not received the requested information. 
If you are still experiencing this issue please provide all the requested information and re-open the issue report. 
Thanks!
