### ISSUE TITLE
mmap

### ISSUE THREAD

**Issue by poseydonfba** [amay077/Xamarin.Forms.GoogleMaps#292]
(This is template for issue. Please choose from feature request or bug report or others then write.
If you need realtime communication then you can join our [gitter room](https://gitter.im/Xamarin-Forms-GoogleMaps/public).)

----
### SUMMARY

(write summary of your feature request or suggestion)

### DETAILS

(write details/usecases with text, codes and images)

```
// usage of your requested feature to use
```

### PLATFORMS

which platform do you want?

- [x] Android
- [ ] iOS
- [ ] UWP

----
### SUMMARY

(write summary of your bug report.)

### VERSIONS

* Xamarin.Forms.GoogleMaps - x.x.x
* Xamarin.Forms - x.x.x
* 

### PLATFORMS

- [ ] Android
- [x] iOS
- [ ] UWP

### HOW TO REPRODUCE

(Let me show how to reproduce with steps or codes)

1. 
2. 
3. 

```csharp
// code for reproduce
```

### ACTUAL IMAGES

(Let me show your actual problem images/stacktrace. If you want to capture simulator screen to animation GIF, I recomend to [LICEcap](http://www.cockos.com/licecap/).)

![something_image](your_image.png) 

```
// paste stacktrace
```

----

## OTHERS

(free format)

**Comment by amay077** [comment]
I don't understand.
Please re-post issue.
