### ISSUE TITLE
[Android & iOS] Bug - Custom pin icon is not drawn in the center of position

### ISSUE THREAD

**Issue by dw2kim** [amay077/Xamarin.Forms.GoogleMaps#296]
### SUMMARY

Custom pin icon is not drawn in the center of position.

### DETAILS

This is an example:

The custom pin with icon is drawn at the position (lat: 43.8476200226465, long: -73.4234762191772).
Also, the circle is drawn at the same position (lat: 43.8476200226465, long: -73.4234762191772).

The custom pin with icon is not drawn in the center of the circle:
![image](https://cloud.githubusercontent.com/assets/8919703/25917049/d8b048da-3594-11e7-8d78-b7c852956f1f.png)

### PLATFORMS
- [Y] Android
- [Y] iOS
- [X] UWP

### VERSIONS
* Xamarin.Forms.GoogleMaps - 1.8.1
* Xamarin.Forms - 2.3.4.231

**Comment by amay077** [comment]
You should set ``Pin.Anchor`` property to ``0.5, 0.5``.
Anchor default value is ``0.5, 1.0``. This means **Center and Bottom**.

https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/4e41bcb3901d1c1a52ff32dc5f9157a453a97ff1/XFGoogleMapSample/XFGoogleMapSample/PinsPage.xaml.cs#L126
