### ISSUE TITLE
Add Map Projection property to offset the center of the map.

### ISSUE THREAD

**Issue by rizaanlakay** [amay077/Xamarin.Forms.GoogleMaps#298]
(This is template for issue. Please choose from feature request or bug report or others then write.
If you need realtime communication then you can join our [gitter room](https://gitter.im/Xamarin-Forms-GoogleMaps/public).)

----
## FEATURE REQUEST / SUGGESTION
I would like to offset the center of the map further to the bottom 1/3 of the screen, much like the GPS would do. I've see guys on the internet use the .getProjection or Projection property on the Map object.
Could you either expose the .Projection property or implement the offset :)
### SUMMARY

(write summary of your feature request or suggestion)

### DETAILS

(write details/usecases with text, codes and images)

```
// usage of your requested feature to use
```

### PLATFORMS

which platform do you want?

- [x] Android
- [x ] iOS
- [ ] UWP

----
### SUMMARY

(write summary of your bug report.)

### VERSIONS

* Xamarin.Forms.GoogleMaps - x.x.x
* Xamarin.Forms - x.x.x
* 

### PLATFORMS

- [x ] Android
- [x] iOS
- [ ] UWP

### HOW TO REPRODUCE

(Let me show how to reproduce with steps or codes)

1. 
2. 
3. 

```csharp
// code for reproduce
```

### ACTUAL IMAGES

(Let me show your actual problem images/stacktrace. If you want to capture simulator screen to animation GIF, I recomend to [LICEcap](http://www.cockos.com/licecap/).)

![something_image](your_image.png) 

```
// paste stacktrace
```

----

## OTHERS

(free format)

**Comment by amay077** [comment]
You can use ``Map.Padding`` property that is offset the center of the map.

https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/4e41bcb3901d1c1a52ff32dc5f9157a453a97ff1/XFGoogleMapSample/XFGoogleMapSample/CameraPage.xaml.cs#L113
