### ISSUE TITLE
Offline Mode

### ISSUE THREAD

**Issue by mpghelli** [amay077/Xamarin.Forms.GoogleMaps#300]
## FEATURE REQUEST / SUGGESTION

Offline mode

### SUMMARY

Is there Someway that the component could implement to work with offline mode too?
It seems google maps sdk don't implement this yet:

https://issuetracker.google.com/issues/35827808

But i saw some custom solutions in that way:

https://code.google.com/archive/p/ogmaps/

Is that viable to Xamarin.Forms.GoogleMaps?

### PLATFORMS

which platform do you want?

- [x] Android
- [x] iOS
- [ ] UWP

### VERSIONS

* Xamarin.Forms.GoogleMaps - 1.8.1

**Comment by amay077** [comment]
No we can't.
Because Xamarin.Forms.GoogleMaps is depends on Google Maps SDK.
We can't inject some custom implementations.
