### ISSUE TITLE
Close / Disable Info Window

### ISSUE THREAD

**Issue by Gavrielo** [amay077/Xamarin.Forms.GoogleMaps#303]
Close / Disable Info Window

I need the ability to just disable info window so it does not popup - I can get this working on iOS by just setting the selected pin again but this does not work for Android.

### PLATFORMS

- [x] Android
- [ ] iOS
- [ ] UWP

----

**Comment by amay077** [comment]
Could you try below code?
This is disable Pin selecting.

```
map.PinClicked += (sender, e) => 
{
    e.Handled = !map.IsEnabled;
};
```

**Comment by Gavrielo** [comment]
Hi Amay,

I've tried and it still ignores anything I place in the brackets:

```
					myMap.PinClicked += (sender, e) =>
					{
                        DisplayAlert("Test","test","ok"); //display doesn't show up
						e.Handled = !myMap.IsEnabled; // pin popup still appears
					};
```

**Comment by aybarsyalcin** [comment]
Hi , you can use code for disable Info Window 
myMap.PinClicked += (sender, e) =>
	{
               e.Pin.Label = null;
                e.Pin.Address = null;
	};
