### ISSUE TITLE
How to change the Camera Bearing(orientation)

### ISSUE THREAD

**Issue by jmjcoelho** [amay077/Xamarin.Forms.GoogleMaps#305]
### SUMMARY

I need to change camera Bearing(orientation) to align the map with the direction of travellling, is this possible?

### PLATFORMS

which platform do you want?

- [x] Android
- [ ] iOS
- [ ] UWP

Many thanks is advance
Jose Coelho

**Comment by amay077** [comment]
You can use below code.

```
 await map.MoveCamera(CameraUpdateFactory.NewCameraPosition(
                    new CameraPosition(
                        latLng, // new position
                        17d, // zoom
                        45d, // bearing(rotation)
                        60d // tilt
                        )));
```

https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/aaba954ac405eec2df465cd1267a5dcf28861d59/XFGoogleMapSample/XFGoogleMapSample/CameraPage.xaml.cs#L58-L64

**Comment by jmjcoelho** [comment]
That worked.

Many thanks
Jose Coelho
