### ISSUE TITLE
Custom markers do not scale correctly on Android

### ISSUE THREAD

**Issue by gviddy** [amay077/Xamarin.Forms.GoogleMaps#307]
----
### SUMMARY

On Android my map icons are not scaling. They are really large on a low res phone and really tiny on my Samsung Galaxy S6 and high resolution emulator screens.

### DETAILS

I am loading them BitmapDescriptorFactory.FromBundle(). Is there something I need to do for them to scale correctly? They draw ok on iOS and the default pin marker is correct size on Android but not the markers i load.

### PLATFORMS

which platform do you want?

- [x] Android
- [x] iOS
- [ ] UWP

----

### VERSIONS

* Xamarin.Forms.GoogleMaps - 1.8.1
* Xamarin.Forms - 2.3.4.247

### PLATFORMS

- [x] Android
- [ ] iOS
- [ ] UWP

### HOW TO REPRODUCE

Icon = BitmapDescriptorFactory.FromBundle("marker1.png")

**Comment by deextercz** [comment]
I would recommend to you use resources in android instead, it will scale your image automaticaly, but you have to create logic that will provide stream from your resource.

    public Stream GetRandomBitmap()
    {
         Resources resources = Application.Context.Resources;
         var resourceList = new List<int>
            {
                Resource.Drawable.ic_arrow_blue,
            };

            var index = Convert.ToInt32(text);

            var resource = resourceList[index % resourceList.Count];

            Bitmap bitmap = BitmapFactory.DecodeResource(resources, resource);
            bitmap = bitmap.Copy(Bitmap.Config.Argb8888, true);
            MemoryStream stream = new MemoryStream();
            stream.Position = 0;
            bitmap.Compress(Bitmap.CompressFormat.Png, 0, stream);
            return stream;
    }

**Comment by gviddy** [comment]
thanks for the reply... will definitely look into doing it that way....

**Comment by amay077** [comment]
We have same question in #40 .
Xamarin.Forms.GoogleMaps only wrap native Google Maps API.
This means it it native Google Maps behavior.

I'll close this issue.
Please join #40.
