### ISSUE TITLE
Infowindow long press

### ISSUE THREAD

**Issue by samirkhatri** [amay077/Xamarin.Forms.GoogleMaps#308]
Hi, Is it possible to have the event InfoWindowLongClicked exposed, as it is now available in android and ios google map version. Just need to expose them. I have done it in forked repo, but then I will not able to get your update.

**Comment by samirkhatri** [comment]
Will you be able to release it soon ?

**Comment by amay077** [comment]
Yes, I'll release contained it BETA today.

**Comment by amay077** [comment]
Sorry I'm late.
I just released [Xamarin.Forms.GoogleMaps 2.1.0-beta1](https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/2.1.0-beta1) that contains this issue.

**Comment by amay077** [comment]
Released in https://github.com/amay077/Xamarin.Forms.GoogleMaps/releases/tag/v2.1.0-beta1
