### ISSUE TITLE
MapType Terrain

### ISSUE THREAD

**Issue by fmarsoni** [amay077/Xamarin.Forms.GoogleMaps#313]
Both Xamarin.Google.iOS.Maps 2.1.0.1 and android Xamarin.GooglePlayServices.Maps 42.1021.1 supports MapType Terrain. Can you add it?

**Comment by amay077** [comment]
Sure! 
We can add ``MapType.Terrain`` and implement on Android and iOS easily.

I hope somebody add this.

**Comment by amay077** [comment]
Released in https://github.com/amay077/Xamarin.Forms.GoogleMaps/releases/tag/v2.1.0-beta6
