### ISSUE TITLE
Pin Icon From Url

### ISSUE THREAD

**Issue by APinheiroPT** [amay077/Xamarin.Forms.GoogleMaps#316]
## FEATURE REQUEST

Would be nice if we can set the pin image from a url. I can't do that right now.

### PLATFORMS

which platform do you want?

- [x] Android
- [x] iOS
- [x] UWP

**Comment by szybki8562** [comment]
same problem right now

**Comment by krazazian** [comment]
you can do it by opening a Stream.  Ive done this approach, but I ran into timing issues with my map.
using (HttpClient client = new HttpClient())
            {
                Stream stream = await client.GetStreamAsync(url);
                var bmp = SKBitmap.Decode(stream);
            }

**Comment by APinheiroPT** [comment]
I think if amay077 can change the type of icon property from BitmapDescriptor to ImageSource(Xamarin.Forms) it will made much more easy accomplish all things we wanted.

**Comment by amay077** [comment]
Is there someone who know how to convert ImageSource to native Bitmap(Android:Bitmap, iOS:UIImage) or byte array?

**Comment by edmckee** [comment]
Curious if anyone has found a good solution for this.  I originally did this using Akavache but ran into release problems with that plugin, in addition to the fact that it seemed like a large dependency to introduce to get a bitmap stream.
