### ISSUE TITLE
No way to remove Polyline from GoogleMap

### ISSUE THREAD

**Issue by shengguow** [amay077/Xamarin.Forms.GoogleMaps#321]
## FEATURE REQUEST / SUGGESTION
Polylines.Clear() only remove all elements,but polylines on Google Map are still visible,
I can't find way to remove these polylines from Google Map,
It is recommended to be able remove Polylines manually, or polylines added before will be always visible on the Google Map.

To reproduce the issue by simply:
1. Add polylines manually (ex: map.Polylines.Add(polyline1),map.Polylines.Add(polyline2)
2. Remove polylines by calling map.Polylines.Clear() or remove element by element.

Thank you!

### SUMMARY
Map.Polylines.Clear() does no remove polylines from Google Map
I also tried to remove it element by element, and no luck with it.

### PLATFORMS

which platform do you want?

- [x] Android
- [x] iOS
- [x] UWP

### VERSIONS
* Xamarin.Forms.GoogleMaps - 1.8..1

**Comment by Resham143** [comment]
I am facing same issue in 2.1.0  version of Xamarin.Forms.GoogleMaps did you found any solution.
Thanks.

**Comment by shengguow** [comment]
So far not yet. :(
(But I found the TKCustomMap, it is possible to get over on this issue).

**Comment by amay077** [comment]
We have not received the requested information. 
If you are still experiencing this issue please provide all the requested information and re-open the issue report. 
Thanks!

**Comment by damanbedi2011** [comment]
use the below code for Clear your map.
```

 mymap.Polylines.Clear();
 mymap.Pins.Clear();
```

**Comment by mhaas2-tgm** [comment]
@damanbedi2011 This method doesnt exist...
