### ISSUE TITLE
show InfoWindow after map loading

### ISSUE THREAD

**Issue by maxdiable** [amay077/Xamarin.Forms.GoogleMaps#323]
hi, 
it's possible to show InfoWindow after map is loading ?
br
Max

**Comment by amay077** [comment]
Yes you can.

Set your pin to ``Map.SelectedPin`` in page constructor.

FYI - https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/master/XFGoogleMapSample/XFGoogleMapSample/CustomPinsPage.xaml.cs#L196

**Comment by maxdiable** [comment]
good :)
br
Max
