### ISSUE TITLE
ZIndex property for the polyline

### ISSUE THREAD

**Issue by Hofmanix** [amay077/Xamarin.Forms.GoogleMaps#325]
### SUMMARY

Add zIndex property for the polyline on iOS and Android

### DETAILS

(write details/usecases with text, codes and images)

```
When i use custom tiles in the googlemaps and then create polyline, it will be under the custom tiles so i can´t see it, setting zIndex to the polyline can solve this
```

### PLATFORMS

which platform do you want?

- [x] Android
- [x] iOS
- [ ] UWP

**Comment by amay077** [comment]
Released in https://github.com/amay077/Xamarin.Forms.GoogleMaps/releases/tag/v2.1.0-beta6
