### ISSUE TITLE
Polyline for UWP

### ISSUE THREAD

**Issue by Hofmanix** [amay077/Xamarin.Forms.GoogleMaps#326]
### SUMMARY

Create polyline for UWP Bing map

### DETAILS

```
Polyline to show on UWP Bing map
```

### PLATFORMS

which platform do you want?

- [ ] Android
- [ ] iOS
- [x] UWP

**Comment by amay077** [comment]
Released in https://github.com/amay077/Xamarin.Forms.GoogleMaps/releases/tag/v2.1.0-beta6
