### ISSUE TITLE
InfoWindowClick for UWP

### ISSUE THREAD

**Issue by Hofmanix** [amay077/Xamarin.Forms.GoogleMaps#327]
### SUMMARY

Add InfoWindowClick event for UWP Bing maps

### DETAILS

UWP has custom info window over the pin in this plugin but click event on it is not implemented

### PLATFORMS

which platform do you want?

- [ ] Android
- [ ] iOS
- [x] UWP

**Comment by amay077** [comment]
Released in https://github.com/amay077/Xamarin.Forms.GoogleMaps/releases/tag/v2.1.0-beta6
