### ISSUE TITLE
Support custom marker

### ISSUE THREAD

**Issue by amay077** [amay077/Xamarin.Forms.GoogleMaps#33]
* [Marker  |  Google Maps Android API  |  Google Developers](https://developers.google.com/maps/documentation/android-api/marker?hl=ja#_6)
* [Marker  |  Google Maps SDK for iOS  |  Google Developers](https://developers.google.com/maps/documentation/ios-sdk/marker)

**Comment by talhaa91** [comment]
When will this be available?

**Comment by amay077** [comment]
Maybe 1-2 weeks later.
What features do you need?

ex)

* using bitmap
* rotation
* anchor
* transparency
* ...

**Comment by talhaa91** [comment]
I think just a custom marker image would do. If you can prioritize that and ship a nuget.

**Comment by amay077** [comment]
Thanks.
First, I will implement custom marker, and upload to nuget as pre-release.
Please check that.

**Comment by aubykhan** [comment]
Yes, definitely need this feature sooner (Y).

**Comment by amay077** [comment]
Current status:

![screenshot](https://cloud.githubusercontent.com/assets/401369/16775280/dc06ced8-489a-11e6-82ac-ec048e2f86d1.png)

**Comment by amay077** [comment]
I deployed v1.4.0-beta1 to nuget.
https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/1.4.0-beta1

This release contains as follows:

* Support custom marker #33
* [iOS] Exception: Specified cast is not valid #38

You can try "CUSTOM PIN" in [XFGoogleMapSample(develop branch)](https://github.com/amay077/Xamarin.Forms.GoogleMaps/tree/develop/XFGoogleMapSample).

**Comment by amay077** [comment]
v1.4.0 is now stable!
https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/1.4.0
