### ISSUE TITLE
ZIndex property for the circle and polygon

### ISSUE THREAD

**Issue by ViktorBylbas** [amay077/Xamarin.Forms.GoogleMaps#331]
### SUMMARY

Add zIndex property for the circle on iOS and Android

### PLATFORMS

which platform do you want?

- [x] Android
- [x] iOS
- [ ] UWP

**Comment by amay077** [comment]
Also we need Z-index for polygons.

**Comment by amay077** [comment]
Polyline already has ZIndex property.

https://github.com/amay077/Xamarin.Forms.GoogleMaps/pull/328

Is there someone who implement this?

**Comment by Hofmanix** [comment]
I'll make it

**Comment by amay077** [comment]
I released https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/2.1.0-beta7 that include it.
