### ISSUE TITLE
[Android/iOS]HasScrollEnabled Not Working Correctly

### ISSUE THREAD

**Issue by JRC-BitBull** [amay077/Xamarin.Forms.GoogleMaps#335]
----
## BUG / PROBLEM REPORT

As of latest version iOS maps don't respond to the HasScrollEnabled property being set to false if set from Xaml or in constructor of the parent page.

### VERSIONS

* Xamarin.Forms.GoogleMaps - 2.1.0 beta 6
* Xamarin.Forms - 2.3.4.247

### PLATFORMS

- [x] iOS

### HOW TO REPRODUCE

Just add a map to Xaml and set HasScrollEnabled to false.

**Comment by JRC-BitBull** [comment]
Actually this seems to affect Android as well.

**Comment by amay077** [comment]
Thanks I reproduce in Android and iOS.
I'll fix it as soon.

**Comment by amay077** [comment]
I'm in progress.

But you can use ``Map.UiSettings.ScrollGesturesEnabled`` instead of ``HasScrollEnabled ``.
I'll mark as obsolete ``HasScrollEnabled `` property because UiSettings is completely support Google Maps API's UiSettings class.

**Comment by JRC-BitBull** [comment]
OK - great, thanks.

Also something else I’ve come across is that if you have a map on one page (on Android) and go to another page also containing a map, the ‘old’ map is still present in front of the new one (only inactive).

I seem to have fixed this by adding this method to MapRenderer in Android…

private bool control_removed;

        protected override void OnVisibilityChanged(global::Android.Views.View view, ViewStates visibility)
        {
            base.OnVisibilityChanged(view, visibility);

            if (visibility == ViewStates.Visible && control_removed)
            {
                // just in case do visible stuff here
                Control.Visibility = ViewStates.Visible;
                AddView(Control);
                control_removed = false;
            }

            if (visibility == ViewStates.Gone)
            {
                // run surfaceDestroy logic here also!
                Control.Visibility = ViewStates.Gone;
                RemoveView(Control);
                control_removed = true;
            }
        }

Also in Android MapRenderer I found I had to add the check for null in the following method otherwise if you move to another page as the result of clicking a pin you get a NullPointerException. 

public void OnCameraChange(GCameraPosition pos)
        {
            UpdateVisibleRegion(pos.Target);
            var camera = pos.ToXamarinForms();
            if (Map != null)
            {
                Map.CameraPosition = camera;
                Map.SendCameraChanged(camera);
            }
        }

cheers

====

James Closs, Director, BitBull Ltd

http://www.bitbull.com <http://www.bitbull.com/> 

07771 991171 | @BitBullDotCom

====

Check out the #giantjm trailer: http://bit.ly/1XSStQu <http://http//bit.ly/1XSStQu>

**Comment by amay077** [comment]
We have not received the requested information. 
If you are still experiencing this issue please provide all the requested information and re-open the issue report. 
Thanks!
