### ISSUE TITLE
Android enable use of Resource/drawable-x assets for custom pins

### ISSUE THREAD

**Issue by KristofColpaertITP** [amay077/Xamarin.Forms.GoogleMaps#337]
### SUMMARY

Provide a way to use _/Resources/drawable-mdpi_, _/Resources/drawable-hdpi_ ... as assets for custom pins on Android.

### DETAILS

Currently it's possible to have custom pins with images that are provided in the Assets-folder of the Xamarin.Droid project. But there's no way to make a distinction between MDPI, HDPI, XHDPI, XXHDPI and XXXHDPI screen resolutions with images in the Assets-folder.

It would be a better solution to enable the use of images that are provided in the /Resources/drawable-x folders. This way, it is possible to make a proper distinction between MDPI, HDPI, XHDPI, XXHDPI and XXXHDPI screen resolutions.

Check native Android library [BitmapDescriptorFactory.fromResource()](https://developers.google.com/android/reference/com/google/android/gms/maps/model/BitmapDescriptorFactory.html#fromResource(int)).

### PLATFORMS

- [x] Android
- [ ] iOS
- [ ] UWP

**Comment by amay077** [comment]
Good point!
We consider compatibility for iOS.
Do you have any idea?

I have an another way what provide native object access.
https://github.com/amay077/Xamarin.Forms.GoogleMaps/issues/29

**Comment by ormedo** [comment]
With FromPath method you can delegate the client the absolutepath of the resource.
Actually commented

**Comment by amay077** [comment]
I have an idea for implement it.

https://github.com/amay077/Xamarin.Forms.GoogleMaps/issues/436

Please any comment or vote up(:+1:) in #436 .
