### ISSUE TITLE
SelectedPinChanged for UWP

### ISSUE THREAD

**Issue by Hofmanix** [amay077/Xamarin.Forms.GoogleMaps#341]
### SUMMARY

Implement selected pin changed event for uwp

### DETAILS

Selected pin and pin tapped is already implemented for UWP but, selected pin changed is not, event if it is easy to implement with this possibilities

### PLATFORMS

which platform do you want?

- [ ] Android
- [ ] iOS
- [x] UWP

**Comment by amay077** [comment]
I released https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/2.1.0-beta7 that include it.
