### ISSUE TITLE
Generate unhandled exception when I added Init function

### ISSUE THREAD

**Issue by miakim2017** [amay077/Xamarin.Forms.GoogleMaps#344]
(This is template for issue. Please choose from feature request or bug report or others then write.
If you need realtime communication then you can join our [gitter room](https://gitter.im/Xamarin-Forms-GoogleMaps/public).)

----
### PLATFORMS

which platform do you want?

- [x] Android
- [ ] iOS
- [ ] UWP

----
### SUMMARY

I tried to add FormsGoogleMaps.Init on MainActivity.cs in Android, but it kept failed.

### VERSIONS

Hi I've used Xamarin.Forms.GoogleMaps ver 2.1.0-beta6 and updated Xamarin forms.
I was going to make sure to having the same property and development environment, but because of other packages that I have to use, only difference is the targeting. 

My targetFramework is   <package id="Xamarin.Forms.GoogleMaps" version="2.1.0-beta6" targetFramework="portable46-net451+win81" />

Anyway, as you nocticed, I tried to add FormsGoogleMaps.Init on MainActivity.cs in Android. But it kept occur unhandled exception. Also the weird thing is I don't have Myapp. cs too.

I'm suppose to make IOS app as well, but Ive tested only Android app just now by using emulator.
Actually can I modify or add some Android code directly? How can I solve this problem?

* Xamarin.Forms.GoogleMaps -2.1.0-beta6
* Xamarin.Forms -2.3.4.247

### PLATFORMS

- [x ] Android
- [] iOS
- [ ] UWP

### HOW TO REPRODUCE

(Let me show how to reproduce with steps or codes)

1. 
2. 
3. 

```csharp
// code for reproduce
```

### ACTUAL IMAGES

(Let me show your actual problem images/stacktrace. If you want to capture simulator screen to animation GIF, I recomend to [LICEcap](http://www.cockos.com/licecap/).)

![something_image](your_image.png) 

```
// paste stacktrace
```

----

## OTHERS

(free format)

**Comment by amay077** [comment]
Sorry I'm late.
Could you reproduce this yet?

**Comment by amay077** [comment]
We have not received the requested information. 
If you are still experiencing this issue please provide all the requested information and re-open the issue report. 
Thanks!
