### ISSUE TITLE
Can't install NuGet package on Androis or PCL

### ISSUE THREAD

**Issue by SykesJohn** [amay077/Xamarin.Forms.GoogleMaps#346]
### SUMMARY

Would not install package
### DETAILS

Could not install package 'Xamarin.Forms.GoogleMaps 2.0.0'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v6.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.	```

### PLATFORMS

which platform do you want?

- [x] Android 6.0
- [ ] iOS
- [ ] UWP

* Xamarin.Forms.GoogleMaps - 2.0.0

### HOW TO REPRODUCE

1. Install NuGet package.
2. 
3.

**Comment by brunoracosta** [comment]
I have the same problem. 

For Add more information:
-  In **Edit References** I have the Assembly Mono.Android - Package Xamarin.Android v6.0 Suport
-  I am using Visual Studio For Mac

**Comment by amay077** [comment]
Xamarin.Forms.GoogleMaps 2.x is only support for MonoAndroid version 7.0+ .
Please re-select your app target.
