### ISSUE TITLE
Doesn't seem to be possible to have custom marker images come from resources folder on Android. 

### ISSUE THREAD

**Issue by garypope** [amay077/Xamarin.Forms.GoogleMaps#347]
When I use the BitmapDescriptorFactory.FromBundle("home_pin.png") method and the file home_pin.png is in the resources/drawable folder I get an exception..

----
## Stacktrace ##
[MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] Java.Lang.RuntimeException: bitmap
[MonoDroid]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <bb24406fc7674544b0aeca80bf301743>:0 
[MonoDroid]   at Java.Interop.JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <c9023a42821645cf8671f55f61df2c43>:0 
[MonoDroid]   at Android.Runtime.JNIEnv.CallObjectMethod (System.IntPtr jobject, System.IntPtr jmethod, Android.Runtime.JValue* parms) [0x0000e] in <a91c406c4eeb44e3a3f561c342220060>:0 
[MonoDroid]   at Android.Gms.Maps.GoogleMap.AddMarker (Android.Gms.Maps.Model.MarkerOptions options) [0x0004a] in <cede2ee4138a48bb98b62dcaee115663>:0 
[MonoDroid]   at Xamarin.Forms.GoogleMaps.Logics.Android.PinLogic.CreateNativeItem (Xamarin.Forms.GoogleMaps.Pin outerItem) [0x000b1] in <98f75d94cb8a4ee9acb39d6f8704d0a9>:0 
[MonoDroid]   at Xamarin.Forms.GoogleMaps.Logics.DefaultLogic`3[TOuter,TNative,TNativeMap].AddItems (System.Collections.IList newItems) [0x0003b] in <804e4494a5d24729b73dcda67fcede1c>:0 
[MonoDroid]   at Xamarin.Forms.GoogleMaps.Logics.DefaultLogic`3[TOuter,TNative,TNativeMap].RestoreItems () [0x00047] in <804e4494a5d24729b73dcda67fcede1c>:0 
[MonoDroid]   at Xamarin.Forms.GoogleMaps.Android.MapRenderer.InitializeLogic () [0x0002d] in <98f75d94cb8a4ee9acb39d6f8704d0a9>:0 
[MonoDroid]   at Xamarin.Forms.GoogleMaps.Android.MapRenderer.OnLayout (System.Boolean changed, System.Int32 l, System.Int32 t, System.Int32 r, System.Int32 b) [0x0002c] in <98f75d94cb8a4ee9acb39d6f8704d0a9>:0 
[MonoDroid]   at Xamarin.Forms.Platform.Android.FormsViewGroup.n_OnLayout_ZIIII (System.IntPtr jnienv, System.IntPtr native__this, System.Boolean p0, System.Int32 p1, System.Int32 p2, System.Int32 p3, System.Int32 p4) [0x00008] in <509b941eb6c9409ea563416977a01cbe>:0 
[MonoDroid]   at (wrapper dynamic-method) System.Object:848b8b23-6633-4a67-952c-fb9635832e60 (intptr,intptr,bool,int,int,int,int)
[MonoDroid]   --- End of managed Java.Lang.RuntimeException stack trace ---
[MonoDroid] java.lang.NullPointerException: bitmap
[MonoDroid] 	at com.google.maps.api.android.lib6.common.l.a(:com.google.android.gms.DynamiteModulesB:5)
[MonoDroid] 	at com.google.maps.api.android.lib6.impl.n.<init>(:com.google.android.gms.DynamiteModulesB:2)
[MonoDroid] 	at com.google.maps.api.android.lib6.impl.m.a(:com.google.android.gms.DynamiteModulesB:8)
[MonoDroid] 	at com.google.maps.api.android.lib6.impl.cy.<init>(:com.google.android.gms.DynamiteModulesB:23)
[MonoDroid] 	at com.google.maps.api.android.lib6.impl.az.a(:com.google.android.gms.DynamiteModulesB:482)
[MonoDroid] 	at com.google.android.gms.maps.internal.j.onTransact(:com.google.android.gms.DynamiteModulesB:115)
[MonoDroid] 	at android.os.Binder.transact(Binder.java:387)
[MonoDroid] 	at com.google.android.gms.maps.internal.IGoogleMapDelegate$zza$zza.addMarker(Unknown Source)
[MonoDroid] 	at com.google.android.gms.maps.GoogleMap.addMarker(Unknown Source)
[MonoDroid] 	at md5105bfc0c8b124351616acc9954ededbf.MapRenderer.n_onLayout(Native Method)
[MonoDroid] 	at md5105bfc0c8b124351616acc9954ededbf.MapRenderer.onLayout(MapRenderer.java:53)
[MonoDroid] 	at android.view.View.layout(View.java:17938)
[MonoDroid] 	at android.view.ViewGroup.layout(ViewGroup.java:5812)
[MonoDroid] 	at com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout(FormsViewGroup.java:29)
[MonoDroid] 	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.VisualElementRenderer_1.n_onLayout(Native Method)
[MonoDroid] 	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.VisualElementRenderer_1.onLayout(VisualElementRenderer_1.java:58)
[MonoDroid] 	at android.view.View.layout(View.java:17938)
[MonoDroid] 	at android.view.ViewGroup.layout(ViewGroup.java:5812)
[MonoDroid] 	at com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout(FormsViewGroup.java:29)
[MonoDroid] 	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.VisualElementRenderer_1.n_onLayout(Native Method)
[MonoDroid] 	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.VisualElementRenderer_1.onLayout(VisualElementRenderer_1.java:58)
[MonoDroid] 	at android.view.View.layout(View.java:17938)
[MonoDroid] 	at android.view.ViewGroup.layout(ViewGroup.java:5812)
[MonoDroid] 	at com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout(FormsViewGroup.java:29)
[MonoDroid] 	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.VisualElementRenderer_1.n_onLayout(Native Method)
[MonoDroid] 	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.VisualElementRenderer_1.onLayout(VisualElementRenderer_1.java:58)
[MonoDroid] 	at android.view.View.layout(View.java:17938)
[MonoDroid] 	at android.view.ViewGroup.layout(ViewGroup.java:5812)
[MonoDroid] 	at com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout(FormsViewGroup.java:29)
[MonoDroid] 	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.VisualElementRenderer_1.n_onLayout(Native Method)
[MonoDroid] 	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.VisualElementRenderer_1.onLayout(VisualElementRenderer_1.java:58)
[MonoDroid] 	at android.view.View.layout(View.java:17938)
[MonoDroid] 	at android.view.ViewGroup.layout(ViewGroup.java:5812)
[MonoDroid] 	at com.xamarin.forms.platform.android.FormsViewGroup.measureAndLayout(FormsViewGroup.java:29)
[MonoDroid] 	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.PlatformRenderer.n_onLayout(Native Method)
[MonoDroid] 	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.PlatformRenderer.onLayout(PlatformRenderer.java:55)
[MonoDroid] 	at android.view.View.layout(View.java:17938)
[MonoDroid] 	at android.view.ViewGroup.layout(ViewGroup.java:5812)
[MonoDroid] 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
[MonoDroid] 	at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1731)
[MonoDroid] 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1496)
[MonoDroid] 	at android.view.View.layout(View.java:17938)
[MonoDroid] 	at android.view.ViewGroup.layout(ViewGroup.java:5812)
[MonoDroid] 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
[MonoDroid] 	at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
[MonoDroid] 	at android.view.View.layout(View.java:17938)
[MonoDroid] 	at android.view.ViewGroup.layout(ViewGroup.java:5812)
[MonoDroid] 	at com.android.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:493)
[MonoDroid] 	at android.view.View.layout(View.java:17938)
[MonoDroid] 	at android.view.ViewGroup.layout(ViewGroup.java:5812)
[MonoDroid] 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
[MonoDroid] 	at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
[MonoDroid] 	at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:3193)
[MonoDroid] 	at android.view.View.layout(View.java:17938)
[MonoDroid] 	at android.view.ViewGroup.layout(ViewGroup.java:5812)
[MonoDroid] 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2666)
[MonoDroid] 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2367)
[MonoDroid] 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1437)
[MonoDroid] 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7397)
[MonoDroid] 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
[MonoDroid] 	at android.view.Choreographer.doCallbacks(Choreographer.java:695)
[MonoDroid] 	at android.view.Choreographer.doFrame(Choreographer.java:631)
[MonoDroid] 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
[MonoDroid] 	at android.os.Handler.handleCallback(Handler.java:739)
[MonoDroid] 	at android.os.Handler.dispatchMessage(Handler.java:95)
[MonoDroid] 	at android.os.Looper.loop(Looper.java:158)
[MonoDroid] 	at android.app.ActivityThread.main(ActivityThread.java:7224)
[MonoDroid] 	at java.lang.reflect.Method.invoke(Native Method)
[MonoDroid] 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
[MonoDroid] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by amay077** [comment]
Same as #337 .
Does not support ``resources/drawable-x`` ,
Please use [``Assets``](https://github.com/amay077/Xamarin.Forms.GoogleMaps/tree/master/XFGoogleMapSample/Droid/Assets) directory instead of drawable-x.

**Comment by amay077** [comment]
#436
