### ISSUE TITLE
FromPath() comment on BitMapDescriptorFactory

### ISSUE THREAD

**Issue by ormedo** [amay077/Xamarin.Forms.GoogleMaps#351]
----
## FEATURE REQUEST / SUGGESTION
I need to create a bitmap from resource folder images in Android to create custom Pins.
### SUMMARY

BitmapDescritorFactory.onBundle() get the images from Assets in Android, but i need to obtains the images from the resource folder.

In GitHub i see that fromPath method in BitmapDescriptFactory its commented, but in BitmapDescriptor its implemented

**Comment by JKennedy24** [comment]
Possible duplicate:
https://github.com/amay077/Xamarin.Forms.GoogleMaps/issues/337
