### ISSUE TITLE
.NET Standard Support?

### ISSUE THREAD

**Issue by gsaldana** [amay077/Xamarin.Forms.GoogleMaps#355]
Well, this is not an issue, really is a question?

does the Xamarin.Forms.GoogleMaps library has netstandard support? Or When dou you have in mind release a version with NET Standard support?

Thanks in advance

**Comment by goeaway** [comment]
I've tried myself to get it to work in .netstandard but have had no luck. Would also like to see a version with support if possible.

**Comment by ComplexVariable** [comment]
I am also waiting for .netstandard version. Are you going to release it ?

**Comment by goeaway** [comment]
Managed to get the maps working in .netstandard. I had some issues when the app initially ran but managed to get around that by initialising the map element in c# code rather than the xaml page. Don't know if that was specific to my solution but it seems like it is compatible with netstandard after all lol.

**Comment by amay077** [comment]
I have no plan to support .NET Standard.
Because this library is only for Xamarin.Forms platform.
I think If Xamarin.Forms will not support PCL then we should support .NET Standard.

Do you have any advantages for support .NET Standard?

**Comment by reachpoint1** [comment]
I need to upgrade my projects(iOS/Android) to .NET Standard 2 for many reasons/benefits(eg. EF Core 2 support). 

Xamarin.Forms.GoogleMaps works with .NET Standard 1.4 library with no issue for my projects . But it does not work with .NET Standard 2. It says "...This package may not be fully compatible with your project".

To reproduce the issue, create a new XF project and replace PCL with  new .NET Standard 2 project. (Just copy App/Main.xaml files and remove PCL). Just adding GoogleMaps will produce the error. I tested even with v2.2.0-beta1.

**Comment by MisterJimson** [comment]
I would suggest using .NET Standard 2.0, now that XF, Android and iOS all support it.

**Comment by WSudolPGS** [comment]
What is status of migration ?

**Comment by softsan** [comment]
Any updates on this?

**Comment by ConX-Ryan** [comment]
I am also interested in the .NETStandard Lib currently forcing the .NET 4.6.1 version in with some issues

**Comment by amay077** [comment]
I released https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/3.0.0-beta1 what support .NET Standard 2.0 .

Could you try it?
