### ISSUE TITLE
Get current position

### ISSUE THREAD

**Issue by ViktorBylbas** [amay077/Xamarin.Forms.GoogleMaps#357]
### SUMMARY

Get current position (latitude and longitute)

### PLATFORMS

which platform do you want?

- [x] Android
- [x] iOS
- [ ] UWP

**Comment by lengk** [comment]
There is a [library](https://github.com/jamesmontemagno/Xamarin.Plugins/tree/master/Geolocator) that does this already

**Comment by deextercz** [comment]
@amay077 Could you please add this FAQ? and creaTe FAQ at main page?
