### ISSUE TITLE
Binary Rejected _glGetQueryObjectivEXT

### ISSUE THREAD

**Issue by edmckee** [amay077/Xamarin.Forms.GoogleMaps#359]
### SUMMARY

The googleMaps package worked very well, until I submitted the app to the app store I received this rather unhelpful message.

This is the only package that we've updated since the last drop.  Has anyone seen this issue, do you use the OpenGL library, can you think of any setting or anything in the googlemaps code base that may cause this problem?

## BUG / PROBREM REPORT
We have discovered one or more issues with your recent delivery for "Goidit". To process your delivery, the following issues must be corrected:

Non-public API usage:

The app references non-public symbols in goidit_shared.iOS: _glGetQueryObjectivEXT
If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed.

### VERSIONS

* Xamarin.Forms.GoogleMaps - 2.1.10
* Xamarin.Forms - 2.3.4.247
* 

### PLATFORMS

- [ ] Android
- [x] iOS
- [ ] UWP

**Comment by amay077** [comment]
We have not received the requested information. 
If you are still experiencing this issue please provide all the requested information and re-open the issue report. 
Thanks!
