### ISSUE TITLE
UiSetting is not working on .netstandard 2.0

### ISSUE THREAD

**Issue by paradisehuman** [amay077/Xamarin.Forms.GoogleMaps#363]
Hi.
UiSetting is not working on .netstandard 2.0.
for example disabling zoom control to false , not working.

### VERSIONS

Xamarin.Forms.GoogleMaps - 2.1
Xamarin.Forms - 2.4.0.266-pre1

### PLATFORMS
Android 7.1

**Comment by amay077** [comment]
I think it is same as #371 .
Maybe already solved. Please use latest beta version.
