### ISSUE TITLE
Is it possible to animate the size of a bitmapdescriptor?

### ISSUE THREAD

**Issue by mjmostachetti** [amay077/Xamarin.Forms.GoogleMaps#366]
----
## FEATURE REQUEST / SUGGESTION

Instead of swapping a custom small pin with a custom large pin, is there a way to animate the pin's bitmapdescriptor to increase and decrease in size?

which platform do you want?

- [x] Android
- [ x] iOS
- [ ] UWP

### PLATFORMS

- [x] Android
- [x] iOS
- [ ] UWP

**Comment by amay077** [comment]
No we haven't.
You should implementing animations at yourself.
