### ISSUE TITLE
MyLocationEnabled doesn't work

### ISSUE THREAD

**Issue by D00Minik** [amay077/Xamarin.Forms.GoogleMaps#367]
----
### SUMMARY

Hi. I try to implement this plugin to my app and I noticed "MyLocationEnabled" doesn't work. When I set it to true there is no button to click and no device marker on map.  If I use "IsShowingUser" instead  then everting is fine.
Doesn't matter is it xaml or c#, result is the same.
Thank you.
### VERSIONS

* Xamarin.Forms.GoogleMaps - 4.0.1
* Xamarin.Forms -2.3.4.270
* 

### PLATFORMS

- [ API 23, 25 ] Android

### HOW TO REPRODUCE

Just add code to xaml or c#.

**Comment by amay077** [comment]
If you want to show "Location Button" then set ``true`` to ``Map.UiSettings.MyLocationButtonEnabled``.

![android_emulator_-_galaxy_nexus_api_23_5554](https://user-images.githubusercontent.com/401369/30324845-6f8b514e-97fd-11e7-8356-9acc3751ba9f.png)

**Comment by D00Minik** [comment]
Didn't help

**Comment by straiser** [comment]
Same situation. ZoomButtons also not showing on iOS.

**Comment by kingnguyen1993** [comment]
Any solution for that. I have the same issue.

**Comment by amay077** [comment]
> Same situation. ZoomButtons also not showing on iOS.

ZoomButtons is not provide by Google Maps iOS SDK.

**Comment by amay077** [comment]
I think this issue is related with #371 .
Could you try 2.2.0-beta2 https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/2.2.0-beta2 ?

**Comment by rayita** [comment]
@amay077  last version (2.2.1) MyLocationEabled works in Android but not in iOS (no blue dot, and no certer if you tap in MyLocationButton)

**Comment by matteopiccioni** [comment]
Same problem for me,
ios and android

**Comment by amay077** [comment]
I got the issue.
Wait a while for fix.

**Comment by amay077** [comment]
I fixed it and released [v2.3.0-beta2](https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/2.3.0-beta2) .
You can try it now.

**Comment by Jatsai** [comment]
Hi, Is it closed?

**Comment by amay077** [comment]
Yes I closed.
