### ISSUE TITLE
BaseCameraLogic unhandled nullpointer exception on Android

### ISSUE THREAD

**Issue by Jelle-elaut** [amay077/Xamarin.Forms.GoogleMaps#368]
I put the GoogleMaps view in a page, which works correctly on normal behaviour.
However, when this page gets opened, and the back button is pressed immediately after opening this page (so the GoogleMaps view isn't fully rendered yet) the app crashes with the following stacktrace: 

`09-06 12:50:37.602 I/MonoDroid(20835): UNHANDLED EXCEPTION:
09-06 12:50:37.616 D/Mono    (20835): [0x8027f920] hill climbing, change max number of threads 5
09-06 12:50:37.644 I/MonoDroid(20835): System.NullReferenceException: Object reference not set to an instance of an object.
09-06 12:50:37.644 I/MonoDroid(20835):   at Xamarin.Forms.GoogleMaps.Logics.BaseCameraLogic`1[TNativeMap].Register (Xamarin.Forms.GoogleMaps.Map map, TNativeMap nativeMap) [0x00021] in <7082e972b6b544548493ccf32d1392ba>:0 
09-06 12:50:37.644 I/MonoDroid(20835):   at Xamarin.Forms.GoogleMaps.Android.MapRenderer+<OnElementChanged>d__20.MoveNext () [0x00351] in <33f480a5aa3448b39a955c15f6587f42>:0 
09-06 12:50:37.644 I/MonoDroid(20835): --- End of stack trace from previous location where exception was thrown ---
09-06 12:50:37.644 I/MonoDroid(20835):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <3fd174ff54b146228c505f23cf75ce71>:0 
09-06 12:50:37.644 I/MonoDroid(20835):   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) [0x00000] in <3fd174ff54b146228c505f23cf75ce71>:0 
09-06 12:50:37.644 I/MonoDroid(20835):   at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <d855bac285f44dda8a0d8510b679b1e2>:0 
09-06 12:50:37.644 I/MonoDroid(20835):   at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <d855bac285f44dda8a0d8510b679b1e2>:0 
09-06 12:50:37.644 I/MonoDroid(20835):   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <d855bac285f44dda8a0d8510b679b1e2>:0 
09-06 12:50:37.644 I/MonoDroid(20835):   at (wrapper dynamic-method) System.Object:2c372093-ec2c-4298-96ca-2e6a00e5ed04 (intptr,intptr)
09-06 12:50:37.654 W/art     (20835): JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
09-06 12:50:37.659 D/Mono    (20835): DllImport searching in: '__Internal' ('(null)').
09-06 12:50:37.659 D/Mono    (20835): Searching for 'java_interop_jnienv_throw'.
09-06 12:50:37.659 D/Mono    (20835): Probing 'java_interop_jnienv_throw'.
09-06 12:50:37.659 D/Mono    (20835): Found as 'java_interop_jnienv_throw'.
09-06 12:50:38.535 E/mono    (20835): 
09-06 12:50:38.535 E/mono    (20835): Unhandled Exception:
09-06 12:50:38.535 E/mono    (20835): System.NullReferenceException: Object reference not set to an instance of an object.
09-06 12:50:38.535 E/mono-rt (20835): [ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object.
`

**Comment by amay077** [comment]
It is difficult to reproduce it for me.
Can you make sample app for reproduce?

**Comment by amay077** [comment]
Maybe same as #352 and fixed it.
