### ISSUE TITLE
Open infowindow in code

### ISSUE THREAD

**Issue by timdmaxey** [amay077/Xamarin.Forms.GoogleMaps#369]
### FEATURE REQUEST / SUGGESTION

Wanted to know if the current release has the ability to open the info window on a pin in code, meaning without the user tapping on the pin. Wanted to open the Label/Address with another button?

### PLATFORMS

which platform do you want?

- [x] Android
- [x] iOS
- [ ] UWP

**Comment by amay077** [comment]
You can use set to ``Map.SelectedPin`` property.

https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/master/XFGoogleMapSample/XFGoogleMapSample/PinsPage.xaml.cs#L98

Also, if you want to close info-window then set ``null`` to ``Map.SelectedPin`` property.

**Comment by timdmaxey** [comment]
Yeah that worked perfect, thank you, is there a document I can look at to see all functions etc so i wouldn't have had to bother you? Like Infowindows, can we add "callout buttons" or change the fonts etc? Thank you for everything!

**Comment by amay077** [comment]
> can we add "callout buttons" or change the fonts etc? Thank you for everything!

I have a plan to #70 - Customized information box.
But I don't have best design and how to implements it.

**Comment by KhimGurung** [comment]
Map.SelectedPin set info window visible of only one pin. How can we set all pin's info window visible?
