### ISSUE TITLE
can't use google maps custom icons

### ISSUE THREAD

**Issue by Cariaga** [amay077/Xamarin.Forms.GoogleMaps#372]
![err2](https://user-images.githubusercontent.com/9010504/30510998-58f776e4-9b02-11e7-8a10-686d88a878f3.PNG)
 BitmapDescriptorFactory.FromBundle android crash

tried
*changing the image format
*tried changing the build action to Embedded Resource and AndroidResource
*tried without extension
*currently using vs 2017 and PCL
*only works with default marker

![err](https://user-images.githubusercontent.com/9010504/30510981-f1317546-9b01-11e7-8e92-82aff012a080.PNG)

**Comment by amay077** [comment]
You should add ``icon.png`` to ``Assets`` folder and set BuildAction to ``AndroidAsset``.

See also:

* https://github.com/amay077/Xamarin.Forms.GoogleMaps/tree/master/XFGoogleMapSample/Droid/Assets
* https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/master/XFGoogleMapSample/XFGoogleMapSample/CustomPinsPage.xaml.cs#L218

**Comment by amay077** [comment]
Close this because no longer response.
