### ISSUE TITLE
Crash on Andoird 7.0 after open new Page with map.

### ISSUE THREAD

**Issue by KSemenenko** [amay077/Xamarin.Forms.GoogleMaps#373]
Hi. 
I had a crash on android when I open a new straintsu with the map.

Object reference not set to an instance of an object.
```
BaseCameraLogic`1[TNativeMap].Register (Xamarin.Forms.GoogleMaps.Map map, TNativeMap nativeMap)
MapRenderer+<OnElementChanged>d__20.MoveNext ()
ExceptionDispatchInfo.Throw ()
AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state)
SyncContext+<>c__DisplayClass2_0.<Post>b__0 ()
Thread+RunnableImplementor.Run ()
IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this)
(wrapper dynamic-method) System.Object:a2f26a92-6781-4bf8-bed7-51cca59648b9 (intptr,intptr)
```

**Comment by amay077** [comment]
Could you show me code for reproduce?

**Comment by KSemenenko** [comment]
I did the research.
In Android MapRendere.cs on line 148
```cs
 _cameraLogic.Register(Map, NativeMap);
```
property Map is null.

next, in file BaseCameraLogic.cs in constructor on line 17, variable _map is null.
So I have a crash because I can not subscribe event.

**Comment by KSemenenko** [comment]
until I can give the code. but in a nutshell, I have a few pages, on each of them a map, and I switch between them. and apparently at some point I do it too quickly

**Comment by cbagpipe** [comment]
can confirm this issue.
And that's code to reproduce this:
1. Create blank android app
2. Install latest GoogleMapsMaps and Xamarin.Forms nugets
3. Set build SDK version to 7.0 (think it's not so important)
4. Replace MainActivity.cs code with following
```csharp
using Android.App;
using Android.OS;
using Xamarin.Forms.Platform.Android;
using Xamarin.Forms;
using System.Threading;
using Xamarin.Forms.GoogleMaps;
using System;

namespace GoogleMapsTest
{
    [Activity(Label = "GoogleMapsTest", MainLauncher = true, Icon = "@drawable/icon")]
    public class MainActivity : FormsApplicationActivity
    {
        public MainActivity Current { get; private set; }

        protected override void OnCreate(Bundle bundle)
        {
            base.OnCreate(bundle);
            global::Xamarin.Forms.Forms.Init(this, bundle);
            global::Xamarin.FormsGoogleMaps.Init(this, bundle);

            Current = this;
            var app = new App();
            LoadApplication(app);
        }
    }

    class App : Xamarin.Forms.Application
    {

        StackLayout contentStack = new StackLayout() { Orientation = StackOrientation.Vertical, };
        int count;
        Timer tmrShuffleMaps;

        public App()
        {

            MainPage = new ContentPage()
            {
                Content = contentStack,
            };
            tmrShuffleMaps = new Timer(ShuffleMaps, null, 10000, 300);
            contentStack.Children.Add(new Map());
            contentStack.Children.Add(new Map());
            contentStack.Children.Add(new Map());
        }

        private void ShuffleMaps(object state)
        {
            Device.BeginInvokeOnMainThread(() =>
            {
                try
                {
                    if (count % 2 == 0)
                        contentStack.Children.RemoveAt(0);

                    if (count % 2 == 1)
                        contentStack.Children.Insert(0, new Map());

                    count++;
                }
                catch (Exception ex)
                {
                    System.Diagnostics.Trace.WriteLine(ex);
                }
            });
        }
    }
}
```
5. Run project and wait about a minute. App will crash with:

> 12-14 11:34:18.962 I/MonoDroid( 4353): UNHANDLED EXCEPTION:
> 12-14 11:34:19.036 I/MonoDroid( 4353): System.ArgumentNullException: Value cannot be null.
> 12-14 11:34:19.037 I/MonoDroid( 4353): Parameter name: map
> 12-14 11:34:19.037 I/MonoDroid( 4353):   at Xamarin.Forms.GoogleMaps.Logics.BaseCameraLogic`1[TNativeMap].Register (Xamarin.Forms.GoogleMaps.Map map, TNativeMap nativeMap) [0x00003] in 
> 
> <4123c95e7608418e92cb2c2ac657d720>:0 
> 12-14 11:34:19.037 I/MonoDroid( 4353):   at Xamarin.Forms.GoogleMaps.Logics.Android.CameraLogic.Register (Xamarin.Forms.GoogleMaps.Map map, Android.Gms.Maps.GoogleMap nativeMap) [0x00000] in <c4b84e7d85f849bc98947ab2b6942b7e>:0 
> 12-14 11:34:19.037 I/MonoDroid( 4353):   at Xamarin.Forms.GoogleMaps.Android.MapRenderer+<OnElementChanged>d__20.MoveNext () [0x00297] in <c4b84e7d85f849bc98947ab2b6942b7e>:0 
> 12-14 11:34:19.037 I/MonoDroid( 4353): --- End of stack trace from previous location where exception was thrown ---
> 12-14 11:34:19.037 I/MonoDroid( 4353):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <3fd174ff54b146228c505f23cf75ce71>:0 
> 12-14 11:34:19.037 I/MonoDroid( 4353):   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) [0x00000] in <3fd174ff54b146228c505f23cf75ce71>:0 
> 12-14 11:34:19.037 I/MonoDroid( 4353):   at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <61dabd3f0b0446bc8b570d6071d995d7>:0 
> 12-14 11:34:19.037 I/MonoDroid( 4353):   at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <61dabd3f0b0446bc8b570d6071d995d7>:0 
> 12-14 11:34:19.037 I/MonoDroid( 4353):   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <61dabd3f0b0446bc8b570d6071d995d7>:0 
> 12-14 11:34:19.037 I/MonoDroid( 4353):   at (wrapper dynamic-method) System.Object:41cdda5e-06f6-4109-8aa1-ede5dd5a8d48 (intptr,intptr)
> 12-14 11:34:19.174 W/art     ( 4353): JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
> 12-14 11:34:19.190 D/Mono    ( 4353): DllImport searching in: '__Internal' ('(null)').
> 12-14 11:34:19.190 D/Mono    ( 4353): Searching for 'java_interop_jnienv_throw'.
> 12-14 11:34:19.192 D/Mono    ( 4353): Probing 'java_interop_jnienv_throw'.
> 12-14 11:34:19.192 D/Mono    ( 4353): Found as 'java_interop_jnienv_throw'.
> An unhandled exception occured.
> 
> 12-14 11:34:20.937 E/mono    ( 4353): 
> 12-14 11:34:20.937 E/mono    ( 4353): Unhandled Exception:
> 12-14 11:34:20.937 E/mono    ( 4353): System.ArgumentNullException: Value cannot be null.
> 12-14 11:34:20.937 E/mono    ( 4353): Parameter name: map
> 12-14 11:34:20.938 E/mono-rt ( 4353): [ERROR] FATAL UNHANDLED EXCEPTION: System.ArgumentNullException: Value cannot be null.
> 12-14 11:34:20.938 E/mono-rt ( 4353): Parameter name: map

**Comment by jaspervanmegroot** [comment]
I have this issue when rotating the device on Android. Any solutions?

**Comment by jaspervanmegroot** [comment]
I have this issue when rotating the device and back on android. Any solution?

**Comment by MisterJimson** [comment]
@jaspervanmegroot have you tried on the newest betas 5 or 6?

**Comment by jaspervanmegroot** [comment]
@MisterJimson  I am currently on 2.3.0 beta 6

**Comment by amay077** [comment]
We have not received the requested information. 
If you are still experiencing this issue please provide all the requested information and re-open the issue report. 
Thanks!
