### ISSUE TITLE
Android camera update problem

### ISSUE THREAD

**Issue by AcabreraT** [amay077/Xamarin.Forms.GoogleMaps#377]
## BUG / PROBLEM REPORT

I have set everything for a simple example with initial camera update to a fixed position, it is already initialised in every plaform and working smoothly on iOS and UWP, but in Android, loads the map but it does not update the camera position i've tried some workarounds but it keeps loading the map at the ocean (if you zoom out you can see the map) with no camera update at all.

I've tested on different physical devices.
I've tried xaml and code behind both working nice on iOS and UWP.

Is this a known bug ? Anyone had the same problem? I'm doing something wrong? 
I don't post code cause it's quite the same than the example project here.

### VERSIONS

* Xamarin.Forms.GoogleMaps - 2.1.0
* Xamarin.Forms - 2.3.4.270 stable
* 

### PLATFORMS

- [x] Android
- [ ] iOS
- [ ] UWP

### HOW TO REPRODUCE

I'm afraid i can't tell. I'm using 100% examples from your example project, nothing fancy.

**Comment by amay077** [comment]
We have not received the requested information. 
If you are still experiencing this issue please provide all the requested information and re-open the issue report. 
Thanks!
