### ISSUE TITLE
Ground Overlay objects are not shown on map

### ISSUE THREAD

**Issue by idan-rubin** [amay077/Xamarin.Forms.GoogleMaps#378]
### SUMMARY
Ground overlay objects are not shown on map in the PCL types. It does work in the native types.

### VERSIONS

* Xamarin.Forms.GoogleMaps - 2.1.0
* Xamarin.Forms - 2.3.4.270 

### PLATFORMS

- [?] Android
- [x] iOS
- [ ] UWP

### HOW TO REPRODUCE

(Let me show how to reproduce with steps or codes)

```csharp
(Not working)
var satelliteImage = new GroundOverlay()
{
     Icon = BitmapDescriptorFactory.FromStream(new MemoryStream(imageBytesArray)),
     Bounds = new Bounds(new Position(southWest.Lat, southWest.Lon), new Position(northEast.Lat, northEast.Lon)),
      IsClickable = false,
};

//NOT WORKING :( Ground overlay is not shown on map
_googleMap.GroundOverlays.Add(_satelliteImage);

(Working iOS native)
var satelliteImageNative = new Google.Maps.GroundOverlay
{
    Icon = new UIKit.UIImage(Foundation.NSData.FromArray(imageBytesArray)),
    Bounds = new Google.Maps.CoordinateBounds(new CoreLocation.CLLocationCoordinate2D(southWest.Lat, southWest.Lon), new CoreLocation.CLLocationCoordinate2D(northEast.Lat, northEast.Lon)),
    Tappable = false,
    ZIndex = 100,
    Map = _mapView
};
```

### ACTUAL IMAGES

(Let me show your actual problem images/stacktrace. If you want to capture simulator screen to animation GIF, I recomend to [LICEcap](http://www.cockos.com/licecap/).)

![something_image](your_image.png) 

```
// paste stacktrace
```

----

## OTHERS

(free format)

**Comment by amay077** [comment]
Yes it is bug.
Workaround is set ``Transparency`` to ``0`` when after added.

```
_googleMap.GroundOverlays.Add(_satelliteImage);
_satelliteImage.Transparency = 0f;
```

**Comment by edmckee** [comment]
I'm doing the same thing.  Anyway you can share how you are getting your imageBytesArray from a URL.

**Comment by amay077** [comment]
Fixed at https://github.com/amay077/Xamarin.Forms.GoogleMaps/releases/tag/v2.1.1-beta1
