### ISSUE TITLE
Map displays noting in uwp

### ISSUE THREAD

**Issue by ozgblc** [amay077/Xamarin.Forms.GoogleMaps#382]
Hi,
When i use it in uwp , the map displays nothing, just a blue color background  with the +, - buttons.  And with InitialCameraUpdate  it crashes. Am i doing something wrong?

**Comment by amay077** [comment]
You should get Bing Maps API Key - https://developer.xamarin.com/guides/xamarin-forms/user-interface/map/#Windows_Runtime_and_Universal_Windows_Platform .
And set it to ``Xamarin.FormsGoogleMaps.Init(BING_MAPS_API_KEY)`` .

See also:

* https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/master/XFGoogleMapSample/UWP/App.xaml.cs#L67

**Comment by ozgblc** [comment]
thanks for your reply . I got the key and i added the line you say. But the problems occurs when i chose street or terrain as a type.

**Comment by DatSpace** [comment]
I can add my self to the problem as well. After trying to find a solution for some hours I am reporting there has to be a problem :P When was the last time you checked for Bing ? Thanks for your time and this project !!!
PS. I have followed all the steps and have a working token. Btw I think I found a bug as well. In many solutions they propose using the Init() without any token as it should work as well (they claim). If I dont use any token in Init() using your api it crashes with unhandled exceptions. Again thanks 👍

**Comment by amay077** [comment]
FYI:

You should call ``Xamarin.Forms.Forms.Init`` with ``rendererAssemblies`` .
In release mode, If you forgot call it then nothing show map.

https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/master/XFGoogleMapSample/UWP/App.xaml.cs#L62-L66
