### ISSUE TITLE
Pin Click Event - Detect right-click

### ISSUE THREAD

**Issue by btidoug** [amay077/Xamarin.Forms.GoogleMaps#383]
Is there a way to detect if a pin click was performed by the right mouse button?  I have a need to select multiple pins and then do some processing on the selected pins in the model.  I'd like to still have functionality of left-click and showing info window.

----
### SUMMARY

(write summary of your feature request or suggestion)

### DETAILS

(write details/usecases with text, codes and images)

```
// usage of your requested feature to use
```

### PLATFORMS

which platform do you want?

- [x] Android
- [ ] iOS
- [ ] UWP

----
### SUMMARY

(write summary of your bug report.)

### VERSIONS

* Xamarin.Forms.GoogleMaps - 2.1.0
* Xamarin.Forms - 2.3.4.270
* Xamarin.Forms.GoogleMaps.Bindings - 2.1.0

### PLATFORMS

- [ ] Android
- [x] iOS
- [ ] UWP

### HOW TO REPRODUCE

(Let me show how to reproduce with steps or codes)

1. 
2. 
3. 

```csharp
// code for reproduce
```

### ACTUAL IMAGES

(Let me show your actual problem images/stacktrace. If you want to capture simulator screen to animation GIF, I recomend to [LICEcap](http://www.cockos.com/licecap/).)

![something_image](your_image.png) 

```
// paste stacktrace
```

----

## OTHERS

(free format)

**Comment by deextercz** [comment]
Can you explain how do you want make a mouse click on mobile platform?

**Comment by btidoug** [comment]
Oh my gosh!!!  I'm so sorry!  I have been literally heads down in development mode for 12 hours and working with the emulator and my mouse.  You're right - there is no right-click.  Wow! 

Please disregard!
