### ISSUE TITLE
Initial location question

### ISSUE THREAD

**Issue by btidoug** [amay077/Xamarin.Forms.GoogleMaps#384]
How do you set the base location to something other than Rome?  My app has a filter page that allows user to filter some lat/lon data and then display that data on the map as pins.  All that works great, but the map always defaults to Rome and I have to zoom out, scroll, etc to go find the pins and then zoom in.  

Can the base location be some calculation of all the pins and zoom levels set so all pins are centered and on the screen at once?

----
### SUMMARY

(write summary of your feature request or suggestion)

### DETAILS

(write details/usecases with text, codes and images)

```
// usage of your requested feature to use
```

### PLATFORMS

which platform do you want?

- [x] Android
- [ ] iOS
- [ ] UWP

----
### SUMMARY

(write summary of your bug report.)

### VERSIONS

* Xamarin.Forms.GoogleMaps - x.x.x
* Xamarin.Forms - x.x.x
* 

### PLATFORMS

- [ ] Android
- [x] iOS
- [ ] UWP

### HOW TO REPRODUCE

(Let me show how to reproduce with steps or codes)

1. 
2. 
3. 

```csharp
// code for reproduce
```

### ACTUAL IMAGES

(Let me show your actual problem images/stacktrace. If you want to capture simulator screen to animation GIF, I recomend to [LICEcap](http://www.cockos.com/licecap/).)

![something_image](your_image.png) 

```
// paste stacktrace
```

----

## OTHERS

(free format)

**Comment by AcabreraT** [comment]
interested too

**Comment by amay077** [comment]
You can use ``Map.InitialCameraUpdate`` in XAML or ``xxx.xaml.cs``.

* XAML -
 https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/master/XFGoogleMapSample/XFGoogleMapSample/BasicMapPage.xaml#L217
* CS - https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/master/XFGoogleMapSample/XFGoogleMapSample/Shapes2Page.xaml.cs#L69

**Comment by btidoug** [comment]
I tried the XAML one and was getting run-time errors.

 `<googleMaps:Map MapType="Hybrid" InitialCameraUpdate="42.96, -85.67, 13, 30, 60" IsIndoorEnabled="True" MyLocationEnabled="true" ... `

**Comment by amay077** [comment]
Yes, I just fixed #379 and release v2.1.1-beta2 .

Please try https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/2.1.1-beta2 .

**Comment by btidoug** [comment]
That fixed it!  Thanks

**Comment by btidoug** [comment]
Is the InitialCameraUpdate bindable?

**Comment by amay077** [comment]
``Map.InitialCameraUpdate`` is bindable property but it only get when page shown.

**Comment by btidoug** [comment]
What about using the sister project ... Xamarin.Forms.GoogleMaps.Bindings?  I just think it is weird not being able to set a default location for the map on initial showing of the page.

**Comment by amay077** [comment]
Xamarin.Forms.GoogleMaps.Bindings is support library for this.
But it does not full-support Xamarin.Forms.GoogleMaps features.
