### ISSUE TITLE
Marker opacity

### ISSUE THREAD

**Issue by deextercz** [amay077/Xamarin.Forms.GoogleMaps#386]
Please implement marker opacity

----
### SUMMARY

Google maps api supports opacity for marker
https://developers.google.com/maps/documentation/android-api/marker
https://developers.google.com/maps/documentation/ios-sdk/marker#change_the_marker_opacity

### DETAILS

Probably it is possible to implement this for UWP 
http://igrali.com/2012/02/04/bing-maps-data-bound-pushpins-fade-in-animation/
https://msdn.microsoft.com/en-us/library/hh709044.aspx

But I am not sure.

### PLATFORMS

which platform do you want?

- [x] Android
- [x] iOS
- [x] UWP

**Comment by amay077** [comment]
Added ``Pin.Transparency`` property in [v2.1.1-beta4](https://github.com/amay077/Xamarin.Forms.GoogleMaps/releases/tag/v2.1.1-beta4) .

Also added sample for it - https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/v2.1.1-beta4/XFGoogleMapSample/XFGoogleMapSample/CustomPinsPage.xaml.cs#L175 .

![simulator screen shot - iphone 8 - 2017-10-01 at 16 54 44](https://user-images.githubusercontent.com/401369/31052787-5305d3c0-a6c9-11e7-841b-2c5619bccc90.png)
