### ISSUE TITLE
How to FitMapRegionToPositions - show all Pins

### ISSUE THREAD

**Issue by eopeter** [amay077/Xamarin.Forms.GoogleMaps#389]
I cannot find a way to show all pins at once on the map. Any help is appreciated

**Comment by amay077** [comment]
You can use ``Bounds.FromPositions`` and ``Bounds.Including``, these methods inflates region from position(s).
And call ``Map.InitialCameraUpdate`` or ``Map.MoveCamera`` with ``CameraUpdateFactory.NewBounds(bounds, padding)`` to fit map region to bounds.

https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/v2.1.1-beta4/XFGoogleMapSample/XFGoogleMapSample/Shapes2Page.xaml.cs#L55-L69

**Comment by eopeter** [comment]
Awesome!!! Thanks
