### ISSUE TITLE
Traffic under polyline

### ISSUE THREAD

**Issue by eopeter** [amay077/Xamarin.Forms.GoogleMaps#390]
How can I put traffic above polyline?

**Comment by amay077** [comment]
You can see traffic layer by ``IsTrafficeEnabled`` but can not get as polyline.

**Comment by deextercz** [comment]
@amay077 I think that @eopeter wants change Z-index of traffic but I think it is not possible.

**Comment by amay077** [comment]
Yes you're right!
We can't change Z-Index of traffic map.
