### ISSUE TITLE
Need to convert GoogleMaps PCL to .NetStandard

### ISSUE THREAD

**Issue by JKennedy24** [amay077/Xamarin.Forms.GoogleMaps#394]
Need to convert the PCL library to a .Net Standard Library

https://oren.codes/2017/04/23/using-xamarin-forms-with-net-standard-vs-2017-edition/

**Comment by amay077** [comment]
I think no need .NET Standard in Xamarin.Forms.GoogleMaps now.
Because this is for "Google Maps" and Google Maps supports only Android and iOS.

I can't see some advantage for support .NET Standard in Xamarin.Forms.GoogleMaps .

**Comment by amay077** [comment]
This is duplicate.
Let's join to #355
