### ISSUE TITLE
Update Google Key after Init

### ISSUE THREAD

**Issue by aherrick** [amay077/Xamarin.Forms.GoogleMaps#395]
## OTHERS

How can I update the Google Key after Init? My key might change depending on who is using the App.

**Comment by amay077** [comment]
No you can't. Because Google Maps Android API needs api key in ``AndroidManifest.xml`` .

* [Get API Key  |  Google Maps Android API  |  Google Developers](https://developers.google.com/maps/documentation/android-api/signup)

If you change the API key, you should restart apps.

**Comment by aherrick** [comment]
Thanks for the response. I have no problem restarting the App, but I can't hard code the key in the Android Manfiest. How do I update the key dynamically?

**Comment by amay077** [comment]
I understand you said.
Yes you are right, it is impossible because API key needs const.
We should change API key and re-build, re-deploy my apps. :fearful:
