### ISSUE TITLE
Pin Drag not working

### ISSUE THREAD

**Issue by viscardo** [amay077/Xamarin.Forms.GoogleMaps#397]
Hello,
I love you plugin but and I am very advance on my project using Xamarin.Forms.GoogleMaps.

Now I have to make the pin draggable and unfortunately it is not working :(
### SUMMARY

I cant drag it on IOS and Android. 
It seems when I click and drag the Pin, it drags the whole map, but the pin is still stucking at the same position.

I lost my saturday trying to find a solution but I does not drag.

### VERSIONS

* Xamarin.Forms.GoogleMaps - 2.1.1
* Xamarin.Forms -2.4.0.18342
* 

### PLATFORMS

- [X] Android
- [x] iOS
- [X] UWP

### HOW TO REPRODUCE

below my code:

			Pin pPin = new Pin()
			{
				Type = PinType.SavedPin,
				Label = "Teste",
				Position = newPosition,
				Tag = "1",
				IsDraggable = true
			};

			MyMap.Pins.Clear();
			MyMap.Pins.Add(pPin);
			MyMap.SelectedPin = pPin;

**Comment by viscardo** [comment]
Sorry, forget about the issue.
I just realized on the simulator you need to click and hold it for a while to start drag.

**Comment by amay077** [comment]
Yes! You should hold pin when to start dragging. 👍
