### ISSUE TITLE
Direct assign 'MyLocationButtonEnabled' value / result = no show

### ISSUE THREAD

**Issue by maniti** [amay077/Xamarin.Forms.GoogleMaps#400]
# BUG / PROBREM REPORT

### SUMMARY
Directly assign value, result map itself never show the my location button.

### VERSIONS
Xamarin.Forms.GoogleMaps = 2.2.0

### PLATFORMS
- [x] iOS

### HOW TO REPRODUCE
1. Your sample solution / on BasicMapPage.xsml.cs / comment out all code 
(from the comment marker '// MyLocationButtonEnabled' about line#65 until the end.)
`
            // MyLocationButtonEnabled
            switchMyLocationButtonEnabled.Toggled += (sender, e) =>
            {
                map.UiSettings.MyLocationButtonEnabled = e.Value;
            };
            switchMyLocationButtonEnabled.IsToggled = map.UiSettings.MyLocationButtonEnabled;
`

2. Put on below line of code instead
`map.UiSettings.MyLocationButtonEnabled = true;`

3. My result the my location button never show.

**Comment by amay077** [comment]
Thank you for reporting.
It seem same as #371 .
I will fix it soon. 👍

**Comment by amay077** [comment]
I fixed this issue in [v2.2.1-beta1](https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/2.2.1-beta1) .
Could you try?

**Comment by kingnguyen1993** [comment]
Fix n Android? I just test, and it's still not shown.

**Comment by deextercz** [comment]
I can confirm also and even my position is not displayed.

**Comment by amay077** [comment]
I can see location button on iOS by below code with v2.2.1-beta1 and XFGoogleMapsSample.

```
    public partial class BasicMapPage : ContentPage
    {
        public BasicMapPage()
        {
            InitializeComponent();

            map.UiSettings.MyLocationButtonEnabled = true;
        }
    }
```

![image](https://user-images.githubusercontent.com/401369/32152245-204d0c1a-bd66-11e7-93a7-d5c813f51536.png)

**Comment by deextercz** [comment]
A was testing on android emulator and it is not showing with the same code

**Comment by amay077** [comment]
Thanks. I reproduced it. (I didn't run on Android because this issue is about iOS side)

> A was testing on android emulator and it is not showing with the same code

This issue has 2 reasons.

1. Design of GoogleMaps Android API - We should set **``Map.MyLocationEnabled = true``** and  ``UiSettings.MyLocationButtonEnabled = true`` for display location button.
2. Bug - ``Map.MyLocationEnabled = true`` in page constructor is not worked. This is my bug.

### Conclusion

Add ``map.MyLocationEnabled = true`` in your page constructor.
And wait for next version(v2.2.1-beta2).

    public partial class BasicMapPage : ContentPage
    {
        public BasicMapPage()
        {
            InitializeComponent();

            map.MyLocationEnabled = true;  // <-- added
            map.UiSettings.MyLocationButtonEnabled = true;
        }
    }

**Comment by maniti** [comment]
Dear @amay077 
thanks for your afford, v2.2.1-beta2 works fine.

**Comment by amay077** [comment]
I released [v2.2.1-beta2](https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/2.2.1-beta2).
Could you try this?

**Comment by maniti** [comment]
@amay077 v2.2.1-beta2 = working fine

**Comment by Jatsai** [comment]
Is this bug closed?

**Comment by amay077** [comment]
Yes, it's closed.

**Comment by rayita** [comment]
@amay077  last version (2.2.1) MyLocationEabled works in Android but not in iOS (no blue dot, and no certer if you tap in MyLocationButton)
