### ISSUE TITLE
App Crashing

### ISSUE THREAD

**Issue by aparun22** [amay077/Xamarin.Forms.GoogleMaps#402]
After add dll from nuget package app crashing. I am using xamarin forms cross platform. 
When run android app as soon as app launch its closing without any error prompt.

If i add Google api key and package name only its not deploying to emulator  else it opens up without Map

Thanks,
Arun.

**Comment by amay077** [comment]
[Please show me more informations and how to reproduce.](https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/master/ISSUE_TEMPLATE.md)

**Comment by aparun22** [comment]
[Maps.zip](https://github.com/amay077/Xamarin.Forms.GoogleMaps/files/1429374/Maps.zip)

I have uploaded sample project to re-produce the issue. I used VS2017 to develop my project. I as soon as i assign the package name in my google console project not deployed to emulator. 

Thanks,
Arun
