### ISSUE TITLE
How to display a 'blue dot' of the current position?

### ISSUE THREAD

**Issue by maniti** [amay077/Xamarin.Forms.GoogleMaps#403]
### SUMMARY
How to display a 'blue dot' of the current position?

### VERSIONS
* Xamarin.Forms.GoogleMaps - 2.2.1-beta1

### PLATFORMS
- [x] iOS

### HOW TO REPRODUCE
1. By testing the sample solutions / iOS / BasicMapPage

2. Once we click on the My Location Button we can't see the blue-dot 
(as shows on Google Map via browser) ![googlemap-bluedot](https://user-images.githubusercontent.com/5965867/32168452-4ac331b6-bd9f-11e7-97b3-d3765a90de8c.jpg)

3. The sample screen on iOS 
![googlemap-ios-emu-screen](https://user-images.githubusercontent.com/5965867/32168477-5fe80c42-bd9f-11e7-800f-151ff8878a7e.jpg)

**Comment by deextercz** [comment]
Yhis is a bug reported here: https://github.com/amay077/Xamarin.Forms.GoogleMaps/issues/371 please wait for new version.

**Comment by amay077** [comment]
I released [v2.2.1-beta2](https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/2.2.1-beta2).

And you should call ``Map.MyLocationEnabled = true``.
Could you try below code with v2.2.1-beta2?

```
public partial class BasicMapPage : ContentPage
{
    public BasicMapPage()
    {
        InitializeComponent();

        map.MyLocationEnabled = true;  // <-- added
        map.UiSettings.MyLocationButtonEnabled = true;
    }
}
```

**Comment by deextercz** [comment]
![capture](https://user-images.githubusercontent.com/23039506/32197232-b46bbda8-bdc3-11e7-94f7-ce1ca57fea14.PNG)
Still it is not working for me even with v2.2.1-beta2.

**Comment by kingnguyen1993** [comment]
Try add MyLocationEnabled = "true" in Xaml.

**Comment by amay077** [comment]
@deextercz ,
I can not reproduced.
I added below code in XFGoogleMapSample, works fine.

```
// CustomMap.cs
using System;

namespace XFGoogleMapSample
{
    public class CustomMap : Xamarin.Forms.GoogleMaps.Map
    {
        public CustomMap()
        {
            MyLocationEnabled = true;
            UiSettings.MyLocationButtonEnabled = true;
        }
    }
}
```

```
// BasicMapPage.xml
<?xml version="1.0" encoding="UTF-8"?>

<ContentPage
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:cmaps="clr-namespace:XFGoogleMapSample;assembly=XFGoogleMapSample"
    x:Class="XFGoogleMapSample.BasicMapPage"
    Title="BasicMap">
    <ContentPage.Content>
        <cmaps:CustomMap x:Name="map"
                  InitialCameraUpdate="-23.68, -46.87, 13, 30, 60"
                  VerticalOptions="FillAndExpand" />
    </ContentPage.Content>
</ContentPage>
```

```
// BasicMapPage.xml.cs
using System;
using System.Collections.Generic;
using System.Linq;

using Xamarin.Forms;
using Xamarin.Forms.GoogleMaps;

namespace XFGoogleMapSample
{
    public partial class BasicMapPage : ContentPage
    {
        public BasicMapPage()
        {
            InitializeComponent();
        }
    }
}
```

![image](https://user-images.githubusercontent.com/401369/32222116-5d2592f4-be7b-11e7-8817-5da3e0b76999.png)

**Comment by deextercz** [comment]
Probably it was in some cache, now it is working.

**Comment by maniti** [comment]
I tried on both on code and xaml = the blue-dot won't show either.

Dear @deextercz //cache? how?

**Comment by deextercz** [comment]
Clean solution helped me to make it works

**Comment by maniti** [comment]
Not yet testing with the new solution suggested by @deextercz:

Tested on either my solution & sample solutions / iOS / BasicMapPage = still not working

**Comment by deextercz** [comment]
@maniti could you try Android ?

**Comment by maniti** [comment]
@deextercz : will test / thanks

**Comment by rayita** [comment]
@amay077  last version (2.2.1) MyLocationEabled works in Android but not in iOS (no blue dot, and no certer if you tap in MyLocationButton)

**Comment by GorAbelyan** [comment]
@amay077 dear I use 4.0.0.0 beta … on my xamarin Ios project … when pin and blue dot on same postion  pin click event doesn’t fire …


And I Have issues also on IOS clustering I use clustering nuget 1.1.0.  On android its work fine but on ios it also doesn’t work can you help me ..



thanks a lot.
