### ISSUE TITLE
Zoom control won't show

### ISSUE THREAD

**Issue by maniti** [amay077/Xamarin.Forms.GoogleMaps#404]
### SUMMARY
Zoom control won't show even we have enabled.

### VERSIONS
Xamarin.Forms.GoogleMaps - 2.2.1-beta1

### PLATFORMS
(test only on iOS Emu)
- [x] iOS

### HOW TO REPRODUCE
1. By testing the sample solutions / iOS / BasicMapPage
2. Once we click on the 'ZoomControls Enable' button, the control itself won't show up.
![googlemap-zoomcontrol](https://user-images.githubusercontent.com/5965867/32168759-62d6b2ea-bda0-11e7-9bc8-1deb23df029c.jpg)

**Comment by amay077** [comment]
This is not worked on iOS because GoogleMaps iOS SDK does not support it.
