### ISSUE TITLE
Android fragments overlapping ?

### ISSUE THREAD

**Issue by AntonioCabreraTornero** [amay077/Xamarin.Forms.GoogleMaps#414]
Hello, suddenly our maps are overlapping in a strange way in Android. (Image below)
I say strange way cause the little zoomed map you can see overlaped on the big one, is from the previous page of navigation.

What could be causing this issue?
Has someone found this stone on his way? 
I would apreciate any advice on this one!

![screenshot-1510653215231](https://user-images.githubusercontent.com/20106560/32773394-50f4f304-c929-11e7-9fac-d57b5c47d091.jpg)

**Comment by AntonioCabreraTornero** [comment]
No one has faced this issue?

**Comment by amay077** [comment]
Yes I have never seen this issue.
Could you make simple apps for reproduce it?

**Comment by AntonioCabreraTornero** [comment]
Ok, good news... it got solved after raising the target sdk from 12 to 14, i'm not sure how it got downgraded, but well... everything's in place now.
