### ISSUE TITLE
Overlapping Marker Spiderfier in Xamarin.Forms.GoogleMaps

### ISSUE THREAD

**Issue by carvah** [amay077/Xamarin.Forms.GoogleMaps#426]
## FEATURE REQUEST / SUGGESTION

I was in need of a feature that Google Earth has when there are multiple markers near the same location you are able to click on that marker and it expands. 

### SUMMARY

Basically, this feature would make us able to click on a master pin that would expand if it had children inside him.

### IDEA TAKEN FROM

https://github.com/jawj/OverlappingMarkerSpiderfier

https://github.com/leaflet/Leaflet.markercluster/

### PLATFORMS

which platform do you want?

- [x] Android
- [x] iOS
- [ ] UWP

**Comment by Maxikq** [comment]
+1

**Comment by amay077** [comment]
We called it "Marker Clustering".
please vote to #123
