### ISSUE TITLE
Crash Android loading pin in map

### ISSUE THREAD

**Issue by cacaxiq** [amay077/Xamarin.Forms.GoogleMaps#427]
(This is template for issue. Please choose from feature request or bug report or others then write.
If you need realtime communication then you can join our [gitter room](https://gitter.im/Xamarin-Forms-GoogleMaps/public).)

----
### SUMMARY

I am getting the error described in the details when I load pins while browsing the map.

### DETAILS

System.NullReferenceException: Object reference not set to an instance of an object.
11-28 17:40:05.247 I/MonoDroid(14604):   at System.Collections.Generic.LinkedList`1[T].InternalRemoveNode (System.Collections.Generic.LinkedListNode`1[T] node) [0x00012] in <6c708cf596db438ebfc6b7e012659eee>:0 
11-28 17:40:05.247 I/MonoDroid(14604):   at System.Collections.Generic.LinkedList`1[T].Remove (T value) [0x0000b] in <6c708cf596db438ebfc6b7e012659eee>:0 
11-28 17:40:05.247 I/MonoDroid(14604):   at Xamarin.Forms.GoogleMaps.Android.Utils+<>c__DisplayClass6_0.<ConvertViewToBitmapDescriptor>b__0 () [0x0007d] in <3360f919a0e147cb91edbab1f2c1be66>:0 
11-28 17:40:05.247 I/MonoDroid(14604):   at System.Threading.Tasks.Task`1[TResult].InnerInvoke () [0x0000f] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
11-28 17:40:05.247 I/MonoDroid(14604):   at System.Threading.Tasks.Task.Execute () [0x00010] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
11-28 17:40:05.247 I/MonoDroid(14604): --- End of stack trace from previous location where exception was thrown ---
11-28 17:40:05.247 I/MonoDroid(14604):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
11-28 17:40:05.247 I/MonoDroid(14604):   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
11-28 17:40:05.247 I/MonoDroid(14604):   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
11-28 17:40:05.247 I/MonoDroid(14604):   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
11-28 17:40:05.247 I/MonoDroid(14604):   at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
11-28 17:40:05.247 I/MonoDroid(14604):   at Xamarin.Forms.GoogleMaps.Logics.Android.PinLogic+<TransformXamarinViewToAndroidBitmap>d__24.MoveNext () [0x001e3] in <3360f919a0e147cb91edbab1f2c1be66>:0 
11-28 17:40:05.247 I/MonoDroid(14604): --- End of stack trace from previous location where exception was thrown ---
11-28 17:40:05.247 I/MonoDroid(14604):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
11-28 17:40:05.247 I/MonoDroid(14604):   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) [0x00000] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
11-28 17:40:05.247 I/MonoDroid(14604):   at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <e975227ac8644a30bb0866117325de0d>:0 
11-28 17:40:05.247 I/MonoDroid(14604):   at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <e975227ac8644a30bb0866117325de0d>:0 
11-28 17:40:05.247 I/MonoDroid(14604):   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <e975227ac8644a30bb0866117325de0d>:0 
11-28 17:40:05.247 I/MonoDroid(14604):   at (wrapper dynamic-method) System.Object:0b0515df-cbe9-4869-b6ef-f0e81c9b41d0 (intptr,intptr)
11-28 17:40:05.280 W/zygote  (14604): JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable

```
// usage of your requested feature to use
```

### PLATFORMS

which platform do you want?

- [x] Android
- [ ] iOS
- [ ] UWP

**Comment by amay077** [comment]
Could you tell me how to reproduce?
Do you use ``Task<T>`` or ``async/await`` ?

**Comment by cacaxiq** [comment]
Hello,

I am trying to find a scenario to reproduce the error, but it is very intermittent.

My scenario is that I have to present many pins on the screen. When the user zooms too far, more than 500 pins can be plotted on the map. In the process of loading the pins I use an ObservableCollection of Pins and let the Xamarin.Forms.GoogleMaps.Bindings plot on the screen of the mobile.

I do not use any Task <T> or async / await to insert or remove pins / polygons. When I was doing the async process it was always necessary to use the Device.MainOnThread.

**Comment by ormedo** [comment]
ObservableCollection needs to change always on the Main Thread, So Device.MainOnThread. Its needed.

**Comment by cacaxiq** [comment]
@ormedo Device.MainOnThread has not been used. I believe it's because of XFG.Bindings

**Comment by philmoz** [comment]
I'm also seeing this on Android. A large number of pins can cause a crash, as can refreshing/rebuilding the list of pins.

I suspect the problem is in the ConvertViewToBitmapDescriptor method of Utils.cs. This runs each bitmap convert in a new task; but the lruTracker list does not appear to be used in a thread-safe manner.

So far I have not been able to reproduce the crash if I comment out the code that uses the 'lruTracker' and and 'cache' properties.

**Comment by amay077** [comment]
We have not received the requested information. 
If you are still experiencing this issue please provide all the requested information and re-open the issue report. 
Thanks!
