### ISSUE TITLE
Implement UWP TakeSnapshot

### ISSUE THREAD

**Issue by DavidPressman** [amay077/Xamarin.Forms.GoogleMaps#429]
### SUMMARY

In UWP the awaitable TakeSnapshot() function always returns null;

### VERSIONS

* Xamarin.Forms.GoogleMaps - 2.2.1
* Xamarin.Forms - 2.5.0.91635
* 

### PLATFORMS

- [ ] Android
- [ ] iOS
- [x] UWP

### HOW TO REPRODUCE

(Let me show how to reproduce with steps or codes)

1. Display Map using Bing Service for the UWP project. Works as expected.
2. Execute await map.TakeSnapshot();
3. Function returns null every time;

pcl csharp xaml.cs code segment (vm is the view model) -- works fine in Android and iOS, but not in UWP:

        private void SaveButton_Clicked(object sender, EventArgs e)
        {
            if (saving) return;
            saving = true;
            StoreBytes();
        }

        private async void StoreBytes()
        {
            try
            {
                var stream = await MyMap.TakeSnapshot();
                if (stream == null) throw new Exception("Map Not Saved, but co-ordinates can be used to re-create.");
                using (MemoryStream ms = new MemoryStream())
                {
                    stream.CopyTo(ms);
                    vm.MapBytes = ms.ToArray();
                }
            }
            catch (Exception e)
            {
                Dialogs.UserDialogs.Instance.Alert(e.Message);
            }
            vm.SaveCmd();
        }

**Comment by amay077** [comment]
Sorry, I don't know how to take screenshot by Bing Maps SDK.

**Comment by DavidPressman** [comment]
Understood. Perhaps there is a way. I'm retired and have some time to investigate. If I find a way I'll certainly let you know.


David Pressman


________________________________
