### ISSUE TITLE
Does not work with Xamarin.Google.iOS.Maps version 2.4.0 or later

### ISSUE THREAD

**Issue by philmoz** [amay077/Xamarin.Forms.GoogleMaps#432]
### SUMMARY

Xamarin.Forms.GoogleMaps no longer works if the Xamarin.Google.iOS.Maps plugin is updated to version 2.4.0 or 2.5.0. The app hangs and no map page is displayed.

### VERSIONS

* Xamarin.Forms.GoogleMaps - 2.2.1 (also tried 2.3.0-beta2)
* Xamarin.Forms - 2.5.0.121934
* Xamarin.Google.iOS.Maps - 2.4.0 or 2.5.0

### PLATFORMS

- [ ] Android
- [x] iOS
- [ ] UWP

### HOW TO REPRODUCE

Can be seen in the sample app 'XFGoogleMapSample'.
Update the version of Xamarin.Google.iOS.Maps in the project to 2.4.0 or 2.5.0.
Run the app (iOS) and click on 'Basic Map' button.

**Comment by amay077** [comment]
I just released Xamarin.Forms.GoogleMaps [v2.3.0-beta3](https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/2.3.0-beta3) that resolved this issue.

Notice: Now your apps requires Xamarin.Google.iOS.Maps.2.5.0 .

**Comment by galadril** [comment]
can confirm that it's fixed on beta 3
