### ISSUE TITLE
iOS App crash on page load Xamarin.Google.iOS.Maps - 2.5.0

### ISSUE THREAD

**Issue by soile1991** [amay077/Xamarin.Forms.GoogleMaps#433]
### SUMMARY

App crashes 

### VERSIONS

* Xamarin.Forms.GoogleMaps - 2.2.1
* Xamarin.Forms - 2.5.0.121934
* Xamarin.Google.iOS.Maps - 2.5.0

### PLATFORMS

- [ ] Android
- [x] iOS
- [ ] UWP

### HOW TO REPRODUCE

(Let me show how to reproduce with steps or codes)

1. just open a page with a map

## Got this error 

Attempting to JIT compile method 'Xamarin.Forms.GoogleMaps.iOS.MapRenderer:UpdateMapType ()' while running in aot-only mode. See https://developer.xamarin.com/guides/ios/advanced_topics/limitations/ for more information.

**Comment by amay077** [comment]
I just released Xamarin.Forms.GoogleMaps [v2.3.0-beta3](https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/2.3.0-beta3) that resolved this issue.

Notice: Now your apps requires Xamarin.Google.iOS.Maps.2.5.0 .

**Comment by galadril** [comment]
can confirm that it's fixed on beta 3

**Comment by soile1991** [comment]
yeah it works on Xamarin.Forms.GoogleMaps v2.3.0-beta3 with Xamarin.Google.iOS.Maps.2.5.0.

thank you @amay077
