### ISSUE TITLE
Some of UiSettings not working

### ISSUE THREAD

**Issue by cbagpipe** [amay077/Xamarin.Forms.GoogleMaps#437]
### SUMMARY

subj and screenshots are self-describing.

### VERSIONS

* Xamarin.Forms.GoogleMaps - 2.2.1
* Xamarin.Forms - 2.5.0.121934

### PLATFORMS

- [x] Android

### HOW TO REPRODUCE

```csharp
// code for reproduce
map = new Map
            {
                VerticalOptions = LayoutOptions.Fill,
                HorizontalOptions = LayoutOptions.Fill,
                IsIndoorEnabled = false,
                IsTrafficEnabled = false,
                //HasRotationEnabled = false,
                //HasScrollEnabled = false,
                //HasZoomEnabled = false,
                //IsShowingUser = false,
                MapType = MapType.Street,
                InitialCameraUpdate = camera,
            };
map.UiSettings.CompassEnabled = false;
map.UiSettings.IndoorLevelPickerEnabled = false;
map.UiSettings.MyLocationButtonEnabled = false;
map.UiSettings.RotateGesturesEnabled = false;
map.MyLocationEnabled = false;
map.UiSettings.ScrollGesturesEnabled = false;
map.UiSettings.TiltGesturesEnabled = false;
map.UiSettings.ZoomControlsEnabled = false;
map.UiSettings.ZoomGesturesEnabled = false;
```

### ACTUAL IMAGES

![debug shot](https://user-images.githubusercontent.com/22903809/33922428-899af72c-e016-11e7-8c89-f66e6add1e91.jpg)
![map shot](https://user-images.githubusercontent.com/22903809/33922523-1732d5dc-e017-11e7-8a95-20c83b3e54ab.jpg)

**Comment by amay077** [comment]
Hum,,, I can't see your behavior.

I tried reproduce in [issue_437 branch](https://github.com/amay077/Xamarin.Forms.GoogleMaps/tree/issue_437/XFGoogleMapSample) but I looks like works fine.

![screenshot_1513183306](https://user-images.githubusercontent.com/401369/33950846-c1fb5936-e070-11e7-9439-adc93af5d28d.png)

Could you reproduce in [issue_437 branch](https://github.com/amay077/Xamarin.Forms.GoogleMaps/tree/issue_437/XFGoogleMapSample)?

**Comment by cbagpipe** [comment]
Ok, I see the difference. You SDK version is 7.0 (vs 7.1 of my) and xamarin.android.support.* packages versions differs (25.1.0 vs 25.4.0.2 of my). With your configuration really no problem. Updated my project and problem gone. But can you check with my build settings and nuget versions?

**Comment by amay077** [comment]
I updated MonoAndroid to 7.1 and xamarin.android.support.*  to 25.4.0.2. -
 https://github.com/amay077/Xamarin.Forms.GoogleMaps/commit/ea9a368b4b3c8501a847ec2360cf4af1c173430f

But I can't reproduce it yet.

Could you give me small solution for repro.

**Comment by cbagpipe** [comment]
Hmmm, now I can't reproduce it too. Ghost Bug? Think you may close this issue. Thanks)
