### ISSUE TITLE
[FEATURE REQUEST] Custom Information Window

### ISSUE THREAD

**Issue by JMNewsome** [amay077/Xamarin.Forms.GoogleMaps#438]
### SUMMARY

I am curious when a rough ETA might be mentioned about implementing custom information windows. I have scanned through and saw that it was implemented in another issue report, What is a reasonable estimation when it will be officially support within this project? Thank you for all you have done for this alternative to the default xamarin implementation. It is the backbone to my app, the next big step would be having the ability to customize the information window to fit my app's design style

### PLATFORMS

which platform do you want?

- [x] Android
- [x] iOS
- [ ] UWP

**Comment by amay077** [comment]
Duplicate with https://github.com/amay077/Xamarin.Forms.GoogleMaps/issues/70 .
Please any comment or post 👍  in #70 .
