### ISSUE TITLE
Circles always under groundoverlays, ignores ZIndex

### ISSUE THREAD

**Issue by edmckee** [amay077/Xamarin.Forms.GoogleMaps#441]
### SUMMARY
We are attempting to add circles over the groundoverlays.  We are utilizing the zIndex and have tried changing the order in which they're added. 

### VERSIONS

* Xamarin.Forms.GoogleMaps - 2.3.0-beta5
* Xamarin.Forms - 2.3.4.247

### PLATFORMS

- [x] Android
- [x] iOS
- [ ] UWP

### HOW TO REPRODUCE

The below snippet was added to the PinsPage.xaml.cs in the demo project.  We are expecting the circle to cover the image in the overlay, but the overlay is always on top.

```csharp
                map.Circles.Add(new Circle()
                {
                    Center = new Position(40.7808d, -73.961d),
                    FillColor = Color.Red,
                    Radius = new Distance(100),
                    ZIndex = 3,
                });

                var _overlay = new GroundOverlay()
                {
                    Bounds = new Bounds(new Position(40.781d, -73.961d), new Position(40.782d, -73.962d)),
                    Icon = BitmapDescriptorFactory.FromBundle("image01.png"),
                    Tag = "THE GROUNDOVERLAY",
                    ZIndex = 2
                };

                map.GroundOverlays.Add(_overlay);
```

### ACTUAL IMAGES

```
![untitled 4](https://user-images.githubusercontent.com/349146/34140075-e80daa18-e43d-11e7-8369-7e531185781d.png)

// paste stacktrace
```

----

## OTHERS

(free format)

**Comment by amay077** [comment]
I seems works fine.

![2017-12-19 22 06 49](https://user-images.githubusercontent.com/401369/34158488-ffc7f12e-e508-11e7-9e22-e8ff37faad11.png)

```csharp
map.Pins[0].ZIndex = 11;
map.Polylines[0].ZIndex = 10;
map.Polylines[1].ZIndex = 9;
map.Polylines[2].ZIndex = 8;
map.Circles[0].ZIndex = 7;
map.Circles[1].ZIndex = 6;
map.Circles[2].ZIndex = 5;
map.Polygons[0].ZIndex = 4;
map.Polygons[1].ZIndex = 3;
map.Polygons[2].ZIndex = 2;
map.GroundOverlays[0].ZIndex = 1;
```

![2017-12-19 22 06 55](https://user-images.githubusercontent.com/401369/34158530-2a9b7e0c-e509-11e7-8cce-bee098b2596a.png)

```csharp
map.Pins[0].ZIndex = 1;
map.Polylines[0].ZIndex = 2;
map.Polylines[1].ZIndex = 3;
map.Polylines[2].ZIndex = 4;
map.Circles[0].ZIndex = 5;
map.Circles[1].ZIndex = 6;
map.Circles[2].ZIndex = 7;
map.Polygons[0].ZIndex = 8;
map.Polygons[1].ZIndex = 9;
map.Polygons[2].ZIndex = 10;
map.GroundOverlays[0].ZIndex = 11;
```

**Comment by amay077** [comment]
But I found a bug that ``ZIndex`` not working when ``GroundOverlays.Add``(also ``Polygons.Add``, ``Polylines.Add`` and ``Circles.Add``).

```csharp
overlay.ZIndex = 7;
map.GroundOverlays.Add(overlay);  // ZIndex not works

overlay.ZIndex = 6; // working
```

**Comment by amay077** [comment]
Fixed at https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/master/RELEASE_NOTES.md#230-beta6 .
