### ISSUE TITLE
Native map is throwing null exception in iOS custom renderer

### ISSUE THREAD

**Issue by Abhiprao** [amay077/Xamarin.Forms.GoogleMaps#446]
Im trying to custom renderer the map in iOS and all Im getting is null reference exception from line(var nativeMap = Control as MKMapView) saying that native map is null.Please can anyone one give me a good solution for this and below is my code, The map which I use is google map.

[assembly: ExportRenderer(typeof(CustomMap), typeof(CustomMapRenderer))]

namespace MapOverlay.iOS
{
public class CustomMapRenderer : MapRenderer
{
MKPolylineRenderer polylineRenderer;
protected override void OnElementChanged(ElementChangedEventArgs e)
{
base.OnElementChanged(e);

        if (e.OldElement != null) {
            var nativeMap = Control as MKMapView;
            if (nativeMap != null) {
                nativeMap.RemoveOverlays(nativeMap.Overlays);
                nativeMap.OverlayRenderer = null;
                polylineRenderer = null;
            }
        }

        if (e.NewElement != null) {
            var formsMap = (CustomMap)e.NewElement;
            var nativeMap = Control as MKMapView;
            nativeMap.OverlayRenderer = GetOverlayRenderer;

            CLLocationCoordinate2D[] coords = new CLLocationCoordinate2D[formsMap.RouteCoordinates.Count];
            int index = 0;
            foreach(var position in formsMap.RouteCoordinates)
            {
                coords[index] = new CLLocationCoordinate2D(position.Latitude, position.Longitude);
                index++;
            }

            var routeOverlay = MKPolyline.FromCoordinates(coords);
            nativeMap.AddOverlay(routeOverlay);
        }
    }
}
}

**Comment by amay077** [comment]
You can see original Xamarin.Forms.Maps that implemented for Apple Maps.

https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Maps.iOS/MapRenderer.cs
