### ISSUE TITLE
Support Map.MapClicked and MapLongClicked event

### ISSUE THREAD

**Issue by amay077** [amay077/Xamarin.Forms.GoogleMaps#45]
Implements as follows:

## Android

* [Events  |  Google Maps Android API  |  Google Developers](https://developers.google.com/maps/documentation/android-api/events#map_click_long_click_events)

## iOS

* [<GMSMapViewDelegate> Protocol Reference  |  Google Maps SDK for iOS  |  Google Developers](https://developers.google.com/maps/documentation/ios-sdk/reference/protocol_g_m_s_map_view_delegate-p.html?hl=ja#a9f226252840c79a996df402da9eec235)

**Comment by XnainA** [comment]
Please fix this issue ASAP.

**Comment by amay077** [comment]
@XnainA 

I deployed v1.5.0-beta1 to nuget - https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/1.5.0-beta1 .

This contains as follows:

* #10 Moving pin by tap and hold (Android / iOS only)
* #45 Support Map.MapClicked and MapLongClicked event (Android / iOS only)

Also I added samples for these.
Please check BasicMapPage and CustomPinsPage in [XFGoogleMapSample(dev branch)](https://github.com/amay077/Xamarin.Forms.GoogleMaps/tree/develop/XFGoogleMapSample) .

If you (and somebody) say "OK" then I'll deploy as stable version. 👌

**Comment by amay077** [comment]
v1.5.0 is now stable! 🎉

**Comment by XnainA** [comment]
Great. Congratulations and thank you so much for your support :)
