### ISSUE TITLE
How do i customize the marker pin in xamarin forms

### ISSUE THREAD

**Issue by saikrupa** [amay077/Xamarin.Forms.GoogleMaps#450]
I am very new to xamarin, I just want to display the view like this tried lot of ways like creating a image dynamically and place it as marker but all these solutions doesn't worked for me. can some one guide me with the solution  

![cl0rd](https://user-images.githubusercontent.com/4343451/35030085-d6f42966-fb83-11e7-943c-e2f0bd1de6ad.png)

**Comment by deextercz** [comment]
There are more ways how to do it.
1. It is possible to  write your text to your image and then convert to bitmapdescriptor or you can create vector (but there are some issue with scaling for resolutions).
2. Another is create view where you place image and label (this will not work for UWP)
It depends what you want to do.

**Comment by amay077** [comment]
Duplicate with https://github.com/amay077/Xamarin.Forms.GoogleMaps/issues/70 .
Please any comment or post 👍  in #70 .
