### ISSUE TITLE
Show Map directions

### ISSUE THREAD

**Issue by Wilmerj** [amay077/Xamarin.Forms.GoogleMaps#451]
Hi everyone, I want to show directions into my map, do they know how make that?

**Comment by amay077** [comment]
Hi @Wilmerj ,
What do you mean "show directions" ? Is it like turn-by-turn car navigation?
We don't support turn-by-turn navigation.

**Comment by amay077** [comment]
Or same as https://github.com/amay077/Xamarin.Forms.GoogleMaps/issues/362 ?
