### ISSUE TITLE
NativeMap is not available at OnElementChanged of the Android Map renderer

### ISSUE THREAD

**Issue by alexeystrakh** [amay077/Xamarin.Forms.GoogleMaps#452]
I'm trying to override map renderer for my specific needs and custom renderer is unable to access NativeMap because at that stage it's not available.

From the code, there is MapReady handler, but it's private and not available for an override.

**Comment by amay077** [comment]
I understand.

``OnMapReady(GoogleMap nativeMap, Map map)`` should change to ``protected`` for make custom renderers.

I'll do it.

**Comment by amay077** [comment]
Fixed in https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/3.0.0-beta4 .
