### ISSUE TITLE
[FEATURE REQUEST] Cluster Markers

### ISSUE THREAD

**Issue by galadril** [amay077/Xamarin.Forms.GoogleMaps#453]
---
### SUMMARY

Please implement the posibility to do Marker Clustering as described on this google developer page:
https://developers.google.com/maps/documentation/javascript/marker-clustering

### DETAILS

The number on a cluster indicates how many markers it contains. Notice that as you zoom into any of the cluster locations, the number on the cluster decreases, and you begin to see the individual markers on the map. Zooming out of the map consolidates the markers into clusters again.

![example from google developers](https://user-images.githubusercontent.com/14561640/35512473-3553c96e-0500-11e8-83ca-ad61baadfd02.png)

### PLATFORMS

which platform do you want?

- [X] Android
- [X] iOS
- [ ] UWP

**Comment by amay077** [comment]
Duplicate with https://github.com/amay077/Xamarin.Forms.GoogleMaps/issues/123 .
Please any comment or post 👍  in #123 .
