### ISSUE TITLE
MoveToRegion doesn't work properly on IOS

### ISSUE THREAD

**Issue by denmusic1992** [amay077/Xamarin.Forms.GoogleMaps#455]
### SUMMARY

I'm using the google maps for my xamarin forms app. It works good on Android, but on iOS there is a bug - I can't center my geolocation on the map or any pins location.
The code is:
```csharp
MyMap.MoveToRegion(MapSpan.FromCenterAndRadius(new Xamarin.Forms.GoogleMaps.Position(finalLat, finalLng), Distance.FromKilometers(distance / 2 + 1)));
```
I'm using maps  with a HeightRequest = ContentHeight / 2.  So it looks like centering using MoveToRegion works like if the map is Full Screen...
P.S. Sorry if I have some mistakes in English..
### VERSIONS

* Xamarin.Forms.GoogleMaps - 2.3.0
* Xamarin.Forms - 2.5.0
* 

### PLATFORMS

- [ ] Android
- [x] iOS
- [ ] UWP

**Comment by amay077** [comment]
```cs
MyMap.MoveToRegion(MapSpan.FromCenterAndRadius(
  new Xamarin.Forms.GoogleMaps.Position(
    finalLat, finalLng), Distance.FromKilometers(distance / 2 + 1)));
```

Could you show me actual parameters? (``finalLat``, ``finalLon`` and ``distance``)

**Comment by denmusic1992** [comment]
Good day!
Here are the parameters:
`
var latitudes = new List<double>();
            var longitudes = new List<double>();

            latitudes.Add(Location.Latitude);
            longitudes.Add(Location.Longitude);
...(some staff with adding another coordinates)...
double lowestLat = latitudes.Min();
            double highestLat = latitudes.Max();
            double lowestLng = longitudes.Min();
            double highestLng = longitudes.Max();
            double finalLat = (lowestLat + highestLat) / 2;
            double finalLng = (lowestLng + highestLng) / 2;
            double distance = DistanceCalculation.GeoCodeCalc.CalcDistance(lowestLat, lowestLng, highestLat, highestLng, DistanceCalculation.GeoCodeCalcMeasurement.Kilometers);
MyMap.MoveToRegion(MapSpan.FromCenterAndRadius(
  new Xamarin.Forms.GoogleMaps.Position(
    finalLat, finalLng), Distance.FromKilometers(distance / 2 + 1)));
`

**Comment by denmusic1992** [comment]
Any ideas? I am still stuck with this problem...
I don't want to use another map library, but on iOS it looks not so good..
BTW, all the markers have an offset on the map in iOS. And I tried to set different anchors, but it doesn't help.

**Comment by nt2vna** [comment]
MoveToRegion works for me,ios 11, lastest version. Check your lat, long or Googlemap API key

**Comment by amay077** [comment]
We have not received the requested information. 
If you are still experiencing this issue please provide all the requested information and re-open the issue report. 
Thanks!
