### ISSUE TITLE
CustomMapRenderer for Android in 2.2.1/2.3.0 missing overrides

### ISSUE THREAD

**Issue by dinonovak** [amay077/Xamarin.Forms.GoogleMaps#458]
HI,

I am experiencing a strange issue with Android version 2.3.0.
If I try to Override OnElementChanged it is missing.

when I downgrade to v2.2.1 then I am unable to override OnMarkerCreated, looks like it was added in 2.3.0

in Ios 2.3.0 everything works, can you please take a look on the issue?

Thank you,
DiNo

**Comment by dinonovak** [comment]
Looks like ElementChangedEventArgs<View> need to be chnaged to ElementChangedEventArgs<Map>

**Comment by amay077** [comment]
Hi, sorry for late.
I can not understand your actual problem.
Could you show me details?
