### ISSUE TITLE
How to InfoWindow automatically open when Map Page load?

### ISSUE THREAD

**Issue by aliyasar** [amay077/Xamarin.Forms.GoogleMaps#459]
Hi,

I have inserted a bunch of pin to the map. However, it only shows information when a user clicks the pushpin. I want to do that automatically open Info Window when Map Page load. Is it possible to default show information about the Pins when a user does not click any pin? 

Thanks.

**What I did:** [
![image](https://user-images.githubusercontent.com/6706258/36658013-dbb293a4-1adf-11e8-9bfc-9d677487fab4.png)
](url)

**What I want to do:** [
![image](https://user-images.githubusercontent.com/6706258/36657791-018a1e9a-1adf-11e8-8166-f5c223880615.png)
](url)

**Comment by edosusanto** [comment]
Hi I don't think you can show all info windows. The google map API doc said that you can only display one info window at a time. I think you should make custom pins with labels
