### ISSUE TITLE
Possible to get center position of a map.

### ISSUE THREAD

**Issue by rex232** [amay077/Xamarin.Forms.GoogleMaps#460]
Are there any function to get the center position of map visible region.
 Just like a uber app done.

**Comment by salvador-guerrero** [comment]
I've been using the `CameraPosition `property, which has a `Target `property

Xaml:
``` 
            <maps:Map CameraPosition="{Binding MyPosition}"/>
```

ViewModel:
```
var lat = MyPosition.Target.Latitude;
var lng = MyPosition.Target.Longitude;
```

**Comment by amay077** [comment]
Also, you can handing camera moving via ``Map.CameraIdled`` event.

https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/3c5968eb32f001251682a2298dad9a89e8772c65/XFGoogleMapSample/XFGoogleMapSample/CameraPage.xaml.cs#L50-L58
