### ISSUE TITLE
install the latest version of 'Google Repository' from the 'Extras'

### ISSUE THREAD

**Issue by ShahramShobeiri1** [amay077/Xamarin.Forms.GoogleMaps#463]
### SUMMARY

When I add Xamarin.Forms.GoogleMaps nuget package to my Android project, I get this build errors:

1>------ Build started: Project: Sayba.Xamarin.Android, Configuration: Debug Any CPU ------
1>C:\TFS_Sayba\Sayba\Services\packages\Xamarin.Build.Download.0.4.2\build\Xamarin.Build.Download.targets(47,3): error XBD009: Partial Download Failed for one or more parts
1>C:\TFS_Sayba\Sayba\Services\packages\Xamarin.Build.Download.0.4.2\build\Xamarin.Build.Download.targets(47,3): error : An error occurred while sending the request.
1>C:\TFS_Sayba\Sayba\Services\packages\Xamarin.Build.Download.0.4.2\build\Xamarin.Build.Download.targets(47,3): error XBD404: Please open the Android SDK Manager and install the latest version of 'Google Repository' from the 'Extras' section, and then reload your solution.
========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========

My Google Repository version is 47

### VERSIONS

* Xamarin.Forms.GoogleMaps - 2.3.0
* Xamarin.Forms - 2.5.0.280555

### PLATFORMS

- [ ] Android

### HOW TO REPRODUCE

Just add the package to your project!

**Comment by ernestochaves** [comment]
Got the same error. Care to explain what was it?

**Comment by ShahramShobeiri1** [comment]
I solved this problem but there wasn't a straight forward way. Here is some of activities that I did:
1-Downloading API level 26 in Android SDK Manager
2-Using Oreo as target framework in Xamarin.Android project(Compile using Android version ...)
3-Updating everyting in Tools and Extra sections in Android SDK Manager
4-Installing Google Play Services in Extra section in Android SDK Manager
5-Removing bin and obj, cleaning, rebuilding, restaring visual studio 1000 times!
Hope this helps
Sorry for bad English.

**Comment by ernestochaves** [comment]
Google play services did it, thanks a lot.

**Comment by caioborges** [comment]
@ernestochaves, I installed google play services, but the problem still remains. 
Do you remember doing anything extra?

**Comment by ShahramShobeiri1** [comment]
Have you done all the 5 steps? I don't remember anything extra.

**Comment by ernestochaves** [comment]
I did all steps as well. After I added google play services, restarted everything, clean, etc.

**Comment by chandsuhail99** [comment]
maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
this is not work for me
