### ISSUE TITLE
.Net standard support

### ISSUE THREAD

**Issue by TonyHenrique** [amay077/Xamarin.Forms.GoogleMaps#464]
I am trying to use  in Xamarin Forms with .Net Standard, but this appears:

> Warning	NU1701	Package 'Xamarin.Forms.GoogleMaps 2.3.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.

.Net standard support will be good thing. (with the lowest the .net standard version possible)

**Comment by vitmarks** [comment]
Same here, would be nice to have a version for .Net Standard

**Comment by amay077** [comment]
ref #355

**Comment by amay077** [comment]
I released https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/3.0.0-beta1 what support .NET Standard 2.0 .

Could you try it?
