### ISSUE TITLE
MyLocationButton position

### ISSUE THREAD

**Issue by antferr** [amay077/Xamarin.Forms.GoogleMaps#465]
## FEATURE REQUEST / SUGGESTION
Change the position of the mylocation button

### SUMMARY
On iOS, MyLocation button is located at the bottom right. 
The request is to be able to position it in the other 3 corners of the screen.

### PLATFORMS
- [x] iOS

**Comment by justwooper** [comment]
Yes I also needed in other position, thanks a lot

**Comment by amay077** [comment]
Feel difficultly.
Google Maps iOS SDK doesn't have position for MyLocation button.
(Also Google Maps Android SDK too.)
