### ISSUE TITLE
Xamarin Froms Error

### ISSUE THREAD

**Issue by vibhav45** [amay077/Xamarin.Forms.GoogleMaps#468]
I am facing the following problem after Installing Xamarin.Forms.Map plugin

Severity	Code	Description	Project	File	Line	Suppression State
Error		java.lang.IllegalArgumentException: already added :  Lcom/google/android/gms/internal/zza;	app.Android			

Any solution for this?

Using Visual Studio 2017, Xamarin forms and Xamarin forms map version : 2.5.0.280555

**Comment by amay077** [comment]
Do you use Xamarin.Forms.Maps?

This is Xamarin.Forms. **GoogleMaps** library.
