### ISSUE TITLE
Show InfoWindow for all pins instantly

### ISSUE THREAD

**Issue by vaadzz** [amay077/Xamarin.Forms.GoogleMaps#469]
Hi.
It's possible to show InfoWindow for all pins instantly?
Regards.

**Comment by deextercz** [comment]
Hello @vaadzz,
I am sure you dont want to do this.
The only way is iterate through collection of pins and toggle infowindow and if you have too much pins it could cause performance problems.

**Comment by mwerickson** [comment]
Hi @deextercz ,
I agree, too many pins would cause performance issues.  In my case I want to show the info window for one pin.  You mention toggle infowindow, how exactly do you do that?  I don't see any methods on the pin that will show the infowindow, the map object has a "SelectedPin" which is supposed to show the infowindow, but I can't seem to get the infowindow to show.  Any thoughts?

Thanks.

**Comment by amay077** [comment]
Hi @mwerickson ,

> the map object has a "SelectedPin" which is supposed to show the infowindow, but I can't seem to get the infowindow to show. 

Could you try our sample apps?

https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/6d61c21dffd041c6d5f73e8e74d7f22784cf08de/XFGoogleMapSample/XFGoogleMapSample/PinsPage.xaml.cs#L89-L99
