### ISSUE TITLE
Add Map Projection property to offset the center of the map

### ISSUE THREAD

**Issue by rizaanlakay** [amay077/Xamarin.Forms.GoogleMaps#474]
I know that map.padding can be used to offset the centre of the map. Any idea how I can offset the center of map when I am using the camera? Padding doesnt offset properly when using a Camera with a tilt.

eg.
map.AnimateCamera(CameraUpdateFactory.NewCameraPosition(new CameraPosition(new Xamarin.Forms.GoogleMaps.Position(pos1.Value.Latitude, pos1.Value.Longitude), 17d, bearing, 80d)));

I'm trying to get a view with a 80d tilt, but offset the centre point a bit further down the screen. Kind of like a navigation app does.
![whatsapp image 2018-04-10 at 12 50 47](https://user-images.githubusercontent.com/16114274/38552927-f7e58e14-3cbd-11e8-9b2b-46f0ba189220.jpeg)

**Comment by amay077** [comment]
Could you try ``Map.Padding`` property?

* https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/master/XFGoogleMapSample/XFGoogleMapSample/CameraPage.xaml.cs#L132
