### ISSUE TITLE
Auto center and Auto zoom for all pins

### ISSUE THREAD

**Issue by btidoug** [amay077/Xamarin.Forms.GoogleMaps#476]
I am trying to center and zoom the map appropriately for a group of pins.  I would like the map to appropriately zoom so all pins that are to be mapped are all visible and appropriately zoomed so you can see all the pins without additional zooming, etc.

Is there a feature for this already?

**EDIT**
I have created a quick and dirty solution in my app but don't know how to offer it up to developers here to add.  Solution is crude and simple.  I am just averaging all the points to get an average center point.  I don't have an answer for the appropriate zoom region yet but this is a good start for what I need.  Any way this could be added to the project or something similar?

**Comment by emrahkenan** [comment]
You can try this metod.
```
//Dynamic Zoom Level 
private async Task MapAnimateCamera(IList<Xamarin.Forms.GoogleMaps.Position> pList, int padding)
{
	if (pList.Count > 0)
	{
		var bounds = Bounds.FromPositions(pList);
		await AnimateCameraRequest.AnimateCamera(CameraUpdateFactory.NewBounds(bounds, padding));
	}
}
```
```

**Comment by btidoug** [comment]
I was able to make a few changes and get it all working.  Thanks!
