### ISSUE TITLE
Map not loading in android 4.4.2

### ISSUE THREAD

**Issue by mo-kml** [amay077/Xamarin.Forms.GoogleMaps#478]
im trying to use this nuget in my app. and everything works fine but in some devices map wont show and the map control just show a green page with Xamarin.Forms.GoogleMaps title on it. what should i do?

- [x] Android

* Xamarin.Forms.GoogleMaps - 2.3.0
* Xamarin.Forms - 2.5.0.280555

**Comment by amay077** [comment]
You should set Google Maps Android API Key to your ``App.cs``.


* https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/map#android
* https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/master/XFGoogleMapSample/Droid/MyApp.cs#L8
