### ISSUE TITLE
How can I open InfoWindow of specific pin after all pins have loaded

### ISSUE THREAD

**Issue by mwerickson** [amay077/Xamarin.Forms.GoogleMaps#479]
I have an app that can at times have 7000+ pins, so for performance reasons I've implemented logic such that only pins in the VisibleRegion are shown.  This means I have to react to map movement so I can load pins based on the center of the map.  I utilize the InfoWindow and since the default behavior on pin tap is to move that pin to the center of the map, I react by loading more pins based on the new center.  This essentially closes the InfoWindow of the pin the user just tapped.

I have tried saving the SelectedPin, and then through a map behavior setting the map.SelectedPin hoping that would open the InfoWindow, but that doesn't seem to work.

So, my question is how can I open the InfoWindow for a specific pin AFTER all pins have been loaded and shown?

Thanks for any help.

**Comment by amay077** [comment]
You can use ``Map.CameraIdled`` event that raises when camera change stopped.
I think you disable auto map centering because it causes recursive moving map.

I wrote example code.

```csharp
public CustomPinsPage()
{
    InitializeComponent();

    // The first pin
    var _pin1 = new Pin()
    {
        Icon = BitmapDescriptorFactory.DefaultMarker(Color.Red),
        Label = "Pin A",
        Position = new Position(35.71d, 139.81d)
    };

    // The second pin
    var _pin2 = new Pin()
    {
        Icon = BitmapDescriptorFactory.DefaultMarker(Color.Blue),
        Label = "Pin B",
        Position = new Position(35.71d, 139.83d)
    };

    // The third pin
    var _pin3 = new Pin()
    {
        Icon = BitmapDescriptorFactory.DefaultMarker(Color.Yellow),
        Label = "Pin C",
        Position = new Position(35.71d, 139.85d)
    };

    Pin lastSelectedPin = null;

    // Clear pins when camera move started
    map.CameraMoveStarted += (sender, e) => 
    {
        map.Pins.Clear();
    };

    // Load pins when camera changed
    map.CameraIdled += (_, e) => 
    {
        map.Pins.Add(_pin1);
        map.Pins.Add(_pin2);
        map.Pins.Add(_pin3);

        // Restore selected pin
        if (lastSelectedPin != null) 
        {
            map.SelectedPin = lastSelectedPin;
        }
    };

    // Save selected pin
    map.SelectedPinChanged += (_, e) => 
    {
        if (e.SelectedPin != null) 
        {
            lastSelectedPin = e.SelectedPin;
        }
    };

    // Disable Auto-centering when Pin clicked
    map.PinClicked += (_, e) =>
    {
        map.SelectedPin = e.Pin;
        e.Handled = true;
    };

    map.InitialCameraUpdate = CameraUpdateFactory.NewPositionZoom(_pin1.Position, 12);
}
```

And screenshot is below:

![untitled3](https://user-images.githubusercontent.com/401369/39575327-0c32407e-4f15-11e8-9fbe-ead27e674054.gif)
