### ISSUE TITLE
Unable to us it on IOS .. seems fine on droid

### ISSUE THREAD

**Issue by Netrapida** [amay077/Xamarin.Forms.GoogleMaps#480]
- [ ] Android
- [X] iOS
- [ ] UWP

PROBREM REPORT
Unable to run in IOS .. i have no problem in android.

> namespace "FormsGoogleMaps" not found... on AppDelegate.cs

unable to compile

```
            global::Xamarin.Forms.Forms.Init();
            Xamarin.FormsGoogleMaps.Init("mykey"); 
            LoadApplication(new App());
```

### VERSIONS

* Xamarin.Forms.GoogleMaps - 1.7.2.2
* Xamarin.Forms - 2.5.x
* 

### PLATFORMS

- [ ] Android
- [x] iOS
- [ ] UWP

**Comment by amay077** [comment]
You should add Xamarin.Forms.GoogleMaps nuget package to your iOS project.
