### ISSUE TITLE
Custom pin icon using "BitmapDescriptorFactory.FromStream"

### ISSUE THREAD

**Issue by MarcoSal** [amay077/Xamarin.Forms.GoogleMaps#481]
(This is template for issue. Please choose from feature request or bug report or others then write.
If you need realtime communication then you can join our [gitter room](https://gitter.im/Xamarin-Forms-GoogleMaps/public).)

----
### SUMMARY

BitmapDescriptorFactory.FromStream = null!!

### DETAILS

I want to use custom markers. The 'BitmapDescriptorFactory.FromStream' statement always returns null values to me. if I use 'BitmapDescriptorFactory.FromBundle' instead, everything works fine.
where am I wrong?the image path 'png' is identical to the example supplied by you.

```
// usage of your requested feature to use
```

### PLATFORMS

which platform do you want?

- [x] Android
- [x] iOS
- [ ] UWP

----
### SUMMARY

(write summary of your bug report.)

### VERSIONS

* Xamarin.Forms.GoogleMaps - 2.3.0
* Xamarin.Forms - 2.3.4.247
* 

### PLATFORMS

- [x ] Android
- [x] iOS
- [ ] UWP

### HOW TO REPRODUCE

(Let me show how to reproduce with steps or codes)

                var assembly = typeof(MapCollect).GetTypeInfo().Assembly;
                var file = "marker02.png";
                var stream = assembly.GetManifestResourceStream($"AppWorkForce.{file}");

```csharp
// code for reproduce
```

### ACTUAL IMAGES

(Let me show your actual problem images/stacktrace. If you want to capture simulator screen to animation GIF, I recomend to [LICEcap](http://www.cockos.com/licecap/).)

![something_image](your_image.png) 

```
// paste stacktrace
```

----

## OTHERS

(free format)

**Comment by seanyda** [comment]
This has always been working for me. Heres my code.

`BitmapDescriptor SetPinIconStream(string embeddedResource)
        {
            var assembly = typeof(DeliveryTrackerDetail).GetTypeInfo().Assembly;
            var stream = assembly.GetManifestResourceStream($"" + embeddedResource);
            return BitmapDescriptorFactory.FromStream(stream);
        }`

**Comment by amay077** [comment]
``FromBundle`` is for native(Android or iOS) resource.
``FromStream `` is for ".NET(PCL)" resource.

And you should set ``marker02.png`` as EmbedResource.
