### ISSUE TITLE
Position on screen of Pins to draw custom graphics using SkiaSharp

### ISSUE THREAD

**Issue by simonemarra** [amay077/Xamarin.Forms.GoogleMaps#487]
### SUMMARY

Hi!
I'm guessing if there is a way to get the position of the pins in terms of pixels of screen / position relative to xaml/cs view layouts, etc... or any other method I can use to get the screen position of Pins.

### DETAILS

I need this since I found very handy to use a SkiaSharp canvas on top of Map view component: using and absolute layout I can overlay a drawing SkiaSharp canvas above the Map and draw all the graphics I want without the need to create custom Xamarin.Forms.GoogleMaps Pins. The resulting performace is really fast and I could even create animations on drawings...

I currently need to write some labels near the pins, but such labels should not be shown if another label is already on the same position (no overlapping). I cannot use custom pins "FromView" since it seems to be a bit slow on rendering elements (using 126 Pins I can clearly see all the labels appearing one by one, taking about 5 seconds to complete, maybe I'm doing something wrong, but I basically copied the "BindingPinView" sample). In addition, I should also know the dimension and position of custom pin to avoid the Labels to overlap themself... and to do this, again, I need to know the position of GoogleMaps elements on the view :(

Using SkiaSharp I have problems related to X-Y values when the map is shown with small zoom values and I can see almost all the world on my Map view. The CameraIdled event give me info about the center point and the VisibleArea, but I cannot convert such values to get the top/bottom bounds since I have only center latitude values, but not top/bottom latitude values. If I use the VisibleRegion.LatitudeDegrees value it seems to be not a correct number when showing the whole world (including poles). It could be related to Mercator Projection problems, but that's it!

The best way for me should be to be able to get pin properties using a method like this:
`
Point position = pin.ViewPosition();
`
This method should return the position related to the GoogleMaps Native View (in pixels), so we can use such info to draw elements on the SkiaSharp canvas placed on top of GoogleMaps component.

### ADDITIONAL INFO

The xaml layout I'm using to overlap GoogleMaps component and SkiaSharp is the following:

```
<AbsoluteLayout x:Name="navLayoutPage" 
        VerticalOptions="FillAndExpand" 
        HorizontalOptions="FillAndExpand"
        Margin="0,0,0,0"
        >
        <maps:Map
            x:Name="mainMap"
            IsShowingUser="False"
            MapType="Satellite" 
            AbsoluteLayout.LayoutBounds="0,0,1,1"
            AbsoluteLayout.LayoutFlags="All"
            />
        <skiaSharp:SKCanvasView
            x:Name="canvasView" VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand" 
            BackgroundColor="Transparent"
            InputTransparent="True"
            AbsoluteLayout.LayoutBounds="0,0,1,1"
            AbsoluteLayout.LayoutFlags="All"/> 
    </AbsoluteLayout>
```

where skiaSharp and maps namespaces are defined as:
```
             xmlns:maps="clr-namespace:Xamarin.Forms.GoogleMaps;assembly=Xamarin.Forms.GoogleMaps"
             xmlns:skiaSharp="clr-namespace:SkiaSharp.Views.Forms;assembly=SkiaSharp.Views.Forms"
```

### PLATFORMS

- [x] Android
- [x] iOS
- [ ] UWP

**Comment by simonemarra** [comment]
At the moment I'm going to expose the Latitude and Longitude of TopLeft, TopRight, BottomLeft and BottomRight corners... It is not the same as having the screen position, but it helps performing the convertion between canvas pixels and lat/long position...

**Comment by simonemarra** [comment]
I close the issue due to merge of pull request #488

**Comment by amay077** [comment]
Fixed in https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/3.0.0-beta4 .

**Comment by BurakOgutken** [comment]
@simonemarra hello could you help me how can i put text with pin how to use skiaSharp

**Comment by BurakOgutken** [comment]
pin.ViewPosition(); this property doesnt have

**Comment by simonemarra** [comment]
I'm sorry, but I did not tested new Xamarin.Forms.GoogleMaps 3.x versions yet.
I think I'll take a look to brand new release in few months, but at the moment I'm a bit busy with a new product we are developing.

**Comment by AlonRom** [comment]
@simonemarra Hi, do you know how to put a resizable shape on the mao without losing the move camera event?

**Comment by simonemarra** [comment]
> @simonemarra Hi, do you know how to put a resizable shape on the mao without losing the move camera event?

Actually I have never did it, but I use the property InputTransparent=true to avoid the touch/click events on my canvas. Anyway I assume you needs the touch events on the shape, so my answer may be useless :(

**Comment by simonemarra** [comment]
I also found this s.o. thread, it may be a way to solve it:

https://stackoverflow.com/a/25650825

**Comment by AlonRom** [comment]
@simonemarra thanks, I will try.

**Comment by stefancvetkovic** [comment]
Im looking also on this. Im trying to create some different pins via SkiaSharp and then to use them as pins like .png files
