### ISSUE TITLE
[Android]Map.Pins.Clear doesn't work correct

### ISSUE THREAD

**Issue by AntonAndr** [amay077/Xamarin.Forms.GoogleMaps#49]
Map.Pins.Clear doesn't work if some pins are not displayed (because of #30 )

**Comment by amay077** [comment]
Thank you for your reporting.
I'll start fix #30.

**Comment by AntonAndr** [comment]
In my experience Map.Pins.Remove & Map.Pins.Clear works correct only the first time for every new Map

**Comment by amay077** [comment]
I fixed #30 in [Xamarin.Forms.GoogleMaps 1.5.1-beta1](https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/1.5.1-beta1).
Also I add "Shapes with initialize" sample - https://github.com/amay077/Xamarin.Forms.GoogleMaps/tree/issue_30/XFGoogleMapSample .

Please try this version. 
(You should check "Show pre-release packages" in nuget package manager)
