### ISSUE TITLE
How to code for the pin in drag and drop event?

### ISSUE THREAD

**Issue by WeiChun0723** [amay077/Xamarin.Forms.GoogleMaps#490]
I wish to ask how you get the position of the pin when you dragged it to certain position?

**Comment by WeiChun0723** [comment]
Thanks for the help, I wish to ask did the nuget came with the search place auto complete function?

**Comment by amay077** [comment]
No, We don't provide search place auto complete function.

**Comment by WeiChun0723** [comment]
Ok thanks. Good job on this nuget, it save me a lot of time. Keep it up !

**Comment by WeiChun0723** [comment]
Oh Sorry, I have one more question about the map will always direct me to Rome by default every time I open the map, is there any way to change it?

**Comment by amay077** [comment]
You can set ``map.InitialCameraUpdate`` to initial position and zoomLv in your page constructor.

https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/7c5605c6ee198af3dd12f68a926f0afc168dfcdc/XFGoogleMapSample/XFGoogleMapSample/BindingPinViewPage.xaml.cs#L13
