### ISSUE TITLE
InitialCameraUpdate to my custom place and after 2 seconds MoveToRegion to CurrentLocation

### ISSUE THREAD

**Issue by mammadkoma** [amay077/Xamarin.Forms.GoogleMaps#492]
Hi
I want to show my custom place when map open , and its ok by set InitialCameraUpdate="35.11, 54, 4.5, 0, 0".
Then I want to get CurrentLocation by geolocator : CurrentPosition = await _geolocator.GetPositionAsync();  (I did in ViewModel)
Finding CurrentPosition takes 1 or 2 seconds.
How can I MoveToRegion to the CurrentPosition after this 1 or 2 seconds?

- [x] Android
- [x] iOS
- [x] UWP

**Comment by mammadkoma** [comment]
Noone ?!

**Comment by amay077** [comment]
I think you should call ``_geolocator.GetPositionAsync()`` in previous page.

```
class PreviousPage {
    async void onButtonClick() {
        var pos = await _geolocator.GetPositionAsync(); // 1 or 2 seconds
        this.Navigation.PushAsync(new MapPage(pos));
    }
}
```
