### ISSUE TITLE
Bicycle Layer

### ISSUE THREAD

**Issue by FalmaJeus** [amay077/Xamarin.Forms.GoogleMaps#495]
### SUMMARY

On my app, I need to add bicycle layer on map.
I want to know that if you have plan to add bicycle layer.
Or can you give me some hints so that I can add it and contribute.

### DETAILS

```
// How to use of your requested feature
```

### PLATFORMS

- [x] Android
- [x] iOS
- [x] UWP

**Comment by amay077** [comment]
Do you know [opencyclemap](https://www.opencyclemap.org/) ?

If you know opencyclemap's tile specification then you can set ``map.TileLayers`` to it.

e.g. https://www.openrailwaymap.org/ 's tile implementation is below:

https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/f4cf99a4829937e9974db3174465d0004e18aa6b/XFGoogleMapSample/XFGoogleMapSample/TilesPage.xaml.cs#L26-L41

**Comment by FalmaJeus** [comment]
Hello,

I know that opencyclemap provides tile pngs and i just want to add bicycle layer over existing google map.
The traffic layer worked well and i want bicycle layer to be added like that.

What is your opinion?
Thanks.
