### ISSUE TITLE
Caching bitmap descriptors

### ISSUE THREAD

**Issue by Matiszak** [amay077/Xamarin.Forms.GoogleMaps#497]
### SUMMARY

Add feature to cache native bitmap descriptors to prevent OutOfMemory exceptions when drawing many pina on map.

### DETAILS

Currently when creating a pin if one wants to have custom icon he must set Icon on Pin like this: 
``` Pin.Icon = BitmapDescriptorFactory.FromStream(...) ```
Although even when setting the same reference to BitmapDescriptor on many Pins underneath the hood PinLogic.cs creates new native bitmap descriptor for each pin.

My feature request can be implemented in many ways but the goap is the same: to cache native bitmap descriptor when many of pin icons are the same.

Solution 1(using configuration to enable caching)
```
GoogleMapConfig.BitmapDescriptorCaching = true;

BitmapDescriptor customIcon = BitmapDescriptorFactory.FromStream(...);

Pin pin1 = new Pin();
pin1.Icon = customIcon;
Map.Pins.Add(pin1); // This would generate native bitmap descriptor underneath and save mapping to some dictionary

Pin pin2 = new Pin();
pin2.Icon = customIcon;
Map.Pins.Add(pin2); // This would reuse previously created native bitmap descriptor because the reference to bitmap deacriptor is the same
```
During my tests it shows that drawing 430 custom pins on map on my app eats 660mb ram. When using caching it is down to 360 mb.

Tests performed on Android using Xamarin Profiler. But i guess iOS could benefit from such an optimization as well.

### PLATFORMS

- [x] Android
- [x] iOS
- [ ] UWP

**Comment by amay077** [comment]
Could you propose "caching implementation" to me?

I think caching algorithm is case-by-case.
So I don't want to lock algorithm.
I think that would be nice if developer can inject caching algorithm to ``BitmapDescriptor ``.

**Comment by Matiszak** [comment]
I've beenthinking about it and i have some ideas but i need to put it in example code, I'll post it on weekend.

**Comment by Matiszak** [comment]
I've implemented sample solution on my fork: 
Note: I've not compiled it or tested, it's just for idea demonstration. 

https://github.com/Matiszak/Xamarin.Forms.GoogleMaps/commit/1068f997b5a322013f5ad8b53c48a327d49b30d4

Description:
I unsealed BitmapDescriptor class to make it possible to make custom BitmapDescriptors which can be handled by custom native descriptor factories. 
During implementation it crossed my mind to try make it in more object-oriented way(instead of Type property on BitmapDescriptor) but i didn't have enough time to try to do it and I think it could be a breaking change. Nevertheless it's worth considering.

**Comment by Matiszak** [comment]
So I guess a thumb up is a go ? I can complete the implementation because i need it in my work anyway. Is there a possibility that if no breaking changes are introduced and tests passes that it gets into 3.0.0-beta-x release ?

**Comment by amay077** [comment]
Hi @Matiszak,

I sent [PR to your repo](https://github.com/Matiszak/Xamarin.Forms.GoogleMaps/pull/1) that contains some improvements.

I have a plan to merge it immediately if you send back PR to me. 👍

**Comment by Matiszak** [comment]
Tried the sample today on iPhone but surprisingly itworked very well without caching. Map loaded really fast and didn't see big spike of used memory. Although i couldnt use Xamarin Profiler so my results could be wrong. Do you know guys the best way to measure app ram usage on ios ?

**Comment by amay077** [comment]
Yes I also look like no problem without caching in iOS side.
And I'm not sure to measure ram usage.

But I believe ``ImageFactory`` is useful for iOS developer.
So I just released to https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/3.0.0-beta6 :grin:
