### ISSUE TITLE
Shape is below the custom tile layer

### ISSUE THREAD

**Issue by bishounen01** [amay077/Xamarin.Forms.GoogleMaps#499]
When I'm using custom tile from URL, the circles firstly are render, after tile is downloaded circles are hidden. And always after zoom the circles become visible until new tile is downloaded.

**Comment by amay077** [comment]
Workaround:
Please set ``Circle.ZIndex`` to ``1`` or  over ``2``.

Circle and tile ZIndex default values are both ``0``.
In this case, drawn tile above circle.

I will change tile's default ZIndex to ``-1``.

**Comment by amay077** [comment]
ref https://github.com/amay077/Xamarin.Forms.GoogleMaps/issues/501#issuecomment-402756156
