### ISSUE TITLE
Tile ArcGis No google maps

### ISSUE THREAD

**Issue by osekom** [amay077/Xamarin.Forms.GoogleMaps#501]
### SUMMARY

How could I just use the OSM tiles without having to call the google api or have to use the google api key? To specify even more where I would have to modify to use the OSM tiles by default in the plugins?

### PLATFORMS
- [x] Android
- [x] iOS
- [x] UWP

**Comment by osekom** [comment]
the lines are hidden under the OSM layer. Any reason why?

**Comment by amay077** [comment]
Workaround:
Please set ``Polyline.ZIndex`` to ``1`` or  over ``2``.

Polyline and tile ZIndex default values are both ``0``.
In this case, drawn tile above polyline.

I will change tile's default ZIndex to ``-1``.

**Comment by osekom** [comment]
Ohhh... Thank you 👍 How could you help establish maximum and minimum zoom? when the tiles are active and when applying the maximum zoom the image is lost

**Comment by amay077** [comment]
> establish maximum and minimum zoom

This is already posted in #315.
Please vote(comment :+1 ) to there.
