### ISSUE TITLE
ZoomLevel to Distance (radius) and/or back

### ISSUE THREAD

**Issue by z07713** [amay077/Xamarin.Forms.GoogleMaps#502]
### SUMMARY

Using the InitialCameraUpdate and MapSpan.FromCenterAndRadius method to move the map i cant get the same result of zoomlevel.

### DETAILS

InitialCameraUpdate = CameraUpdateFactory.NewPositionZoom(vm.Position, 15);
MapSpan = MapSpan.FromCenterAndRadius(Position, Distance.FromMeters(500));

I would like to get the zoomlevel equivalent somehow of the 500m distance or the opposite, it doesnt matter just to be able to achieve the same zoom level in both cases!

### PLATFORMS

- [x] Android
- [ ] iOS
- [ ] UWP

**Comment by amay077** [comment]
> I would like to get the zoomlevel equivalent somehow of the 500m distance or the opposite.

I think it is no make sense.
Because Google Maps uses Mercator projection.
Mercator projection is not correct distance.

> the Mercator projection distorts the size of objects as the latitude increases from the Equator to the poles. 
via https://en.wikipedia.org/wiki/Mercator_projection .
