### ISSUE TITLE
Add the circle draggble function

### ISSUE THREAD

**Issue by ViktorBylbas** [amay077/Xamarin.Forms.GoogleMaps#503]
### SUMMARY

Add the circle draggble function on map. According to the principle of how it is implemented on a pin

### PLATFORMS

- [ ] Android
- [x] iOS
- [ ] UWP

**Comment by amay077** [comment]
I feel difficult.
Because Xamarin.Forms.GoogleMaps is just only "wrapper of Google Maps Android/iOS SDK" .
Circle dragging is not supported in Google Maps Android/iOS SDK.
