### ISSUE TITLE
MoveToRegion not works

### ISSUE THREAD

**Issue by stefancvetkovic** [amay077/Xamarin.Forms.GoogleMaps#507]
### VERSIONS

* Xamarin.Forms.GoogleMaps -2.3.0
* Xamarin.Forms -2.5.1
* 

### PLATFORMS

- [ ] Android
- [x] iOS
- [ ] UWP

### ACTUAL BEHAVIOR

Maps not MoveToPin on selected pin

When I put in my constructor in codeBehind map.MoveToregion, or map.CameraAnimate, it wont to got o specific pin, ro position.

### ACTUAL SCREENSHOTS/STACKTRACE

Here is the actual code behind for constructor...

` public LocationPage ()
		{
            BindingContext = ViewModel = new LocationViewModel(App.ScreenHeight, App.ScreenWidth);
            InitializeComponent ();
            searchFullMapImage.IsVisible = false;
            map.UiSettings.ZoomControlsEnabled = false;
            List<Pin> defaultPins = ViewModel.Pins;

            Position? firstPinPosition = defaultPins?.FirstOrDefault(m => m.Position != null && m.Position.Latitude != 0 && m.Position.Longitude != 0)?.Position;
            defLat = firstPinPosition.Value.Latitude;
            defLong = firstPinPosition.Value.Longitude;

            LoadPins(defaultPins);
            map.MoveToRegion(MapSpan.FromCenterAndRadius(new Position(26, 26), Distance.FromKilometers(5.0)));

            Device.BeginInvokeOnMainThread(() => {
               map.AnimateCamera(CameraUpdateFactory.NewPosition((Position)firstPinPosition));
            });
            //SetHeader(ViewModel.TopUpBox, ViewModel.CashOutBox, ViewModel.ShopsBox);
            //LoadPins(ViewModel.Pins);
        }`

### EXPECTED BEHAVIOR

I want to be able automatically go to the selected pin

```csharp
// code for reproduce
```

**Comment by amay077** [comment]
You can use ``Map.InitialCameraUpdate`` property to default map location.

https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/4b5a5eb735e3aa6692bf37fe2bc62be604193809/XFGoogleMapSample/XFGoogleMapSample/BindingPinViewPage.xaml.cs#L13
