### ISSUE TITLE
Improved Binding Support

### ISSUE THREAD

**Issue by dansiegel** [amay077/Xamarin.Forms.GoogleMaps#519]
### SUMMARY

Working with the Map control should allow easy binding to a data set with a DataTemplate. This should work similar to a ListView in which you can bind to a generic set of data with a DataTemplate that produces a Pin to add to the controls Pin collection.

### DETAILS

Two bindable properties should be added:

- ItemsSource
- ItemTemplate

```xml
<maps:Map Items="{Binding MyLocations}">
  <maps:Map.ItemTemplate>
    <DataTemplate>
      <maps:Pin Label="{Binding Name}" 
                IsDraggable="false"
                Icon="{Binding SomeProp,Converter={StaticResource MyIconConverter}}">
        <maps:Pin.Position>
          <maps:Position Latitude="{Binding Latitude}"
                         Longitude="{Binding Longitude}" />
        </maps:Pin.Position>
      </maps:Pin>
    </DataTemplate>
  </maps:Map.ItemTemplate>
</maps:Map>
```

In addition, an event and Command should be added in the spirit of when a Pin is Selected.

- ItemSelected (event)
- ItemSelectedCommand 

When a Pin is selected the ItemSelected event should invoked and the Command executed with the BindingContext of each passed to them.

### PLATFORMS

- [X] Android
- [X] iOS
- [X] UWP

**Comment by amay077** [comment]
Do you know [Xamarin.Forms.GoogleMaps.Bindings](https://github.com/nuitsjp/Xamarin.Forms.GoogleMaps.Bindings) ?

This is already implemented part of your request.

**Comment by amay077** [comment]
I supported ItemsSource and ItemTemplate in Xamarin.Forms.GoogleMaps v3.1.0+ .

* https://github.com/amay077/Xamarin.Forms.GoogleMaps/releases/tag/v3.1.0
* https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/v3.1.0/XFGoogleMapSample/XFGoogleMapSample/PinItemsSourcePage.xaml#L22-L33

Thanks @dansiegel ! 👍

**Comment by gabrielbunselmeyer** [comment]
Is there any documentation as far as using the DataTemplate part of the binding goes? 

`<maps:Map x:Name="mapView" ItemsSource="{Binding Pins}" AbsoluteLayout.LayoutBounds="0, 0, 1, 0.7" AbsoluteLayout.LayoutFlags="All">
                <maps:Map.ItemTemplate>
                    <DataTemplate>
                        <maps:Pin Label="teste" Address="address">
                            <maps:Pin.Position>
                                <maps:Position >
                                    
                                </maps:Position>
                            </maps:Pin.Position>
                        </maps:Pin>
                                  
                    </DataTemplate>
                </maps:Map.ItemTemplate>
            </maps:Map>`

This is what I currently got, yet can't seem to figure out how to get Latitude and Longitude into it. <maps:Position> doesn't seem to have that property in XAML.
