### ISSUE TITLE
Support for Ground Overlays

### ISSUE THREAD

**Issue by dinonovak** [amay077/Xamarin.Forms.GoogleMaps#52]
HI,

is there a plan to support Ground Overlays ?

https://developers.google.com/maps/documentation/ios-sdk/overlays

Thanx,
D

**Comment by amay077** [comment]
Hi, thank for your request.
I planed this in v1.6.0.
Please wait for few days!

**Comment by amay077** [comment]
I published [v1.6.0-beta1](https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/1.6.0-beta1) that contains Ground Overlay support!
Also I added sample in [XFGoogleMapSample](https://github.com/amay077/Xamarin.Forms.GoogleMaps/tree/master/XFGoogleMapSample).
