### ISSUE TITLE
Pin bindings

### ISSUE THREAD

**Issue by mkopljar** [amay077/Xamarin.Forms.GoogleMaps#529]
### SUMMARY

Adding many pins individually to a map takes a long time because of ObservableCollection<T>.Add method is a bottleneck.
Is there a way to improve ? 
Suggestions: can pin source be anything else but ObservableCollection<Pin> ? Say, List<Pin> ? 
Can bindings be enforced in ViewModel ? 

### DETAILS

```
// How to use of your requested feature
```

### PLATFORMS

- [x] Android
- [x ] iOS
- [x ] UWP

**Comment by amay077** [comment]
Maybe you're from [Xamarin.Forms.GoogleMaps.Bindings](https://github.com/nuitsjp/Xamarin.Forms.GoogleMaps.Bindings/issues/13).

Xamarin.Forms.GoogleMaps is simply wrapper of [Google Maps SDK for Android](https://developers.google.com/maps/documentation/android-sdk/intro).

``Map.Pins.Add`` calls [GoogleMap.addMarker](https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap) directly.

This means, if you feel slowly for adding pin then it is Google Maps SDK for Android's limitation.

I'm not sure to how to improve speed.

**Comment by amay077** [comment]
I supported ItemsSource/ItemTemplate for Xamarin.Forms.GoogleMaps.

* https://github.com/amay077/Xamarin.Forms.GoogleMaps/releases/tag/v3.1.0
* https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/v3.1.0/XFGoogleMapSample/XFGoogleMapSample/PinItemsSourcePage.xaml#L22-L33
