### ISSUE TITLE
Double line address for map pin label

### ISSUE THREAD

**Issue by BillyMartin1964** [amay077/Xamarin.Forms.GoogleMaps#531]
Is it possible to set the label size or the number of lines on the map pin label to show more information?

Or perhaps, could we have a label1, label2, label3?

**Comment by amay077** [comment]
It is difficult (but not impossible).

We don't provide customizable info window.
But you can access to native pin object via ``Pin.NativeObject``.
Then you can implement [custom info window](https://developers.google.com/maps/documentation/android-sdk/infowindows?hl=ja#custom_info_windows) in your apps android(and iOS) side.

Sorry I haven't try it.

**Comment by BillyMartin1964** [comment]
Too bad. That's a big one for people. You would probably pick up a lot more users if you had a custom label. I'm using a custom pin image with rotation, so I can't use the native pin.

**Comment by amay077** [comment]
Yes, I looking for how to implement customized infowindow.
Especially I don't know way of inject Xamarin.Forms.View to infowindow contents.

I will continue to investigate.

This issue is duplicate to below issues. If you have additional comment then post to these.

* ref #70
* ref #532
