### ISSUE TITLE
[BUG] [Android] Map zooms fully in after orientation changed

### ISSUE THREAD

**Issue by galadril** [amay077/Xamarin.Forms.GoogleMaps#536]
### VERSIONS
* Xamarin.Forms.GoogleMaps - 3.0.1
* Xamarin.Forms - 3.1.0.637273

### PLATFORMS
- [X] Android
- [] iOS
- [] UWP

### ACTUAL BEHAVIOR
I have a (fullscreen) map shown in portrait mode with some pins and polylines, and the cameraposition set to show all in one screen. But as soon as I rotate the screen, the map is zoomed in! I don't refresh the data/page/viewmodel, only the maps component is zoomed in.

I've tested the same code with GoogleMaps version 3.0.0 and there it works correctly.

This bug is only on Android

### ACTUAL SCREENSHOTS/STACKTRACE
Screenshots android on GoogleMaps v3.0.1:
![start on portrait](https://user-images.githubusercontent.com/14561640/43588030-e6a5b2b6-966b-11e8-94b5-82b50662d12e.png) 

 after rotate:
![fully zoomed in](https://user-images.githubusercontent.com/14561640/43588050-ee32cbb8-966b-11e8-807e-efc213844f0e.png)

Screenshots when i downgrade to v3.0.0:
![screenshot_2018-08-02-15-44-12-054_com jfhillebrand myhillebrand](https://user-images.githubusercontent.com/14561640/43588079-04e814b2-966c-11e8-902b-0569f82211f8.png) 
 
![screenshot_2018-08-02-15-44-19-946_com jfhillebrand myhillebrand](https://user-images.githubusercontent.com/14561640/43588083-08fdbc3c-966c-11e8-90ab-286775040e06.png)

### EXPECTED BEHAVIOR
I would expect that the map doesn't changes

### HOW TO REPRODUCE
1. show a map in portrait mode, zoomed out with pins/polylines
2. rotate the screen
3. your now zoomed in automaticly

Please let me know if it's clear enough

**Comment by amay077** [comment]
I can not reproduce.

![untitled6](https://user-images.githubusercontent.com/401369/44941418-0dbf9280-add8-11e8-8cf9-333b298650de.gif)

I tried in my sample apps, but looks like works fine.
