### ISSUE TITLE
Pin Drop animation

### ISSUE THREAD

**Issue by JanmarlRodriguez** [amay077/Xamarin.Forms.GoogleMaps#537]
### SUMMARY

Is there a way to animate the Pin Drop animation?
Like a way to animate a pin specifically, either by moving in or rotating it.

### DETAILS

```
Something like Pin.Animate(property,value,time)
```

### PLATFORMS
- [x] Android
- [x] iOS
- [ ] UWP

**Comment by amay077** [comment]
Sorry, I don't have a plan to support it.
Because Google Maps Native SDK does not support pin animations.
