### ISSUE TITLE
Maps.MoveToRegion no longer works after NuGet update.

### ISSUE THREAD

**Issue by veletron2** [amay077/Xamarin.Forms.GoogleMaps#540]
### VERSIONS

* Xamarin.Forms.GoogleMaps - 3.0.1
* Xamarin.Forms - 3.1.0.697729
* 

### PLATFORMS

- [X ] Android
- [] iOS
- [ ] UWP

### ACTUAL BEHAVIOR

I have just updated from Xamarin.Forms.GoogleMaps V2.3.0 to V 3.0.1, unfortunately, the command: Maps.MoveToRegion(MapSpan.FromCenterAndRadius(position, Distance.FromMeters(PatientEvent.PositionAccuracy * ACCURACY_MULPTIPLIER)));

No longer works - the map always shows centred on Rome with no way to change this

The actual parameters from the above are Maps.MoveToRegion(55.9,-3.2,200); (Edinburgh, Scotland)

Any idea's? 

I also tried to downgrade to my old version 2.3.0, but this did not fix. If I restore my old project (pre a recent mass NuGet update) then it all starts working again. 

### ACTUAL SCREENSHOTS/STACKTRACE

![screenshot_20180816-131843](https://user-images.githubusercontent.com/34792184/44207993-043af700-a157-11e8-9c6c-ec4e6b746e1a.png)

In the above, the textural location which I get via the code below is correct.

 var address = CrossGeolocator.Current.GetAddressesForPositionAsync(location).Result.First();
            patientEvent.PositionAddress = $" {address.Thoroughfare}, {address.SubAdminArea}, {address.PostalCode} ";

### EXPECTED BEHAVIOR

Calling Maps.MoveToRegion(MapSpan.FromCenterAndRadius(position, distance); should always move the map to the new position.

Any idea's? I also downgraded forms to previous version, also to no avail - the only way I can get this working appears to be restoring my pre-nuget-update backup.

**Comment by veletron2** [comment]
I might have been premature on this. The old pre-nuget version of the code sometimes fails to update the map when I call MoveToRegion as well. Don't know why as yet. Co-ordinates are always correct (edinburgh), but sometimes, MoveToRegion simply does not make the map move.

Nigel

**Comment by amay077** [comment]
Could you try ``Map. InitialCameraUpdate`` property and ``Map.MoveCamera()/AnimateCamera()`` .

https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/master/XFGoogleMapSample/XFGoogleMapSample/BindingPinViewPage.xaml.cs#L13

https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/master/XFGoogleMapSample/XFGoogleMapSample/CameraPage.xaml.cs#L70
