### ISSUE TITLE
SVG

### ISSUE THREAD

**Issue by peder1896** [amay077/Xamarin.Forms.GoogleMaps#547]
### SUMMARY

How to get an svg image as pin icon ?

### DETAILS
Is there a way to assing an svg file to a pn icon?
Why not having a BitmapDescriptorFactory.FromSvg() 

### PLATFORMS

- [x] Android
- [x ] iOS
- [ ] UWP

**Comment by amay077** [comment]
Can not it.
Because GoogleMaps SDK for Android/iOS doesn't support SVG icon.
