### ISSUE TITLE
Alpha of Circle

### ISSUE THREAD

**Issue by TMagnum1974** [amay077/Xamarin.Forms.GoogleMaps#554]
Hello! First of all: Great library - love it! Makes cross-platform development much easier.

Ran into just one issue: How can I set the alpha value of a circle so it becomes transparent ? So far the circles render solid for me.

Thanks in advance for your help!

**Comment by amay077** [comment]
Yes you can!
We support transparent color in circle and any shapes.

https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/5c7968cbeb89e58288e34e1163052ede19ee1906/XFGoogleMapSample/XFGoogleMapSample/Shapes2Page.xaml.cs#L43-L52

![image](https://user-images.githubusercontent.com/401369/45603948-5b8bfa00-ba6a-11e8-9cbb-8af2d2cd982a.png)

**Comment by TMagnum1974** [comment]
Thank you! Must've missed that part.
