### ISSUE TITLE
Could not install package 'Xamarin.Forms.GoogleMaps 3.0.3'.

### ISSUE THREAD

**Issue by ignasbagdonas** [amay077/Xamarin.Forms.GoogleMaps#555]
Cannot update library from 2.3.0. Doesn't support PCL anymore? :(

You are trying to install this package into a project that targets '.NETPortable,Version=v4.6,Profile=Profile44', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by denmusic1992** [comment]
I have the same problem... trying to install into my pcl project, but no luck...

**Comment by denmusic1992** [comment]
I have the same issue, but my project targets '.NETPortable, Version=v4.5, Profile=Profile78'...

**Comment by amay077** [comment]
I'm not sure for compatibility of PCL and .NET Standard.

is there anyone who can help?

**Comment by denmusic1992** [comment]
I've found a solution: just created new .net standard library, copy-past all classes to it, managed nuget packages, and installed last ver. of google maps. Now it works!

**Comment by ignasbagdonas** [comment]
Yes, but I can't migrate to NET standart now. I have a lot of libraries which don't support .net standart and when I tried it wasn't like 1 hour thing. Spend a day and iOS project still won't build.

@amay077 I think you can create .csproj with previous targeting settings (PCL) and add (not copy) all classes from Xamarin.Forms.GoogleMaps folder to it. Then build another dll and add to nuspec like before. Then, I think, you will be able to support pcl and .net standart.

**Comment by amay077** [comment]
I added "BETA" [Xamarin.Forms.GoogleMaps/3.0.4-beta1](https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/3.0.4-beta1) what contains add support .NET Standard 1.0(≒ PCL) .

This fixes is inspired by official Xamarin.Forms.Maps nuspec.

https://github.com/xamarin/Xamarin.Forms/blob/bd31e1e9fc8b2f9ad94cc99e0c7ab058174821f3/.nuspec/Xamarin.Forms.Maps.nuspec#L31-L35

I seems solves this issue, but I can't fully test.

Could you try it?

**Comment by denmusic1992** [comment]
That works for me, thank you!

**Comment by ignasbagdonas** [comment]
It works for me too! Thanks.
