### ISSUE TITLE
Xamarin.Forms 3.2 - iOS Camera not updating

### ISSUE THREAD

**Issue by ianvink** [amay077/Xamarin.Forms.GoogleMaps#556]
### VERSIONS

* Xamarin.Forms.GoogleMaps - newest
* Xamarin.Forms - x3.2
* 

### PLATFORMS

 
- [x] iOS
 

### ACTUAL BEHAVIOR

Thank you for a wonderful tool!!!!!!

We updated to XF 3.2 and have found that the MoveToRegion() call for iOS doesn't update the map. Android is fine
![Map](https://user-images.githubusercontent.com/112916/45698827-c6e2d400-bb1d-11e8-97ba-bd97dcd24624.png)

 		private void AddMapToDetailsView()
		{
			Device.BeginInvokeOnMainThread(() => {
				if (_map != null)
				{
					var detailItemWithAddress = DetailItemWithLatLng();
					if (detailItemWithAddress != null  )
					{
						_map.IsVisible = true;
						var pin = detailItemWithAddress.Pin;
						_map.Pins.Add(pin);
						_map.MoveToRegion(MapSpan.FromCenterAndRadius(pin.Position, Distance.FromMeters(500)), true);
					 
					}
					else
					{
						_map.IsVisible = false;
					}
				}
			});
		}

**Comment by amay077** [comment]
Do you use Xamarin.Forms.GoogleMaps v3.0.3 ?
v3.0.2 has this bug but fixed in v3.0.3.

And please try [map.InitialCameraUpdate](https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/734fb3d1887677604c4b3455510ca6419ee4b636/XFGoogleMapSample/XFGoogleMapSample/Shapes2Page.xaml.cs#L69) instead of map.MoveRegion .

**Comment by ianvink** [comment]
Hi amay077,

Thank you for your quick reply. I am on 3.0.3

I tried this, but get the standard Rome view only, the camera doesn't update:

	
    var bounds = Xamarin.Forms.GoogleMaps.Bounds.FromPositions(new []{  pin.Position});
    _map.InitialCameraUpdate = CameraUpdateFactory.NewBounds(bounds,5);
    //Tried this too  _map.InitialCameraUpdate = CameraUpdateFactory.NewCameraPosition(new CameraPosition(pin.Position,1));

**Comment by ianvink** [comment]
Found the issue. If the Map.IsVisible == false then it won't update. In previous versions it would update.

Android always had to be visible
