### ISSUE TITLE
Programmatically dispose Map Cache

### ISSUE THREAD

**Issue by denmusic1992** [amay077/Xamarin.Forms.GoogleMaps#557]
### VERSIONS

* Xamarin.Forms.GoogleMaps - 3.0.3
* Xamarin.Forms - 3.2.0
* 

### PLATFORMS

- [x] Android
- [ ] iOS
- [ ] UWP

Are there any chances to dispose Map Cache programmatically?
I need to go further from my map page, but a lot of memory is used on my map page after getting some data. If I pop page, the memory clears as expected, but I need to do that when pushing new page.

**Comment by amay077** [comment]
What is map cache?
Do you use many pins, polygons and ground-overlays?

**Comment by denmusic1992** [comment]
I mean an uploading map bitmaps, when you move inside the map. When you do this, the usage of memory increases, in my case more than 200 MB after a lot of dragging and scaling. 
Just after that OnPin Clicked I push the new Page, but memory not cleaning, it's more than 300 MB usage.
But I need to clean up the memory....
P.S. Sorry if my English is not so good.

**Comment by amay077** [comment]
We can not support.
Because Native Google Maps SDK does not have feature.
