### ISSUE TITLE
can't install package

### ISSUE THREAD

**Issue by henryyue2010** [amay077/Xamarin.Forms.GoogleMaps#558]
Hi,
I tried to install Xamarin.Forms.GoogleMaps - 3.0.3, but got errors:
	
Could not install package 'Xamarin.Forms.GoogleMaps 3.0.3'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

### VERSIONS

* Xamarin.Forms.GoogleMaps - 3.0.3
* Xamarin.Forms - 3.1.0
* 

### PLATFORMS
- [x]PCL
- [x] Android
- [x] iOS
- [x] UWP

Any ideas?

**Comment by amay077** [comment]
Seems same as #555 

It fixed in [3.0.4](https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/3.0.4).
