### ISSUE TITLE
Map Pin Callout not refreshing Address

### ISSUE THREAD

**Issue by prajithmp** [amay077/Xamarin.Forms.GoogleMaps#56]
not updating **address** of pin callout when the pin is already selected. need to set the map.selectedPin to null and again set the Pin as map selected pin

**Comment by amay077** [comment]
I confirmed it.
But I wonder this behavior is [Google Maps Android API](https://developers.google.com/android/reference/com/google/android/gms/maps/model/Marker.html?hl=ja#showInfoWindow()).

I'll check it.

**Comment by prajithmp** [comment]
its right, 
when i tried to update a value (address) in infoWindow programmically (here the infowindow is already visible), its not getting changed . its only getting updated when i close and then open info window again.

**Comment by amay077** [comment]
I don't want to write workaround for this to Xamarin.Forms.GoogleMaps.
But I should care about "same behavior" in Android and iOS.

If callout not refreshing in iOS too, then I do nothing.

**Comment by JeanCollas** [comment]
Any idea on how to solve it? I think moving the pin a little bit redraws it, but as you wrote, it is a workaround...

**Comment by amay077** [comment]
This is a simple workaround.

```
pin.Address = "UPDATED";
map.SelectedPin = null;
map.SelectedPin = pin;
```

**Comment by amay077** [comment]
This is native Android/iOS Google Maps API behavior.
I hope resolve in native side.
