### ISSUE TITLE
Half black screen in Android 8.0 phones

### ISSUE THREAD

**Issue by amrkamal1993** [amay077/Xamarin.Forms.GoogleMaps#561]
I used this map works fine in ios and android but in android 8.0 devices show this issue

![image](https://user-images.githubusercontent.com/11614137/46085469-67806600-c1a6-11e8-9821-c808ed33d9ff.png)

**Comment by amay077** [comment]
I'm using Android 8.0 Phone (Xperia).
But I can't reproduce it.

Could you try another Android 8.0 phone?

**Comment by amrkamal1993** [comment]
I Used Huawei y9 and Huawei Honor and the same problem

**Comment by amay077** [comment]
Please try our sample apps - https://github.com/amay077/Xamarin.Forms.GoogleMaps/tree/da636133501368fa65c8346474d779c106305543/XFGoogleMapSample

Or https://install.mobile.azure.com/users/okuokuoku/apps/xfgooglemapsample/distribution_groups/trial

**Comment by amrkamal1993** [comment]
I used your sample works fine but when i put the same xaml in grid and set map to take half of screen look like the same which i post , any help ?

**Comment by amrkamal1993** [comment]
```
<ContentView Grid.Row="1" HorizontalOptions="Fill" VerticalOptions="Fill">
                    <map:Map InitialCameraUpdate="24.131345,44.58172,4,0,90" Padding="0" x:Name="AndroidMap" MapType="Street"
         HasZoomEnabled="True"/>          
        </ContentView>
```

**Comment by amrkamal1993** [comment]
![image](https://user-images.githubusercontent.com/11614137/47643733-036e0a80-db75-11e8-9fd8-001bd723c77a.png)

and looks fine when i minmize and maxmize application :/ how to slove this issue ?
