### ISSUE TITLE
MapClickedToCommandBehavior does not work in locality IOS

### ISSUE THREAD

**Issue by Nekzitow** [amay077/Xamarin.Forms.GoogleMaps#562]
**VERSIONS**
Xamarin.Forms.GoogleMaps - 3.0.3
Xamarin.Forms - 3.1.0

### PLATFORMS

- [ ] Android
- [X] iOS
- [ ] UWP

When i click on label locality does not call command Map clicked on iOS, but on Android it works.

![simulator screen shot - iphone 7 - 2018-10-03 at 11 25 17](https://user-images.githubusercontent.com/8594818/46424666-62b83680-c6ff-11e8-907c-cdcac56aad8e.png)

**Comment by amay077** [comment]
I think this is [Xamarin.Forms.GoogleMaps.Bindings](https://github.com/nuitsjp/Xamarin.Forms.GoogleMaps.Bindings) feature.
Xamarin.Forms.GoogleMaps does not have ``MapClickedToCommandBehavior ``.
