### ISSUE TITLE
Polygons areas with crossed coordinates are not filled with color in Android

### ISSUE THREAD

**Issue by wilkerfoureaux** [amay077/Xamarin.Forms.GoogleMaps#564]
### VERSIONS

* Xamarin.Forms.GoogleMaps - 3.0.4
* Xamarin.Forms - 3.1.0.697729
* Xamarin.GooglePlayServices.Maps - 60.1142.1

### PLATFORMS

- [x] Android
- [ ] iOS
- [ ] UWP

### ACTUAL BEHAVIOR

Polygons with cross-coordinates draw are not filled when the map is shown only with Android devices.

Squares, circles, complex polygons and others that do not have this positions work flawless.

### ACTUAL SCREENSHOTS/STACKTRACE

Web
![screenshot-2018-10-03-191323](https://user-images.githubusercontent.com/2434331/46442617-9ebfbb80-c740-11e8-9a96-1a949ae41de8.png)

Android
![screenshot_20181003-190545](https://user-images.githubusercontent.com/2434331/46442672-d0388700-c740-11e8-8fa1-f8dc4cab904d.png)

iOS
![screenshot_20181003-190545-2](https://user-images.githubusercontent.com/2434331/46442710-fc540800-c740-11e8-90c9-ce338b7e42a5.png)

```
// paste stacktrace
n/i
```

### EXPECTED BEHAVIOR

Polygons get's filled like in WEB and iOS maps.

### HOW TO REPRODUCE

1. Create a point in the map, intending to draw a square.
2. Create the second point;
3. Create the third point;
4. Create the fourth point, but crossing the polygon, like a "Z" draw.

```csharp
// code for reproduce
n/i
```

**Comment by amay077** [comment]
Probably this is Google Maps Android SDK's design.
Usually, "crossed coordinates/self intersection" polygon is INVALID shape. 
I suggest you should avoid invalid shapes.
