### ISSUE TITLE
Map Pin icon offest property

### ISSUE THREAD

**Issue by prajithmp** [amay077/Xamarin.Forms.GoogleMaps#57]
cannot set offset (x,y) for map Pin position as of google map java-script api marker positioning.

**Comment by amay077** [comment]
Does "offset(x, y)" mean [``MarkerOptions.anchorPoint``](https://developers.google.com/maps/documentation/javascript/3.exp/reference?hl=ja#MarkerOptions)?

**Comment by prajithmp** [comment]
yes

**Comment by amay077** [comment]
Ok, I will schedule it.

**Comment by amay077** [comment]
I implemented in https://github.com/amay077/Xamarin.Forms.GoogleMaps/pull/113 .

**Comment by amay077** [comment]
No problem?
Okay closed it.
