### ISSUE TITLE
 Isn't  it possible to know which button of pin is clicked or is there any by pass for this?

### ISSUE THREAD

**Issue by JitendraEpicomm** [amay077/Xamarin.Forms.GoogleMaps#571]
### SUMMARY

Isn't it possible to know which button of pin is clicked
### DETAILS

Hi Amay, Thanks for fantastic library. I'm implementing a custom pin which is like a info window and having two buttons. Isn't it possible to know which button of pin is clicked or is there any by pass for this?
```
// How to use of your requested feature
```

### PLATFORMS

- [x] Android
- [x] iOS
- [ ] UWP
### _****_

**Comment by amay077** [comment]
Sorry I can't understand your question.
Please show me code or screenshot for your question?

**Comment by lubiepomaranczki** [comment]
@amay077 from my understanding, @JitendraEpicomm has let's say 2 buttons within InfoWindow eg. call location & navigate to the location. He wants to know which button was clicked: call or navigate.

My answer: it's possible on native Android, so it should also be possible on Xamarin. But with usage of Amay's package it won't be that easy. [Here](https://stackoverflow.com/questions/14123243/google-maps-android-api-v2-interactive-infowindow-like-in-original-android-go/15040761#15040761) you can find a way how to do it on Android.

**Comment by amay077** [comment]
Yes, we does not support custom InfoWindow.
