### ISSUE TITLE
Get current zoom value

### ISSUE THREAD

**Issue by sbron** [amay077/Xamarin.Forms.GoogleMaps#575]
Hello,
I would like a property to get the current zoom of the map.

When I click on the + or - button, the map is redrawing. I would get the value of the zoom. 

- [x] Android
- [X ] iOS
- [ ] UWP

**Comment by lubiepomaranczki** [comment]
You can use **_CameraPosition.Zoom_** which gives the current zoom of the map. 
Or did I misunderstand your question @sbron?
