### ISSUE TITLE
Map VisibleRegion.Radius changes every time

### ISSUE THREAD

**Issue by prajithmp** [amay077/Xamarin.Forms.GoogleMaps#58]
when i set the map region like
MyMap.MoveToRegion(MapSpan.FromCenterAndRadius(position, Distance.FromMeters(100)));

next time when i call MyMap.VisibleRegion.Radius , it get change like 124 meters.

how can get the previous zoom level, or can i get zoom changed event.

**Comment by amay077** [comment]
I have a plan to implements  [GoogleMap.OnCameraMoveListener](https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap.OnCameraMoveListener) and [CameraPosition](https://developers.google.com/android/reference/com/google/android/gms/maps/model/CameraPosition) in #7 .
Then you can subscribe zoom changed event.
Please wait for a while.

**Comment by prajithmp** [comment]
sure, thanks

**Comment by amay077** [comment]
I close issue because this is duplicate of #7 .
Please check #7 .
