### ISSUE TITLE
[Question] Is InitialCameraUpdate bindable?

### ISSUE THREAD

**Issue by stesvis** [amay077/Xamarin.Forms.GoogleMaps#580]
### VERSIONS

* Xamarin.Forms.GoogleMaps - 3.0.4
* Xamarin.Forms - 3.3.0.912540

My goal is to bind InitialCameraUpdate to a property in my ViewModel, is it possible?
I am not able to make it work:

```
<maps:Map x:Name="map" InitialCameraUpdate="{Binding Coordinate}"
                              HorizontalOptions="FillAndExpand" HeightRequest="300" />
```

**Comment by lubiepomaranczki** [comment]
I believe [here](https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/ebf27498400c56a1812fba008acdef4871e50524/Xamarin.Forms.GoogleMaps/Xamarin.Forms.GoogleMaps/Map.cs) you have an answer. Line: 37 & 171 😎
