### ISSUE TITLE
Rotating car and map 

### ISSUE THREAD

**Issue by JitendraEpicomm** [amay077/Xamarin.Forms.GoogleMaps#581]
### SUMMARY

Rotating car on map according to the path received from google API
### DETAILS

I Amay, Thanks for the fantastic package. So I'm developing navigation application. I that application, I would like to navigate  and rotate car on the map according to the path I have. Can you please add this feature or is there any work out for this.
```


### PLATFORMS

<!-- which platform do you want? -->

- [x] Android
- [x] iOS
- [x] UWP

**Comment by amay077** [comment]
Maybe you can use ``Map.AnimateCamera()`` with ``CameraUpdateFactory`` and ``CameraUpdate`` .

https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/bc4a52673732195b15900c73d791b9ecb3c65433/XFGoogleMapSample/XFGoogleMapSample/CameraPage.xaml.cs#L83-L93

But I think it is difficult to making like a car navigation apps.

**Comment by jannikscho** [comment]
Hey @JitendraEpicomm,

I have a simple suggestion for you ...
The pin position is updated based on the current position...
the more you query the GPS data, the smaller and more accurate the steps that your pin jumps on the map.

If you just want to turn the pin in the direction of travel,
you just need to query the compass values from your device ​​(for example with Xamarin.Essentials.Compass) and rotate the pin accordingly via Pin.Rotation = compass_value.

If you want to rotate the map, as with Google Maps navigation, you can also turn the map with Map.MoveCamera accordingly. The bearing property must then receive the compass value.

Important: do not use Map.AnimateCamera to rotate the map in this particular case as the position and device orientation may change faster than the animation is finished. This would make everything jerk ...

Here's an example with Xamarin.Forms.Essentials:

//Starting Compass:

`private void StartCompass()
{
	if (!Compass.IsMonitoring)
    {
		Compass.ReadingChanged += OnCompassChanged;
        Compass.Start(SensorSpeed.Game, true);
	}
}`


// Stop Compass

`private void StopCompass()
{
	if (Compass.IsMonitoring)
    {
		Compass.Stop();
    }
}`

// CompassChangedEvent

`private void OnCompassChanged(object sender, CompassChangedEventArgs e)
{
        // If you want to rotate the map...
	if (MAP_ROTATION_ENABLED)
        {
		// map rotates with your device direction
                map.MoveCamera(new CameraPosition(YOUR-LOCATION, YOUR-ZOOM, e.Reading.HeadingMagneticNorth, YOUR-TILT));
        }
        // pin always rotates (if pin.Flat = true)
	Device.BeginInvokeOnMainThread(()=>
	{
		pin.Rotation = e.Reading.HeadingMagneticNorth;
	});
}`

I do it in my app as well and it works fine.
The above code is for illustration only and is untested.
In my code are still too many other functions in it, which have nothing to look for here now ...

I hope it helps you...



Jannik
