### ISSUE TITLE
Circle is not filled every time when changing values

### ISSUE THREAD

**Issue by Sonnenspeer** [amay077/Xamarin.Forms.GoogleMaps#583]
### VERSIONS

* Xamarin.Forms.GoogleMaps - 3.0.4
* Xamarin.Forms - 3.4.0.925479-pre1

### PLATFORMS

[x] Android
[ ] iOS
[ ] UWP

### ACTUAL BEHAVIOR

After creating a circle with a filled color the circle is displayed correct at first time rendering. But when changing the position and radius of the circle then the circle will not be filled anymore. After a few changes in position and radius the circle will be filled once again automatically for a very short time and then again it will be not filled even there was no change in fill color.

So the filling is not happening in the most of times.

I use a circle to display the accuracy of a position for a pin that represents a custom user. The circle position and radius values therefore changing often. The map is using custom tiles.

### EXPECTED BEHAVIOR

The circle should be filled every time the circle is new rendered.

**Comment by amay077** [comment]
I can not reproduce it.
I feel works fine.

![Untitled7](https://user-images.githubusercontent.com/401369/54611723-daee9a80-4a9a-11e9-8fbc-37e983ce11bd.gif)

My code is listed below:

```csharp
// Add Circles
var circle1 = new Circle();
circle1.StrokeWidth = 10f;
circle1.StrokeColor = Color.Red;
circle1.FillColor = Color.FromRgba(255, 0, 0, 160);
circle1.Center = new Position(35.85, 140.23);
circle1.Radius = Distance.FromKilometers(8);
map.Circles.Add(circle1);

buttonUpdateCircle.Clicked += (sender, e) =>
{
    circle1.Radius = Distance.FromMeters(circle1.Radius.Meters * 0.8d);
    circle1.Center = new Position(circle1.Center.Latitude, circle1.Center.Longitude + 0.02d);
};
```

Could you provide small code for reproduce?
