### ISSUE TITLE
Problems with custom Pins

### ISSUE THREAD

**Issue by stesvis** [amay077/Xamarin.Forms.GoogleMaps#584]
### VERSIONS

* Xamarin.Forms.GoogleMaps - 3.0.4
* Xamarin.Forms - 3.3.0.912540

### PLATFORMS

- [x] Android
- [x] iOS
- [ ] UWP

### ACTUAL BEHAVIOR

> Unhandled Exception:
> 
> Java.Lang.IllegalArgumentException: Failed to decode image. The provided image must be a Bitmap.

### EXPECTED BEHAVIOR

I would expect to see the map pin using my custom image.

### HOW TO REPRODUCE

1. I placed ic_vgpin.png in the drawable (android) and Resources (iOS) folder.
2. Tried Build Action = _AndroidAsset_ and _AndroidResource_
3. Ran the code snippet below

```csharp
var pin = new Pin()
                    {
                        Type = PinType.Place,
                        Label = geoLocation.FormattedAddress,
                        Address = geoLocation.FormattedAddress,
                        Position = new Position(geoLocation.Latitude, geoLocation.Longitude),
                        Rotation = 15f,
                        Icon = BitmapDescriptorFactory.FromBundle("ic_vgpin.png"),
                        IsVisible = true
                    };
                    map.Pins.Add(pin);
                    await map.MoveCamera(CameraUpdateFactory.NewPositionZoom(new Position(geoLocation.Latitude, geoLocation.Longitude), 13));
```

Is it ok to place my pin image in the drawable/Resources folder?
Anything else i am missing?

**Comment by fbede4** [comment]
I've placed the icon in the "AndroidProject"/Assets folder, and it works fine for me

**Comment by stesvis** [comment]
Thanks!
That was it, and in iOS it goes in the root folder.

**Comment by marciordonez** [comment]
Remember to set Build Action file property to "AndroidAsset"

![image](https://user-images.githubusercontent.com/5067254/65797925-bf99d180-e146-11e9-8f20-1eb1fe936f15.png)

**Comment by mr5z** [comment]
Why can't it be put into drawables folder?
It would be better if it's there since we can support multiple resolutions.

**Comment by thomasonb** [comment]
Yeah I'm with @mr5z on this one. It should use the drawables folder instead. I have a custom image in my drawables folder so we can support multiple resolutions.
