### ISSUE TITLE
Is it possible to move a pin with the camera?

### ISSUE THREAD

**Issue by fbede4** [amay077/Xamarin.Forms.GoogleMaps#585]
### SUMMARY
Is it possible to auto move a pin with the camera?

### DETAILS
Hi, I would like an auto moving pin, that follows the center of the camera.
Is that possible?
Thank you in advance!

- [x] Android
- [x] iOS
- [ ] UWP

**Comment by Sonnenspeer** [comment]
Hi. More or less this should be possible. 

You could use the "CameraMoving" event to get informed about a new camera position. There you can update the position of the pin with the cameras target position which should point to the center if I'm not wrong. 

This is only a suggestion and not tested.

**Comment by fbede4** [comment]
Hi, thanks for your answer, yes it is possible with the cameramoving event, but it doesn't seem very efficient , the pin keeps moving, and tries to follow movement, when I just want it to stay in the middle of the screen.. I'm thinking about placing an icon in the middle of the map, and just use the camera target position as the (non-existent) icon's position.

**Comment by AshishSharma788** [comment]
how to possible this thing in ios

**Comment by AshishSharma788** [comment]
??
