### ISSUE TITLE
Map suddenly stops showing

### ISSUE THREAD

**Issue by rubenc57** [amay077/Xamarin.Forms.GoogleMaps#586]
### VERSIONS

* Xamarin.Forms.GoogleMaps - 2.3.0
* Xamarin.Forms - 3.0.0.482510
* 

### PLATFORMS

- [x ] Android
- [] iOS
- [ ] UWP

### ACTUAL BEHAVIOR
It was showing a map correctly
But suddenly it stops working

### ACTUAL SCREENSHOTS/STACKTRACE

![error_image](http://files.winsir.net/images/gmss_error.png) 

### EXPECTED BEHAVIOR

It should show the map

**Comment by rubenc57** [comment]
I Have updated to

VERSIONS
Xamarin.Forms.GoogleMaps - 3.0.4
Xamarin.Forms - 3.3.0.967583

and the same result, no map showing...

**Comment by rubenc57** [comment]
Now is crashing
I receive theses errors:
Unhandled Exception:

Java.Lang.SecurityException: my location requires permission ACCESS_FINE_LOCATION or ACCESS_COARSE_LOCATION occurred

Even though I have those permissions set

**Comment by amay077** [comment]
Could you try our sample apps?

https://github.com/amay077/Xamarin.Forms.GoogleMaps/tree/master/XFGoogleMapSample

**Comment by rubenc57** [comment]
I cannot make the sample apps to work
I receive this error when compiling for android

Error	CS0103	The name 'Variables' does not exist in the current context	XFGoogleMapSample.Droid

In MyApp.cs

``    [MetaData("com.google.android.maps.v2.API_KEY",
              Value = Variables.GOOGLE_MAPS_ANDROID_API_KEY)]
``

But I'm not a new user, my app was working and it stops showing the map
You made a modification that I'm not aware of

**Comment by rubenc57** [comment]
OK, I made sample app for android run, but same result, no map

**Comment by rubenc57** [comment]
Ok, it turned out to be my api key
It is working now
