### ISSUE TITLE
Map Shifts to right corner when we tap on Pin both iOS and Android

### ISSUE THREAD

**Issue by Shivaprabhu049** [amay077/Xamarin.Forms.GoogleMaps#588]
### VERSIONS

* Xamarin.Forms.GoogleMaps - x.x.x
* Xamarin.Forms - x.x.x
* 

### PLATFORMS

- [x] Android
- [x] iOS
- [ ] UWP

### ACTUAL SCREENSHOTS/STACKTRACE

![something_image](your_image.png) 

```
// paste stacktrace
```

### HOW TO REPRODUCE

1. 
2. 
3. 

```csharp
// code for reproduce
```

**Comment by amay077** [comment]
I can't reproduce.
Could you show me detail informations?
