### ISSUE TITLE
How to pin fixed when draged map like Uber. 

### ISSUE THREAD

**Issue by matanist** [amay077/Xamarin.Forms.GoogleMaps#589]
### DETAILS

```
// How to use of your requested feature
```
I dragged map and I want pin fixed center of map. And fixed pin when drag stopped Like Uber. 
### PLATFORMS

- [x] Android
- [x] iOS
- [ ] UWP

**Comment by varun-raj** [comment]
Dont create a map pin, instead create a Image element and place it over the map relatively. Thats much efficient approach.
