### ISSUE TITLE
map cluster enable?

### ISSUE THREAD

**Issue by halukmy** [amay077/Xamarin.Forms.GoogleMaps#593]
### SUMMARY

map cluster pinch zoom group away, pinch out gropus together

do you planing or already have clustering?

thanks

**Comment by leaguefun** [comment]
https://github.com/mierzynskim/Xamarin.Forms.GoogleMaps/tree/clustering
There had experts built a branch with map clustering, by the way, its already left behind with current version of the main trunk ... looking forward to see this can merge into the repo  m(-_-)m
