### ISSUE TITLE
When pin startdragging, pin is slide

### ISSUE THREAD

**Issue by haya1992** [amay077/Xamarin.Forms.GoogleMaps#594]
### VERSIONS

* Xamarin.Forms.GoogleMaps - 3.0.4
* Xamarin.Forms - 3.4.0.1008975
* 

### PLATFORMS

- [x] Android
- [ ] iOS
- [ ] UWP

### ACTUAL BEHAVIOR

こんにちは。
マップ上にピンを配置し、ドラッグを開始しようと、ピン上でマウスを押下するとピンが右上に移動します。（シミュレータ上です。実機ではまだ試していません。）
これは、仕様なのでしょうか。

提供しているサンプル(XFGoogleMapSample)にて、東京にピンを置く例がありますが、

                pinTokyo = new Pin()
                {
                    Type = PinType.Place,
                    Label = "Tokyo SKYTREE",
                    Address = "Sumida-ku, Tokyo, Japan",
                    Position = new Position(35.71d, 139.81d),
                    Rotation = 33.3f,
                    Tag = "id_tokyo",
                    IsDraggable = true,　　　　<----これを追加
                    IsVisible = switchIsVisibleTokyo.IsToggled
                };

を追加しても同様の動きになります。

よろしくお願いいたします。

**Comment by amay077** [comment]
返事おそくなってすいません。

ピンを長押しすると、「上に」移動しませんかね？
これは Google Maps Android SDK も同じですが、ピンの移動先が見やすいように、敢えてマウスカーソスから離しているのだと思います。

![Untitled7](https://user-images.githubusercontent.com/401369/54862224-d10ab700-4d7a-11e9-830b-5cead8462983.gif)

**Comment by haya1992** [comment]
こんにちは。
実機でも確認しました。
上に移動したほうが、操作しやすいですね。
そこらへんを考慮した実装だなぁとおもいました。
