### ISSUE TITLE
Map Not Appear

### ISSUE THREAD

**Issue by AhmedAdelGadElkareeem** [amay077/Xamarin.Forms.GoogleMaps#599]
Map Not Appear 
![map](https://user-images.githubusercontent.com/30314037/52238203-1f9be900-28d4-11e9-8ab4-eb2e5796cbb5.PNG)

using this code `myMap.MoveToRegion(MapSpan.FromCenterAndRadius(new Position(24.716632, 46.667862),
                            Distance.FromKilometers(150)));
                myMap.Pins.Add(new Pin()
                {
                    Position = new Position(24.716632, 46.667862),
                    Label = "Your Location",
                    Address = "Location"
                });`

**Comment by Sonnenspeer** [comment]
You need to add an Google Maps API key and have an internet connection.

**Comment by AhmedAdelGadElkareeem** [comment]
@Sonnenspeer  i add Map Api key and have internet connection

**Comment by Sonnenspeer** [comment]
Ugh, could be other things:
- API key not valid.
- MapStyle is None

You can try to debug the initialization process with the source code included as a project instead of a nuget.

**Comment by amay077** [comment]
Maybe API key is nod valid.
Please check your Application Output.
Google maps SDK reports following logs. 
```
[Google Maps Android API] Authorization failure.  Please see https://developers.google.com/maps/documentation/android-api/start for how to correctly set up the map.
[Google Maps Android API] In the Google Developer Console (https://console.developers.google.com)
[Google Maps Android API] Ensure that the "Google Maps Android API v2" is enabled.
[Google Maps Android API] Ensure that the following Android Key exists:
[Google Maps Android API] 	API Key: <your api key>
[Google Maps Android API] 	Android Application (<cert_fingerprint>;<package_name>): D4:C0:D0:DB:76:66:92:F9:42:FD:F6:3D:2D:BC:97:63:2A:A6:D2:41;net.amay077.xfgooglemapsample
```
