### ISSUE TITLE
visible region changed event 

### ISSUE THREAD

**Issue by kitkat14** [amay077/Xamarin.Forms.GoogleMaps#60]
I checked the documentation but I could not find an event for this.

Every time the user moves the map it should fire an event with the visible region as parameter.
This is handy so that you can add pins at runtime.

**Comment by amay077** [comment]
I have a plan to implements  [GoogleMap.OnCameraMoveListener](https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap.OnCameraMoveListener) and [CameraPosition](https://developers.google.com/android/reference/com/google/android/gms/maps/model/CameraPosition) in #7 .
Then you can subscribe visible region changed.
Please wait for a while.

**Comment by kitkat14** [comment]
Cool :+1:  I think another feature to make the map really good is ofcourse drawing the direction from user to some point on the map.

**Comment by JeanCollas** [comment]
This should be completely solved here https://github.com/amay077/Xamarin.Forms.GoogleMaps/pull/151

**Comment by amay077** [comment]
OMG... 

[GoogleMap.setOnCameraChangeListener](https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap.html?setOnCameraChangeListener(com.google.android.gms.maps.GoogleMap.OnCameraChangeListener)) is deprecated.

I should consider to create events listed bellow:

* Map.CameraMoveStarted
* Map.CameraMoved
* Map.CameraMoveCancelled
* Map.CameraIdled

**Comment by amay077** [comment]
``GoogleMap.setOnCameraChangeListener`` is deprecated but new events (e.g. ``CameraMoveStarted``) can not use in Xamarin.Forms 2.3.x .

So I'll keep support ``CameraChanged`` event and will support new events in next major version.
