### ISSUE TITLE
Anchor is initialized when updating Pin  Android

### ISSUE THREAD

**Issue by Yanc35** [amay077/Xamarin.Forms.GoogleMaps#609]
### VERSIONS

* Xamarin.Forms.GoogleMaps - 3.0.4
* Xamarin.Forms - 3.5.0.169047

### PLATFORMS

- [x] Android
- [ ] iOS
- [ ] UWP

### ACTUAL BEHAVIOR

Anchor is initialized when updating Pin.

### ACTUAL SCREENSHOTS/STACKTRACE

Anchor = new Point(0.5, 0.5)
![Anchor1](https://user-images.githubusercontent.com/40679902/54185391-3d202c00-44ec-11e9-94ac-f09b862bc623.png)
↓
update  Icon = RedCircle  →  Anchor is initialize (0.5, 1.0)
![Anchor2](https://user-images.githubusercontent.com/40679902/54185396-40b3b300-44ec-11e9-80c4-d6330d781f8f.png)

### EXPECTED BEHAVIOR

update  Icon = RedCircle
![Anchor3](https://user-images.githubusercontent.com/40679902/54185409-47422a80-44ec-11e9-9f12-fdd2de298065.png)

### HOW TO REPRODUCE

```csharp
// code for reproduce
Xamarin.Forms.GoogleMaps.Android/Logics/PinLogic.cs

protected override void OnUpdateIcon(Pin outerItem, Marker nativeItem)
{
    if (outerItem.Icon != null && outerItem.Icon.Type == BitmapDescriptorType.View)
    {
        // If the pin has an IconView set this method will convert it into an icon for the marker
        TransformXamarinViewToAndroidBitmap(outerItem, nativeItem);
    }
    else
    {
        var factory = _bitmapDescriptorFactory ?? DefaultBitmapDescriptorFactory.Instance;
        var nativeDescriptor = factory.ToNative(outerItem.Icon);
        nativeItem.SetIcon(nativeDescriptor);
        nativeItem.SetAnchor(0.5f, 1f);
        nativeItem.SetInfoWindowAnchor(0.5f, 0f);
    }
}

↓

//        nativeItem.SetAnchor(0.5f, 1f);
//        nativeItem.SetInfoWindowAnchor(0.5f, 0f);
```
Is there a situation where the last two lines are needed?
need the branch condition?

**Comment by amay077** [comment]
A-ha, I think no need last two lines too.
Could you send me Pull request?
