### ISSUE TITLE
Check a Position is inside Visible region

### ISSUE THREAD

**Issue by prajithmp** [amay077/Xamarin.Forms.GoogleMaps#61]
Hi ,

 is there any method to check a Position is Present inside Map's visible region ?

**Comment by amay077** [comment]
No, 
But I want to make ``IsContainsVisibleRegion(Position)`` .
Check this thread!

**Comment by deextercz** [comment]
I have my own class which extends Map class

`        public bool Contains(Position point)
        {
            var bounds = new Bounds(GetMapVisibleSouthWest(), GetMapVisibleNorthEast());

            if (bounds.Contains(point))
            {
                return true;
            }

            return false;
        }

        private Position GetMapVisibleSouthWest()
        {
            var halfHeightDegrees = VisibleRegion.LatitudeDegrees / 2;
            var halfWidthDegrees = VisibleRegion.LongitudeDegrees / 2;

            var left = VisibleRegion.Center.Longitude - halfWidthDegrees;
            var bottom = VisibleRegion.Center.Latitude - halfHeightDegrees;
            return new Position(bottom, left);
        }

        private Position GetMapVisibleNorthEast()
        {
            var halfHeightDegrees = VisibleRegion.LatitudeDegrees / 2;
            var halfWidthDegrees = VisibleRegion.LongitudeDegrees / 2;

            var right = VisibleRegion.Center.Longitude + halfWidthDegrees;
            var top = VisibleRegion.Center.Latitude + halfHeightDegrees;
            return new Position(top, right);
        }`

So basicaly Bounds class contains this feature, but will you still add this feature?
