### ISSUE TITLE
Pins is not visible on Samsung Galaxy Tab S8

### ISSUE THREAD

**Issue by jocontacter** [amay077/Xamarin.Forms.GoogleMaps#615]
### VERSIONS

* Xamarin.Forms.GoogleMaps - 3.0.4/3.0.5
* Xamarin.Forms - 3.5.0.129452

### PLATFORMS

- Android

### ACTUAL BEHAVIOR

Pins created with all methods:
```
Icon = BitmapDescriptorFactory.FromBundle("pin.png")
Icon = BitmapDescriptorFactory.DefaultMarker(Color.Red)
Icon = BitmapDescriptorFactory.FromView(new PinView(discount, isHot))
```
works on emulator and my devices, but dont work on customer device(Samsung Galaxy Tab S8 Android 9.0)

"pin.png" added to assets as AndroidAsset and to Resources/Drawables as AndroidResource. The second is using in custom PinView. All 3 cases working as expected on emulators(Android 8.0, 8.1 and 9.0)
I adding Pins exactly after OnAppearin() method after api call

### EXPECTED BEHAVIOR

Expected the pins is appearing.

### HOW TO REPRODUCE

1.  Run Google maps sample on Samsung Galaxy S8
2.  Search for pins with magnifier

Sorry for my bad english, i just started study

**Comment by jocontacter** [comment]
Sorry guys, the reson was in locale and wrong parsing. My devices and emulator with En-us locale but the customer device is Ru-ru locale, so 30.536 needs to become 30,536 when received from server and parsing. 2 days wasted on it.

**Comment by amay077** [comment]
No problem,  Good for you!
