### ISSUE TITLE
android application closes when map.MyLocationEnabled = true

### ISSUE THREAD

**Issue by jocontacter** [amay077/Xamarin.Forms.GoogleMaps#618]
### VERSIONS

* Xamarin.Forms.GoogleMaps - 3.0.5
* Xamarin.Forms - 3.5.0.169
* 

### PLATFORMS

- [x] Android
- [ ] iOS - not tested

### ACTUAL BEHAVIOR

application closes without exceptions when i make `map.IsShowingUser = true` or `map.MyLocationEnabled = true`

### HOW TO REPRODUCE

```csharp
var status = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Location);
if (status != PermissionStatus.Granted)
{
	var results = await CrossPermissions.Current.RequestPermissionsAsync(Permission.Location);
	if (results.ContainsKey(Permission.Location))
		status = results[Permission.Location];
}

if (status == PermissionStatus.Granted)
{
	map.IsShowingUser = true;
	// the same result:
	//map.MyLocationEnabled = true;
}
```

**Comment by amay077** [comment]
Is there anyone has same issue?

Or do you have more detail information? > @jocontacter

**Comment by jocontacter** [comment]
> Is there anyone has same issue?
> 
> Or do you have more detail information? > @jocontacter

I think it was just a coincidence.

**Comment by amay077** [comment]
Okay I close it. 👍
