### ISSUE TITLE
Binding to a Pin's Tag property

### ISSUE THREAD

**Issue by gabrielbunselmeyer** [amay077/Xamarin.Forms.GoogleMaps#622]
### SUMMARY

Not exactly a feature request, but:

The Tag property of Pin is typed as an object. So, when using the newly added option to bind the pins directly in XAML, the binding for Tag is the _actual bind to it_.

As in, the binding isn't the int object I'm trying to bind as an id, but the Xamarin.Forms.Binding object referring to it.

![image](https://user-images.githubusercontent.com/29930410/56760186-0e46d800-6771-11e9-92b0-ac0b933771f9.png)

### DETAILS

Changing Tag to int would fix this for me (but, as Pin is sealed, I can't implement it). However, as far as I understand, Tag's supposed to be any kind of identification for the pin (any type), so this may not be the most ideal solution.

### PLATFORMS

- [x] Android
- [x] iOS
- [ ] UWP

**Comment by aherrick** [comment]
Hi @gabrielbunselmeyer did you ever find a solution here? thanks!

**Comment by gabrielbunselmeyer** [comment]
Hey, sorry for the delay @aherrick. I didn't, no. Just had to do whatever it was I wanted without using a binding, if I remember correctly. Has been a while since I left that project.

This pull request would help, though: #701.

**Comment by asadullahqmr** [comment]
This never was resolved was it? Would be helpful to have an additional space to store values to the pin without showing a label or address...
