### ISSUE TITLE
Create function to set position and zoom to show all markers

### ISSUE THREAD

**Issue by juniorjrjl** [amay077/Xamarin.Forms.GoogleMaps#624]
### SUMMARY

a google maps api have this function, you pass a array with coordinates and function calculates and set coordinates to show all markers

see about this in this link:
(https://developers.google.com/maps/documentation/javascript/reference/map#Map.fitBounds)

### DETAILS

In my job I'm developing a app who use map to show a vehicles' trackers in a map who refresh each 3 minutes, we use a function fitBounds in web application but I'm have problems in app.
thak you :)

### PLATFORMS

- [x] Android
- [x] iOS
- [x] UWP

**Comment by amay077** [comment]
You can use listed code.

```
Position[] positions = /* your pin's positions */;
Bounds bounds = Bounds.FromPositions(positions);
await map.MoveCamera(CameraUpdateFactory.NewBounds(bounds, 10));
```

**Comment by juniorjrjl** [comment]
It worked, thank you :)
