### ISSUE TITLE
Would like to turn off indoor maps

### ISSUE THREAD

**Issue by gadzair** [amay077/Xamarin.Forms.GoogleMaps#63]
Currently by default the Google Maps are showing indoor levels. For my app I really don't want it, and would like an API in Forms to turn it off.

**Comment by amay077** [comment]
Sure!
I will make ``Map.IndoorLevelPickerEnabled`` property that is wrapping these APIs.

* [Android][UiSettings  |  Google APIs for Android  |  Google Developers](https://developers.google.com/android/reference/com/google/android/gms/maps/UiSettings.html?hl=ja#setIndoorLevelPickerEnabled(boolean))
* [iOS][GMSUISettings Class Reference  |  Google Maps SDK for iOS  |  Google Developers](https://developers.google.com/maps/documentation/ios-sdk/reference/interface_g_m_s_u_i_settings.html?hl=ja#a26f67288459bf6d48b327394193233bd)

Also, I have plan to fully support UiSettings.

* #8 UiSettings class support

**Comment by amay077** [comment]
And I should implement ``Map.IndoorEnabled`` like this:

* [isIndoorEnabled  / GoogleMap  |  Google APIs for Android  |  Google Developers](https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap?hl=ja#isIndoorEnabled())

**Comment by amay077** [comment]
Current status:

## TASKS

* [ ] Android implementation
* [ ] iOS implementation
* [ ] UWP implementation
* [ ] Add samples

**Comment by amay077** [comment]
I released [v1.8.0](https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/1.8.0) that contained it.
