### ISSUE TITLE
Allow the user to demarcate area with polygon

### ISSUE THREAD

**Issue by izefler** [amay077/Xamarin.Forms.GoogleMaps#64]
Hi, first I want to congratulate him for the great work! Well, now I need your help as the web version has a tool to draw an area, allowing the user to create the area in Polygon. Can you help me, how can I do this? Thank you.

**Comment by amay077** [comment]
Thanks, 😄 

I found API in Google Maps Android API.

* [Android] [GoogleMap.setLatLngBoundsForCameraTarget(LatLngBounds)](https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap.html?hl=ja#setLatLngBoundsForCameraTarget(com.google.android.gms.maps.model.LatLngBounds))

> Specifies a LatLngBounds to constrain the camera target, so that when users scroll and pan the map, the camera target does not move outside these bounds.

This API seems fits your request.
But I can't found similar API in [Google Maps iOS SDK](https://developers.google.com/maps/documentation/ios-sdk/reference/).

I guess this feature does not implemented yet in iOS.
The only thing we can do is to wait for Google's implement.

In other way, I have plan to support visible region changed event(#60).
You will can subscribe region changes, if region is out of bounds then re-call ``Map.MoveToRegion``.
