### ISSUE TITLE
How to highlight a pin programmatically?

### ISSUE THREAD

**Issue by GiuseppePennisi** [amay077/Xamarin.Forms.GoogleMaps#644]
Hi, how can I highlight a pin programatically, simulating a click on it and showing its label?

**Comment by amay077** [comment]
Yes you can!

You can set ``Map.SelectedPin`` to your pin to highlighting a pin.

https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/19b140bfc80e80fe676ea98266c9bb81563996a2/XFGoogleMapSample/XFGoogleMapSample/PinsPage.xaml.cs#L98

**Comment by GiuseppePennisi** [comment]
Thanks! The solution to my problem was simpler than I thought!
