### ISSUE TITLE
Distance between address

### ISSUE THREAD

**Issue by marcosgerene** [amay077/Xamarin.Forms.GoogleMaps#646]
Hi,

I just need calculate the distance between my location and an address. 
I just need time and distance. 
I don't need navigation, maps, multiple routes or anything.

How can I do this?

Thanks

**Comment by marcosgerene** [comment]
@amay077 

My issue has recieve "enhancement" label, so the library no answer this, right?

Do you have a forecast for implementation?

Should I wait for this or is it better to look another solution?

Thanks

**Comment by amay077** [comment]
Yes I will add ``Position.ToDistance(Position)`` method.
This method like [Android's Location.distanceTo method](https://developer.android.com/reference/android/location/Location.html#distanceTo(android.location.Location)) .

But this method does NOT provide Address to Lat/Lon conversion.

**Comment by marcosgerene** [comment]
@amay077 

If I convert the address to lat / lon and call this method, will the result be the distance traveled by a car or straight?

I need the distance traveled by a car ...

**Comment by linda-dge** [comment]
Once you have the lat/lon there is a method in Xamarin Essentials Location

Xamarin.Essentials.Location.CalculateDistance(new
Xamarin.Essentials.Location(coord1.Latitude, coord1.Longitude), new
Xamarin.Essentials.Location(coord2.Latitude, coord2.Longitude),
Xamarin.Essentials.DistanceUnits.Kilometers);

or old faithful calculations like Haverstine or Great Circle

*Linda Rawson*


ᐧ

**Comment by linda-dge** [comment]
Driving distance is a different story.

You use Google's api.

https://developers.google.com/maps/documentation/distance-matrix/intro

*Linda Rawson*

ᐧ

**Comment by marcosgerene** [comment]
@linda-dge 

>Driving distance is a different story.

Yeah! So I question about this library...

Thanks

**Comment by marcosgerene** [comment]
@linda-dge @amay077 


The google API has a cost, my client just needs a forecast to know how to order travels by closest to farthest.

This solve my issue:

>Xamarin.Essentials.Location.CalculateDistance(new
Xamarin.Essentials.Location(coord1.Latitude, coord1.Longitude), new
Xamarin.Essentials.Location(coord2.Latitude, coord2.Longitude),
Xamarin.Essentials.DistanceUnits.Kilometers);

Thanks

**Comment by amay077** [comment]
Thanks @linda-dge , @marcosgerene 

``Xamarin.Essentials.Location.CalculateDistance`` is the answer!

 I don't add Position.ToDistance(Position) method in Xamarin.Forms.GoogleMaps.

**Comment by marcosgerene** [comment]
@amay077  @linda-dge 
Thanks!!
