### ISSUE TITLE
Pin Gif

### ISSUE THREAD

**Issue by hoangwy** [amay077/Xamarin.Forms.GoogleMaps#649]
Hi
Can we make something like this
https://tenor.com/view/google-maps-pin-location-london-area-gif-14701030
Thanks
### PLATFORMS

- [x] Android
- [x] iOS
- [ ] UWP

**Comment by amay077** [comment]
No we can't.
Because Native Google Maps SDK for Android/iOS does not support animation GIF.

**Comment by lbshopping** [comment]
Isn't it possible to do something like this:
[https://stackoverflow.com/questions/5979676/gif-marker-google-maps](url)
