### ISSUE TITLE
Android custom icon not showing up

### ISSUE THREAD

**Issue by kitkat14** [amay077/Xamarin.Forms.GoogleMaps#65]
I use the exact same example like the example program. (btw its not working) 
I put the files for iOS in resources and for Android in Assets.

iOS works perfectly but the one for Android doesnt show anything. (the maps and everything works)

**Comment by amay077** [comment]
Is [XFGoogleMapSample](https://github.com/amay077/Xamarin.Forms.GoogleMaps/tree/master/XFGoogleMapSample) not working?

> I put the files for iOS in resources and for Android in Assets.

Please check your asset's build action is "AndroidAsset".

And,
Please check can read asset in Xamarin.Android.
see - [Using Android Assets - Xamarin](https://developer.xamarin.com/guides/android/application_fundamentals/resources_in_android/part_6_-_using_android_assets/).

**Comment by kitkat14** [comment]
Thanks didnt know you have to do that for xamarin 👍
