### ISSUE TITLE
Label not showing on pin 

### ISSUE THREAD

**Issue by rubenc57** [amay077/Xamarin.Forms.GoogleMaps#651]
### VERSIONS

* Xamarin.Forms.GoogleMaps - 3.2.1
* Xamarin.Forms - 4.2.0
* 

### PLATFORMS

- [x] Android
- [x] iOS
- [ ] UWP

### ACTUAL BEHAVIOR

Label is not showing on the pin like normal behavior from googlemaps
https://developers.google.com/maps/documentation/javascript/examples/marker-labels

Thank you for your support
rubenc

**Comment by AnthonyLatty** [comment]
Some Code snippet would be helpful to better assist you. 

> This how you generally add a label to a location

```
var currentPin = new Pin
{
   Type = PinType.SearchResult,
   Position = new Position(Latitude, Longitude),
   Label = "Current location"
};
```

**Comment by rubenc57** [comment]
Yes I'm doing that:

                var pin = new Pin
                {
                    Type = PinType.SearchResult,
                    Position = new Position(pos.Latitude, pos.Longitude),
                    Label = p.Id,
                    Address = p.Address,
                    Tag = p.AddressID,
                };

But the label only shows in the infowindow...

**Comment by AnthonyLatty** [comment]
Ensure the value `Label = p.Id` is of type string.

**Comment by rubenc57** [comment]
Yeah it is, 1 char string

**Comment by AnthonyLatty** [comment]
Ok to test that it is not the plugin try adding `Label = "test"` if that display the label "test" then we can assume it the data that is being send to `Label = p.Id`

**Comment by rubenc57** [comment]
GoogleMaps documentation says the you can only use a single char string or won't show

**Comment by rubenc57** [comment]
Same result

var pin = new Pin
            {
                Type = PinType.SearchResult,
                Position = new Position(pos.Latitude, pos.Longitude),
                Label = "test", //p.Id,
                Address = p.Address,
                Tag = p.AddressID,
            };

![Screenshot_1568069452](https://user-images.githubusercontent.com/20931876/64571820-4fa3e280-d322-11e9-94ef-667b5c1f8773.png)

**Comment by AnthonyLatty** [comment]
Could you comment out `Address = p.Address` and `Tag = p.AddressID`?

**Comment by rubenc57** [comment]
Same result
var pin = new Pin
{
Type = PinType.SearchResult,
Position = new Position(pos.Latitude, pos.Longitude),
Label = "test", //p.Id,
//Address = p.Address,
//Tag = p.AddressID,
};

**Comment by AnthonyLatty** [comment]
Thats strange..

**Comment by AnthonyLatty** [comment]
Can you submit a small sample so i can take a look to see if its only this project acting up or if its maybe something in your solution.

I just created a replica with the exact nuget packages and everything works fine.

**Comment by AnthonyLatty** [comment]
Console log the value coming from the class `DireccionRootObject` maybe the string value is not being passed to `Label = p.Id` so it wouldnt render on the map

**Comment by AnthonyLatty** [comment]
Can you create an empty project with the nuget packages and test alone, thats what i did and i didnt have an issue.

**Comment by rubenc57** [comment]
I created an empty project with only this nuget pacakges:
NetStandard.Library 2.0.3
Xamarin.Essentials 1.1.0
Xamarin.Forms 4.1.0.555618
Xamarin.Forms.GoogleMaps 3.2.1

In XAML I have
`

        <maps:Map x:Name="MyMap" 
                MapType="Street" 
                VerticalOptions="FillAndExpand"
                HorizontalOptions="FillAndExpand">
        </maps:Map>
`

in cs I have:

`


        public MainPage()
        {
            InitializeComponent();
            Map();
        }

        void Map()
        {
            var dirs = new List<DireccionRootObject>();
            var dir = new DireccionRootObject
            {
                Id = "1",
                Latitud = 24.8191,
                Longitud = -107.373
            };

            dirs.Add(dir);
            dir = new DireccionRootObject
            {
                Id = "2",
                Latitud = 24.8166,
                Longitud = -107.3744
            };
            dirs.Add(dir);

            dirs.Add(dir);
            dir = new DireccionRootObject
            {
                Id = "3",
                Latitud = 24.8173,
                Longitud = -107.3745
            };
            dirs.Add(dir);


            //24.8192707,-107.3743718 //las quintas
            var currentLocation = new Xamarin.Essentials.Location(24.8192707, -107.3743718);

            foreach (var p in dirs)
            {
                double latitud = p.Latitud, longitud = p.Longitud;
                if (latitud == 0 && longitud == 0)
                    continue;
                var pos = new Xamarin.Essentials.Location(latitud, longitud); // Latitude, Longitude

                var pin = new Pin
                {
                    Type = PinType.SearchResult,
                    Position = new Position(pos.Latitude, pos.Longitude),
                    Label = p.Id,
                };

                MyMap.Pins.Add(pin);

                if (currentLocation == null
                    || (currentLocation.Latitude == 0
                    && currentLocation.Longitude == 0)
                    )
                    currentLocation = pos;
            }

            if (currentLocation != null)
                MyMap.InitialCameraUpdate = CameraUpdateFactory.NewPositionZoom
                (
                    new Position(currentLocation.Latitude
                                , currentLocation.Longitude)
                    , 15d);

            MyMap.MyLocationEnabled = true;
            MyMap.UiSettings.MyLocationButtonEnabled = true;
            //MyMap.UiSettings.ZoomControlsEnabled = true;
            //MyMap.UiSettings.ZoomGesturesEnabled = true;
        }
`
and I get the same unwanted result :/

![Screenshot_1568742268](https://user-images.githubusercontent.com/20931876/65065931-9d32d780-d940-11e9-93ce-2e66a62750f7.png)

**Comment by AnthonyLatty** [comment]
The code seems alright, i cant seem to see whats causing it not to render. Can you post a zip with the solution and i will take a look at that and see whats really happening here?

**Comment by rubenc57** [comment]
[App8.zip](https://github.com/amay077/Xamarin.Forms.GoogleMaps/files/3626901/App8.zip)

**Comment by AnthonyLatty** [comment]
The issue you are having is the label not showing but by default the label is showing it is just not displayed. You have to use the SelectedPin method to show the label for a particular pin. I attached a sample with i did showcasing that below.

https://send.firefox.com/download/c58a9bf5463d9450/#Po1pfJdaBiqz4rNbUNuRAQ

**Comment by rubenc57** [comment]
Thank you for your help
That is not my issue, the infowindow it's working fine
What I need is the label appearing on the marker
Please check this link: https://developers.google.com/maps/documentation/javascript/examples/marker-labels

This should be the result in my case:

![Screenshot_1568840194](https://user-images.githubusercontent.com/20931876/65185355-9f6e6200-da24-11e9-96ff-c9e7e5620ac4.png)

**Comment by AnthonyLatty** [comment]
Glad i could help, the title was misleading tho

**Comment by rubenc57** [comment]
So the plugin does not render the label on the marker

I had to make the markers one by one and construct the name dynamically:
marcador1.png marcador2.png... macadorA.png marcacorB.png etc.
If in the future you add this feature would be nice.

Thanks again
