### ISSUE TITLE
[Enhancement] ItemTemplateSelector

### ISSUE THREAD

**Issue by andreas-nesheim** [amay077/Xamarin.Forms.GoogleMaps#654]
### SUMMARY

I would like to use the same ItemTemplateSelector which is accessible through the Xamarin.Forms.Maps API. The pull request for this is here in the official API: https://github.com/xamarin/Xamarin.Forms/pull/5226

### DETAILS

See the documentation for Xamarin.Forms.Maps regarding ItemTemplateSelector: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/map#choose-item-appearance-at-runtime

### PLATFORMS

- [x] Android
- [x] iOS
- [ ] UWP

I might be able to assist with this myself when I have time.

**Comment by amay077** [comment]
Released in https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/3.3.0 .
