### ISSUE TITLE
Fixed screen size circle?

### ISSUE THREAD

**Issue by tbenum** [amay077/Xamarin.Forms.GoogleMaps#659]
### SUMMARY
Would it be possible to add a circle dimension which is fixed size (i.e. 10% of screen width etc) instead of real world size?
### DETAILS

Currently I have to use a pin to pinpoint locations on the map, but I would rather use a circle. If the user zooms in/out, the circle should stay a fixed size (it should not zoom).

```
 circle.Radius = Distance.FromScreenWidthPercent(10);
```

### PLATFORMS

- [x] Android
- [x ] iOS
- [ ] UWP

**Comment by amay077** [comment]
We does not support it.

You can draw circle in your canvas using SkiaSharp.
