### ISSUE TITLE
Default Map Positon

### ISSUE THREAD

**Issue by davidbuckleyni** [amay077/Xamarin.Forms.GoogleMaps#667]
For the life of me I can't see how I set up the default map position when the map firsts start up or does it go to the first marker position.

**Comment by amay077** [comment]
``map.MoveToRegion`` is deprecated.

You can use ``map.InitialCameraUpdate`` property in you Page's constructor or XAML.

https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/f7d61668fe1e022f717617a82239efc519405160/XFGoogleMapSample/XFGoogleMapSample/ShapesPage.xaml.cs#L152

https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/f7d61668fe1e022f717617a82239efc519405160/XFGoogleMapSample/XFGoogleMapSample/BasicMapPage.xaml#L216-L218
