### ISSUE TITLE
[Android] Null reference on map.Pins.Add(...

### ISSUE THREAD

**Issue by fraspa** [amay077/Xamarin.Forms.GoogleMaps#67]
Hi, i'm using this library in a crossplatform project.
On IOS everything works fine, on android (emulated and phisical device) it displays the map but crashes with a  "null reference" (Java.Lang.NullPointerException) error.
I tried creating a new minimal test project with only base libraries and it crashes too  
I attached an error message log
[err.txt](https://github.com/amay077/Xamarin.Forms.GoogleMaps/files/439392/err.txt)
And the "main" test code
[main.txt](https://github.com/amay077/Xamarin.Forms.GoogleMaps/files/439398/main.txt)

Do you have any idea why it's behaving like this?
Thanks in advance.

**Comment by amay077** [comment]
Please check exists ``icon.png`` in ``Assets`` directory, and set "Build Action" to ``AndroidAsset``

**Comment by fraspa** [comment]
Thanks for the answer.
In the meantime I rebuilt the solution from the ground and now it works. 
I'll check on the old solution if your answer fixes it (very probable)
I think we can consider this closed.
