### ISSUE TITLE
Text showing instead of map

### ISSUE THREAD

**Issue by stesvis** [amay077/Xamarin.Forms.GoogleMaps#674]
### VERSIONS

* Xamarin.Forms.GoogleMaps - 3.3.0
* Xamarin.Forms - 4.3.0.947036

### PLATFORMS

- [x] Android
- [ ] iOS
- [ ] UWP

### ACTUAL BEHAVIOR

Instead of the map now it just shows the text _Xamarin.Forms.GoogleMaps_

### ACTUAL SCREENSHOTS/STACKTRACE

![Screenshot_20191105_115422_com veloguide mobile prod](https://user-images.githubusercontent.com/6062684/68236806-1ce53600-ffc3-11e9-8a1b-e0de449a56c2.jpg)
 

```
// paste stacktrace
```

### EXPECTED BEHAVIOR

It should display the map, like it used to do before v3.3.0

### HOW TO REPRODUCE

1.  Add a map control in xaml
2. 
3. 

```xml
<maps:Map InitialCameraUpdate="-23.68, -46.87, 13, 30, 60" VerticalOptions="FillAndExpand" />
```

Am i missing something, some settings, extra packages?

**Comment by almirvuk** [comment]
Same here, worked fine in the previous version? Any news about this?

**Comment by almirvuk** [comment]
It seems that this is connected to this issue. https://github.com/amay077/Xamarin.Forms.GoogleMaps/issues/655

**Comment by SoftecsulKleverton** [comment]
I solved this after installing Xamarin.GooglePlayServices.Maps on the Android Project.

Hope it works for you too :)
