### ISSUE TITLE
System.NullReferenceException immediately upon the attempt of drawing the custom map pin (Forms Android)

### ISSUE THREAD

**Issue by devcssbet** [amay077/Xamarin.Forms.GoogleMaps#683]
### VERSIONS

* Xamarin.Forms.GoogleMaps - 3.3.0
* Xamarin.Forms - 4.4.0.991265
* 

### PLATFORMS

- [x] Android
- [ ] iOS
- [ ] UWP

### ACTUAL BEHAVIOR

Crash with System.NullReferenceException after initiating the trace by route on the map.

### ACTUAL SCREENSHOTS/STACKTRACE

UNHANDLED EXCEPTION:
12-19 16:13:03.040 I/MonoDroid(24556): System.NullReferenceException: Object reference not set to an instance of an object.
12-19 16:13:03.045 I/MonoDroid(24556):   at Xamarin.Forms.GoogleMaps.Android.Utils+<>c__DisplayClass2_0.<ConvertFormsToNative>b__0 () [0x00038] in <d0ff28c53c584fe19f7bb765a8220c48>:0 
12-19 16:13:03.045 I/MonoDroid(24556):   at System.Threading.Tasks.Task`1[TResult].InnerInvoke () [0x0000f] in /Users/builder/jenkins/workspace/archive-mono/2019-08/android/release/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Future.cs:534 
12-19 16:13:03.045 I/MonoDroid(24556):   at System.Threading.Tasks.Task.Execute () [0x00000] in /Users/builder/jenkins/workspace/archive-mono/2019-08/android/release/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2319 
12-19 16:13:03.045 I/MonoDroid(24556): --- End of stack trace from previous location where exception was thrown ---
12-19 16:13:03.045 I/MonoDroid(24556):   at Xamarin.Forms.GoogleMaps.Logics.Android.PinLogic.TransformXamarinViewToAndroidBitmap (Xamarin.Forms.GoogleMaps.Pin outerItem, Android.Gms.Maps.Model.Marker nativeItem) [0x0013b] in <d0ff28c53c584fe19f7bb765a8220c48>:0 
12-19 16:13:03.045 I/MonoDroid(24556):   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in /Users/builder/jenkins/workspace/archive-mono/2019-08/android/release/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1021 
12-19 16:13:03.045 I/MonoDroid(24556):   at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <6e2e8fb437184994824f9a85bdfb3fcf>:0 
12-19 16:13:03.045 I/MonoDroid(24556):   at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <6e2e8fb437184994824f9a85bdfb3fcf>:0 
12-19 16:13:03.045 I/MonoDroid(24556):   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <6e2e8fb437184994824f9a85bdfb3fcf>:0 
12-19 16:13:03.045 I/MonoDroid(24556):   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.48(intptr,intptr)
12-19 16:13:03.070 W/art     (24556): JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
12-19 16:13:03.075 D/Mono    (24556): DllImport searching in: '__Internal' ('(null)').
12-19 16:13:03.075 D/Mono    (24556): Searching for 'java_interop_jnienv_throw'.
12-19 16:13:03.075 D/Mono    (24556): Probing 'java_interop_jnienv_throw'.
12-19 16:13:03.075 D/Mono    (24556): Found as 'java_interop_jnienv_throw'.
**System.NullReferenceException:** 'Object reference not set to an instance of an object.'

### EXPECTED BEHAVIOR

Custom pin of the source should trace the route of its movement towards the destination.

### HOW TO REPRODUCE

1.  Download the sample package: https://github.com/rdelrosario/MapTrackingSample (not my own)
2. Add the source route and the destination also
3.  It  should crash immediately upon drawing the pin of the source vehicle

```csharp
// code for reproduce
```

**Comment by amay077** [comment]
I think you should understand MapTrackingSample and ask to https://github.com/rdelrosario/MapTrackingSample 's owner.
