### ISSUE TITLE
Drag and Drop polygons

### ISSUE THREAD

**Issue by AlonRom** [amay077/Xamarin.Forms.GoogleMaps#685]
### SUMMARY

Provide the option to edit a polygon by drag and drop its vertices.

### DETAILS

Is there an option to edit a polygon after it was drawn by dragging and dropping its vertices?

The Google Map for a rectangle exists:

https://developers.google.com/maps/documentation/javascript/shapes#editable

var rectangle = new google.maps.Rectangle({
  bounds: bounds,
  editable: true
});

How can I achieve this in Xamarin.Forms?

![
![image](https://user-images.githubusercontent.com/27087135/71632403-123bcb80-2c17-11ea-9d69-8324a0ce610e.png)

### PLATFORMS

Xamarin.Forms:
- [x] Android
- [x] iOS
- [ ] UWP

**Comment by amay077** [comment]
We can't support it because Google Maps SDK for Android/iOS does not support it.
