### ISSUE TITLE
Issue building iOS fgmps-3.5.0 directory not found

### ISSUE THREAD

**Issue by thomasonb** [amay077/Xamarin.Forms.GoogleMaps#687]
When performing a build with the latest version (3.3.0) it has 3 missing directories all related to fgmps-3.5.0. I followed the steps to manually install Xamarin.Build.Download as suggested in another thread but that didn't seem to fix the issue this time. After downgrading to 3.2.1 the issue isn't happening.

**Comment by SergioAMG** [comment]
I am experiencing the very same issue. Already tried the same steps as the previous comment with out luck.

**Comment by amay077** [comment]
Maybe you can found related issues and solutions.

https://github.com/amay077/Xamarin.Forms.GoogleMaps/issues?utf8=%E2%9C%93&q=is%3Aissue+fgmps-3.5.0
