### ISSUE TITLE
Reference Error

### ISSUE THREAD

**Issue by LumiProj** [amay077/Xamarin.Forms.GoogleMaps#691]
### VERSIONS

* Xamarin.Forms.GoogleMaps - x.x.x
* Xamarin.Forms - x.x.x
* 

### PLATFORMS

- [ ] Android
- [x] iOS
- [ ] UWP

### ACTUAL BEHAVIOR

/.nuget/packages/xamarin.build.download/0.4.11/build/Xamarin.Build.Download.targets(3,3): Error: Did not find reference matching RestoreAssemblyResources AssemblyName metadata 'Google.Maps, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'

### ACTUAL SCREENSHOTS/STACKTRACE

![something_image](your_image.png) 

```
// paste stacktrace
```

### HOW TO REPRODUCE

1. 
2. 
3. 

```csharp
// code for reproduce
```

**Comment by amay077** [comment]
Is this duplicate issue?

Please join #666 or #673 .
