### ISSUE TITLE
CameraUpdate support

### ISSUE THREAD

**Issue by amay077** [amay077/Xamarin.Forms.GoogleMaps#7]
Improve panning, tilt, rotate map
## Android
- [Camera and views  |  Google Maps Android API  |  Google Developers](https://developers.google.com/maps/documentation/android-api/views)
## iOS
- [Camera and views |  Google Maps SDK for iOS  |  Google Developers](https://developers.google.com/maps/documentation/ios-sdk/views)

**Comment by dw2kim** [comment]
Hi Amay, 

I am so waiting for this feature..
Could you provide me the estimate for this feature?

Thanks.

**Comment by amay077** [comment]
Hi @dw2kim ,

Please wait a few more days for [``Map.MoveCamera``](https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap.html#moveCamera(com.google.android.gms.maps.CameraUpdate)).

[``Map.AnimateCamera``](http://bit.ly/2keihJk) implementation is a bit difficult because it have callbacks for animation ended and canceled. I should consider migrate callbacks to ``async/await`` .

**Comment by amay077** [comment]
Hi @dw2kim ,

I released [v1.8.0-beta3](https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/1.8.0-beta3) which contains ``Map.MoveCamera(CameraUpdate)`` method.

And added [``CameraPage.xaml.cs``](https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/master/XFGoogleMapSample/XFGoogleMapSample/CameraPage.xaml.cs) as sample.

Could you try it?

**Comment by dw2kim** [comment]
Hi Amay077,

Thanks for updates and letting me know that.

I will try the new beta version and try the camera feature soon.


Thank you a lot.

dw2kim

**Comment by amay077** [comment]
I fixed listed bellow:

*  #192 [UWP] Map.MoveCamera(CameraUpdateFactory.NewBounds(…)) does not reset rotation
* #189 [iOS] Map.MoveCamera(CameraUpdateFactory.NewBounds(…)) does not raise CameraChanged event

(But I don't release yet.)

**Comment by amay077** [comment]
I released v1.8.0-beta4 now contains ``Map.AnimateCamera(CameraUpdate)`` method available on Android/iOS/UWP.

Also added sample is [here](https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/master/XFGoogleMapSample/XFGoogleMapSample/CameraPage.xaml.cs#L66-L103).

You can try anytime!

**Comment by dw2kim** [comment]
Thank you for updates and notifications, Amay.
I will test it shortly (maybe after a week or so), and let you know.

Thank you

dw2kim

**Comment by amay077** [comment]
FYI

* #199 
* #202

**Comment by dw2kim** [comment]
Hi Amay,

The camera class and zoom level works perfectly now.


Thank you.

**Comment by amay077** [comment]
I released [v1.8.0](https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/1.8.0) that contained it.
