### ISSUE TITLE
Android GoogleMaps.SetPadding() not working

### ISSUE THREAD

**Issue by leaguefun** [amay077/Xamarin.Forms.GoogleMaps#71]
Supposingly, we can add padding around the edges of the map using the GoogleMap.setPadding() method. The map will continue to fill the entire container, but text and control positioning, map gestures, and camera movements will behave as if it has been placed in a smaller space. On iOS platform it can be done by current version of library, whereas it won't on Android, it just works like padding on view. Does it having another method to do the same thing on android ? many thanks.

**Comment by leaguefun** [comment]
Fixed, just using the deprecated interface to get the GoogleMap object, then calling SetPadding(), it's works !! :D

**Comment by amay077** [comment]
I will make ``Map.Padding`` property that is wrapped below APIs.

* [GMSMapView Class Reference  |  Google Maps SDK for iOS  |  Google Developers](https://developers.google.com/maps/documentation/ios-sdk/reference/interface_g_m_s_map_view.html?hl=ja#a66668a48bbc864faee1e8ba71e4c9bec)
* [GoogleMap  |  Google APIs for Android  |  Google Developers](https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap.html?hl=ja#setPadding(int, int, int, int))

**Comment by amay077** [comment]
Current status:

## TASKS

* [x] Android implementation
* [x] iOS implementation
* [ ] UWP implementation
* [ ] Add samples

**Comment by amay077** [comment]
released at https://github.com/amay077/Xamarin.Forms.GoogleMaps/releases/tag/v1.8.0-beta6
