### ISSUE TITLE
[Android] get_Map returns NULL POINTER EXCEPTION

### ISSUE THREAD

**Issue by belandsoft** [amay077/Xamarin.Forms.GoogleMaps#73]
I'm facing this problem on Android probably because i use this lib with Google Play Services ver. 32.x instead of 29.x, but to use some other library inside my project i'm forced to do so.

I'm constantly getting: "Method 'Android.Gms.Maps.MapView.get_Map' not found." and app crashes.

Please update this fanctastic lib to be compatible with newer Google Play Services version too.

**Comment by amay077** [comment]
Xamarin.Forms.GoogleMaps now supports Google Play services ver 32.x.

I published [Xamarin.Forms.GoogleMaps 1.6.1-beta1](https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/1.6.1-beta1), please try it!

**Comment by belandsoft** [comment]
I'ts quiet strange, now my application crashes at start when executing this line of code:

`Xamarin.FormsGoogleMaps.Init(this, bundle);`

the error log says:

"System.TypeLoadException: Could not load type 'Xamarin.Forms.GoogleMaps.Android.MapRenderer' from assembly 'Xamarin.Forms.GoogleMaps.Android, Version=1.6.0.1, Culture=neutral, PublicKeyToken=null'.
"

**Comment by hieumoscow** [comment]
I also have this issue with 1.6, Please help us

**Comment by amay077** [comment]
Hi @tematim , @hieumoscow , @belandsoft ,

Can you give me sample project for reproduce #73 or #76 ?
I can not repro these issues.

I tried these steps

1. Create new Xamarin.Forms(XAML) solution.
2. Add Xamarin.Forms.GoogleMaps v1.6.0 nuget package to PCL and Android project.
3. Add INTERNET, ACCESS_NETWORK_STATE, ACCESS_FINE_LOCATION permissions to Android manifest.
4. Write Google maps apiKey to MyApp.cs (similar [this](https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/master/XFGoogleMapSample/Droid/MyApp.cs))
5. Add Map view to XAML.
6. Write ``Xamarin.FormsGoogleMap.Init`` to MainActivity.cs .

I can launch this app and see Google map.

[XFSample.zip](https://github.com/amay077/Xamarin.Forms.GoogleMaps/files/489620/XFSample.zip)

**Comment by belandsoft** [comment]
Ok, this is my sample project, note 2 main bugs:

1) crash at Droid application start.
2) not working iOS map pin onclick event delegate. (on the app interface you need to open menu' and tap on the "stop map" entry than move the map to make appear a pin)

[OrariGTT.zip](https://github.com/amay077/Xamarin.Forms.GoogleMaps/files/495808/OrariGTT.zip)

**Comment by amay077** [comment]
Thanks @belandsoft , I'll check it. 👍

**Comment by amay077** [comment]
> 1) crash at Droid application start.

I reproduced it.
The cause is Xamarin.Forms-Ver2.3.3-pre2 have breaking changes.

ref - https://forums.xamarin.com/discussion/comment/222650/#Comment_222650

I can not support Xamarin.Forms 2.3.3-pre2 because this is pre-release version.
Let’s wait and see before we make a decision.

**Comment by hieumoscow** [comment]
In my case I fixed it by upgrading XF from Xamarin.Forms 2.2.0.31 to 2.3.0.49. Cheers :)

**Comment by amay077** [comment]
I put this on ice.
If you request again then I will reopen.

**Comment by HarkDev** [comment]
Hey, I just updated all Xamarin packages from NuGet and started getting this same exception.
Method 'Android.Gms.Maps.MapView.get_Map' not found.

Is there any way to solve it or is it a bug?
