### ISSUE TITLE
Issue after updating to latest xamarin.ios and xcode

### ISSUE THREAD

**Issue by starl1n** [amay077/Xamarin.Forms.GoogleMaps#749]
### VERSIONS

* Xamarin.Forms.GoogleMaps - 3.3.0
* Xamarin.Forms - 4.4.0.991265
* 

### PLATFORMS

- [ ] Android
- [x] iOS
- [ ] UWP

### ACTUAL BEHAVIOR

I'm unable to build a project after the update, the project was working perfectly but as soon I installed the latest Xcode version and the latest update of VSMac can't build the project. 

### ACTUAL SCREENSHOTS/STACKTRACE
/Users/theuser/.nuget/packages/xamarin.build.download/0.7.1/buildTransitive/Xamarin.Build.Download.targets(3,3): Error: Did not find reference matching RestoreAssemblyResources AssemblyName metadata 'Google.Maps, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'

If I install Xamarin.Build.Download I get
/Users/starlingonzalez/Documents/Projects/ecostructivemobile/ecostructivemobile.iOS/MTOUCH: Error MT0009: Error while loading assemblies: /Users/starlingonzalez/.nuget/packages/xamarin.google.ios.maps/3.5.0/lib/xamarinios10/Google.Maps.dll. (MT0009) (ecostructivemobile.iOS)

Which I have to mention again, the project was running fine  and in Android don't get any issues, seems related to the new xcode, or Xamarin.iOS package which is :
Xamarin.iOS
Version: 14.0.0.0 (Visual Studio Community)
Hash: 7ec3751a1
Branch: xcode12
Build date: 2020-09-16 11:33:15-040

Any guidance on the topic will be greatly appreciated

**Comment by starl1n** [comment]
Forgot to mention that this is in Catalina (10.15.7) also

**Comment by starl1n** [comment]
worth to mention that I tried the current Xamarin.Forms.Maps and it works out of the box, just letting you know about it to see if it help narrow the issue

**Comment by starl1n** [comment]
I think I find the issue,

I downloaded the source code and did the following:
1. Update all dependencies/packages in all the projects
2. I still get same error, but went deeper on the solution and found that it was referencing the wrong Xamarin.Google.iOS.Maps package, was 3.5.0.1 and updated to 3.7.0.1

built the project and generate the nuget package following this https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package-dotnet-cli, manually added the repository, remove all nuget packages and restore and was able to make it work.

I must say it wasn't easy to came to this solution, but think It's good to mention it here.

Thanks for the great work!

**Comment by jamcar23** [comment]
@starl1n can you share the nuget package?

**Comment by starl1n** [comment]
Sure thing 
Here's a link directly to it

Remember to add a local repository for it and put it in that folder
https://1drv.ms/u/s!AihMZY0ZyrxQk_YsnFwHe59--DosjA?e=tsf2pw
