### ISSUE TITLE
[android] on some devices like HUAWEI P smart 2019 maps(tiles) are not visible as with Xamarin.Forms.Maps.

### ISSUE THREAD

**Issue by gsgou** [amay077/Xamarin.Forms.GoogleMaps#750]
### VERSIONS

* Xamarin.Forms.GoogleMaps - 3.3.0 and 4.0.0-BETA1
* Xamarin.Forms - 4.7.0.1351

### PLATFORMS

- [x] Android

### ACTUAL BEHAVIOR

Maps are not visible (empty tiles) and no error is thrown.
With Xamarin.Forms.Maps maps are visible.

### EXPECTED BEHAVIOR

Maps are visible.

### HOW TO REPRODUCE

Can be reproduced on the sample with
a HUAWEI P smart 2019, Android 10.

**Comment by gsgou** [comment]
Related to key restrictions, therefore can be closed as invalid.

**Comment by pohurn** [comment]
@gsgou May I know what was the fix please?
