### ISSUE TITLE
System.IO.FileNotFoundException unhandled

### ISSUE THREAD

**Issue by tematim** [amay077/Xamarin.Forms.GoogleMaps#76]
Hello,

I have a project with FreshMvvm/Xamarin PCL.

I added Geolocator and your package, and I try to build it and deploy to my phone (HTC One M7).

This is my packages.config :
`<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Plugin.CurrentActivity" version="1.0.1" targetFramework="monoandroid60" />
  <package id="Plugin.Permissions" version="1.1.7" targetFramework="monoandroid60" />
  <package id="Xam.Plugin.Geolocator" version="3.0.4" targetFramework="monoandroid60" />
  <package id="Xamarin.Android.Support.Animated.Vector.Drawable" version="23.3.0" targetFramework="monoandroid60" />
  <package id="Xamarin.Android.Support.v4" version="23.3.0" targetFramework="monoandroid60" />
  <package id="Xamarin.Android.Support.v7.AppCompat" version="23.3.0" targetFramework="monoandroid60" />
  <package id="Xamarin.Android.Support.v7.MediaRouter" version="23.3.0" targetFramework="monoandroid60" />
  <package id="Xamarin.Android.Support.Vector.Drawable" version="23.3.0" targetFramework="monoandroid60" />
  <package id="Xamarin.Forms" version="1.3.3.6323" targetFramework="monoandroid23" />
  <package id="Xamarin.Forms.GoogleMaps" version="1.6.1-beta1" targetFramework="monoandroid60" />
  <package id="Xamarin.GooglePlayServices.Base" version="29.0.0.1" targetFramework="monoandroid60" />
  <package id="Xamarin.GooglePlayServices.Basement" version="29.0.0.1" targetFramework="monoandroid60" />
  <package id="Xamarin.GooglePlayServices.Maps" version="29.0.0.1" targetFramework="monoandroid60" />
</packages>`

I followed steps from here : http://www.knowing.net/index.php/2014/05/30/using-xamarin-forms-maps-you-have-to-init-first/

I try with the 1.6.0 and 1.6.1-beta1, the exception throw in both cases.

Exception Message : `"Could not load file or assembly or one of its dependencies." :
"Xamarin.Forms.GoogleMaps.Android, Version=1.6.0.1, Culture=neutral, PublicKeyToken=null"
`

Could you have a look ?

Regards

**Comment by amay077** [comment]
Did you add Xamarin.Forms.GoogleMaps nuget package to your Android project?

**Comment by tematim** [comment]
Hello,

Yes, I added to PCL and Android/iOS/Win.

Here is the list of my packages : https://gyazo.com/6a789e97547655f73434d0a02f22c555.

Maybe the file isn't added when deploying the app to the phone

**Comment by amay077** [comment]
Why your packages have Xamarin.Forms 1.33 and 2.10?

Please check your packages or start by minimum project.

**Comment by tematim** [comment]
Hello,

This is my sample : https://www.dropbox.com/s/aj0ei92wcz2h9m6/TimeRush2.zip?dl=0

The gps and map instantiation are ok, but I have a blank map.

Please check

**Comment by amay077** [comment]
You should set Google Maps API key to ``AndroidManifest.xml`` or ``MainApplication.cs``.

See below

* [Get API Key  |  Google Maps Android API  |  Google Developers](https://developers.google.com/maps/documentation/android-api/signup)
* [Xamarin.Forms.GoogleMaps/MyApp.cs at master · amay077/Xamarin.Forms.GoogleMaps](https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/master/XFGoogleMapSample/Droid/MyApp.cs#L8)

I can see map on your app. 👍 

![2016-10-04 01 27 52](https://cloud.githubusercontent.com/assets/401369/19045055/ebbd7bb0-89d1-11e6-8b2c-4fd5155700bd.png)
