### ISSUE TITLE
BitmapDescriptorFactory.FromBundle is not working in UWP

### ISSUE THREAD

**Issue by rajeshangappan** [amay077/Xamarin.Forms.GoogleMaps#767]
### VERSIONS

* Xamarin.Forms.GoogleMaps - 3.0
* Xamarin.Forms - x.x.x
* 

### PLATFORMS

-  UWP

### ACTUAL BEHAVIOR
image is not coming in mapview

### ACTUAL SCREENSHOTS/STACKTRACE

![something_image](your_image.png) 

```
// paste stacktrace
```

### EXPECTED BEHAVIOR
image should come

### HOW TO REPRODUCE

1. 
2. 
3. 

```csharp
// code for reproduce
```

**Comment by BillyMartin1964** [comment]
Having the same issue. No custom map pins in UWP

**Comment by rajeshangappan** [comment]
Hi @BillyMartin1964 , Please use the image name like "Assets\\{image}". For UWP, we should mention the Assets folder also...
For UWP:"Assets/icon.png"
