### ISSUE TITLE
Request Option for centering a circular pin image

### ISSUE THREAD

**Issue by dreamsystems** [amay077/Xamarin.Forms.GoogleMaps#77]
Hi, it would be nice to have an option for centering a custom image on the pin's position, when this image is not a pin, a circular image for example. I have attached a picture which shows the current issue. From the user point of view, the information is visually wrong.
Thanks 
![custom-image](https://cloud.githubusercontent.com/assets/17129852/18808257/5274b674-825d-11e6-8bfa-39b5a96096ae.png)

**Comment by dreamsystems** [comment]
Here it would be nice: 
var pin = new Pin { Type = PinType.Circular }

**Comment by amay077** [comment]
I understand it.

You can use ``Pin.AnchorX`` and ``AnchorY`` property.
Set these properties to ``0.5`` then you can show pin in center of circle.

Please see below:

* [MarkerOptions  |  Google APIs for Android  |  Google Developers](https://developers.google.com/android/reference/com/google/android/gms/maps/model/MarkerOptions.html?hl=ja#anchor(float, float))
* [GMSMarker Class Reference  |  Google Maps SDK for iOS  |  Google Developers](https://developers.google.com/maps/documentation/ios-sdk/reference/interface_g_m_s_marker.html?hl=ja#a65c160c7a9d3aadbbfc0a9a640fa826b)

**Comment by dreamsystems** [comment]
Thanks, people at xamarin have already done this work. And thanks for your plugin.
