### ISSUE TITLE
Will this project be moved to MAUI?

### ISSUE THREAD

**Issue by LittleBoxOfChicken** [amay077/Xamarin.Forms.GoogleMaps#772]
Recently there has been a discussion about whether this project is dead or not. It's worrying and it looks pretty dead to me (and everyone else).

I was wondering if this project is really dead. If not, will this project ever be moved to MAUI or will it stay with Xamarin for the remainder of Xamarin's short lifespan?

**Comment by LittleBoxOfChicken** [comment]
Apologies for making this an issue. But I see there is no discussion board.

**Comment by themronion** [comment]
It should be moved, otherwise i just can't upgrade to MAUI. As i said earlier, if someone has the guts he can make a fork and try to target .net 6, we would be grateful! No hope that the author will do this, honestly

**Comment by LittleBoxOfChicken** [comment]
True @themronion

MAUI Preview 4 is out now, one could try to port this. I already gave it a shot but moving to MAUI definitely breaks this package.

The standard Maps package for Xamarin uses Apple's maps API which is not rich enough for any of our projects.

**Comment by LittleBoxOfChicken** [comment]
Could @amay077 maybe give some insight?

**Comment by themronion** [comment]
i highly doubt it

**Comment by themronion** [comment]
https://github.com/amay077/Xamarin.Forms.GoogleMaps/issues/783#issuecomment-1169920397

**Comment by amay077** [comment]
Hello everyone.
I'm reborn. :innocent:

(I was writing typescript for several years.
So I lost interest in Xamarin and C#.
But recently I re-started writing C#, which has given me some motivation.)

This project is not died.
I'm deployed [v5.0.0 to nuget](https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/5.0.0) that supports Xamarin.Forms 5.0.
And I'm starting understand for MAUI, I will supports it if I can(maybe create new project)。.
