### ISSUE TITLE
Issue Android map.MoveToRegion() zoom not working when animate parameter is true

### ISSUE THREAD

**Issue by dreamsystems** [amay077/Xamarin.Forms.GoogleMaps#78]
Hi, i report this issue with a sample code to reproduce the bug: 

```
map.SelectedPinChanged += (sender, e) =>
{
    if (e.SelectedPin != null)
    {
        var latitude = e.SelectedPin.Position.Latitude;
        var longitude = e.SelectedPin.Position.Longitude;
        map.MoveToRegion(MapSpan.FromCenterAndRadius(new Position(latitude, longitude),  Distance.FromKilometers(1 or whatever)));
    }
};
```

**Comment by amay077** [comment]
I reproduced it too.

It is conflicts ``MoveToRegion`` and Google Maps API's default behavior. 

I should implement return ``true`` in [OnMarkerClickListener.onMarkerClick](https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap.OnMarkerClickListener.html?hl=ja#onMarkerClick(com.google.android.gms.maps.model.Marker)).
I will provide ``SelectedPinChangedEventArgs.Handled`` property probably.

You will can set ``SelectedPinChangedEventArgs.Handled = true`` then disable Google Maps API's default behavior.

**Comment by amay077** [comment]
Hi @dreamsystems,

I deployed [1.7.0-beta1](https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/1.7.0-beta1) what provides solution for this issue.

You can subscribe ``Map.PinClicked`` event and set ``PinClickEventArgs.Handled`` to ``true``.
If ``PinClickEventArgs.Handled`` is ``true`` then pin selection doesn't work automatically.
So you can write your own operation to Map and Pin.

Could you try 1.7.0-beta1 and [XFGoogleMapSample](https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/cbb7c2ba2da5dcfdb7224ae69ca1e2d6a65e8fd0/XFGoogleMapSample/XFGoogleMapSample/PinsPage.xaml.cs#L121).

**Comment by dreamsystems** [comment]
Hi, thanks ! I will give a try.

**Comment by dreamsystems** [comment]
It works well on Android and iOS. The callout is disabled when`e.Handled` is true and at the same time, this boolean is used as a checker to do or not the operations.

**Comment by amay077** [comment]
Thanks @dreamsystems ,

I will make stable version soon.
