### ISSUE TITLE
Xamarin.Forms.GoogleMaps - 3.2.0 ,* Xamarin.Forms - 5.0.0.2083 

### ISSUE THREAD

**Issue by MahnedraS** [amay077/Xamarin.Forms.GoogleMaps#785]
### VERSIONS

* Xamarin.Forms.GoogleMaps - 3.2.0
* Xamarin.Forms -5.0.0.2083 
* 

### PLATFORMS

- [x] Android
- [ ] iOS
- [ ] UWP

### Google map not rendering route inside Scrollview xamarin.forms android 

<img width="327" alt="Screenshot 2022-03-03 at 8 54 55 AM" src="https://user-images.githubusercontent.com/14901531/156489940-39169e0b-47bb-4b93-96cb-b08c486b7972.png">
  --> It is working on Xamarin.Forms Ios perfectly 

--->In android outside scrollview Map rendering route perfectly .

please help me to draw route inside scrollview.

Thanks & Regards,
Naga.

**Comment by diloidroj** [comment]
For me works if I put the code outside of scrollview

**Comment by amay077** [comment]
Hi @MahnedraS  ,
I deployed [v5.0.0 to nuget](https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/5.0.0).
Could you try it?

https://github.com/amay077/Xamarin.Forms.GoogleMaps/issues/783#issuecomment-1232771417
