### ISSUE TITLE
Error on Provide APIKey with Xamarin.Forms.GoogleMaps - 3.3.0 

### ISSUE THREAD

**Issue by linda-dge** [amay077/Xamarin.Forms.GoogleMaps#787]
### VERSIONS

* VS 2019 Version 16.11.13
* Xamarin.Forms.GoogleMaps - 3.3.0
* Xamarin.Forms - 5.0.0.2401
* Xamarin.Build.Download - 0.11.1
* Xamarin.Google.iOS.Maps - 6.0.1

### PLATFORMS

- [ ] Android
- [x] iOS
- [ ] UWP

### ACTUAL BEHAVIOR

Upon Compiling

error MT2101: Can't resolve the reference 'System.Boolean Google.Maps.MapServices::ProvideAPIKey(System.String)', referenced from the method 'System.Void Xamarin.FormsGoogleMaps::Init(System.String,Xamarin.Forms.GoogleMaps.iOS.PlatformConfig)' in 'Google.Maps, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

### EXPECTED BEHAVIOR

I expect the project to compile.

### HOW TO REPRODUCE

Tried
⦁	Clean Nuget Cache
⦁	Delete bin and obj Folders
⦁	Clean Solution
⦁	Deployment >10 (I have tried all the way up to 15)

I did find an old issue (https://github.com/amay077/Xamarin.Forms.GoogleMaps/issues/666) and have tried everything in there. I simply cannot build.

**Comment by linda-dge** [comment]
I finally got this to build with

* Xamarin.Forms - 5.0.0.2337
* Xamarin.Forms.GoogleMaps - 3.3.0
* Xamarin.Build.Download - 0.11.1
* Xamarin.Google.iOS.Maps - 3.9.0

Downgrading Xamarin.Forms and Xamarin.Google.iOS.Maps did the trick.

**Comment by eolverabea** [comment]
> I finally got this to build with
> 
> * Xamarin.Forms - 5.0.0.2337
> * Xamarin.Forms.GoogleMaps - 3.3.0
> * Xamarin.Build.Download - 0.11.1
> * Xamarin.Google.iOS.Maps - 3.9.0
> 
> Downgrading Xamarin.Forms and Xamarin.Google.iOS.Maps did the trick.

This only works in debug in relese it does not show the maps, do you have any suggestions ?

**Comment by linda-dge** [comment]
I finally had to open up my google maps api key and not restrict by the application name.

**Comment by eolverabea** [comment]
> I finally had to open up my google maps api key and not restrict by the application name.

Even without restricting the API usage it does not show the maps, thanks for your suggestion.

**Comment by amay077** [comment]
Hi @linda-dge  ,
I deployed [v5.0.0 to nuget](https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/5.0.0).
Could you try it?

https://github.com/amay077/Xamarin.Forms.GoogleMaps/issues/783#issuecomment-1232771417
