### ISSUE TITLE
Using clientId in google Maps

### ISSUE THREAD

**Issue by prajithmp** [amay077/Xamarin.Forms.GoogleMaps#79]
Hi ,

we have got google map premium account, (https://developers.google.com/maps/premium/overview) how can i use this for registering xamarin form google map component. 

this is how we use in our web application
https://maps.googleapis.com/maps/api/js?client=xxx-xxxxxxxxxxxxxxx&sensor=false

i have followed the steps below in xamarin forms, but not working in both platforms.

**In Android**
 Xamarin.FormsGoogleMaps.Init(this, bundle); // in main activity
Manifest
meta-data android:name="com.google.android.geo.API_KEY" android:value="xxx-xxxxxxxxxxxxxxx" 

**In IOS**
Xamarin.FormsGoogleMaps.Init("xxx-xxxxxxxxxxxxxxx");

------------------------------------------------------------------------

its working when i used normal key instead of premium key

**Comment by amay077** [comment]
I think premium key is only for Google Maps Javascript API.

> Client ID
>
> Instead of an API key, you can use your client ID to make requests to any of the APIs **except** the following: Google Places API, Google Maps Geolocation API, Google Maps Roads API, and the **Mobile APIs (Android, iOS)**.

via https://developers.google.com/maps/premium/overview#client-id

You may just use normal api key.
