### ISSUE TITLE
Creating Archive Ios - Causing too long file names

### ISSUE THREAD

**Issue by karitall56** [amay077/Xamarin.Forms.GoogleMaps#797]
### VERSIONS

* Xamarin.Forms.GoogleMaps - 3.3.0 and 5.0.0 Tested both
* Xamarin.Forms - 5.0.0.2515
* 

### PLATFORMS

- [ ] Android OK
- [x] iOS Works fine in another app but not in current (KaBom). Something happend in a week with no changes 
- [ ] UWP N/A

### ACTUAL BEHAVIOR

When I create an Archive for Ios I suddenly get an error message in the build. This Nuget qworks fine in another app wiht same versions as above. It also worked fine in the current problem app one week ago.
Using same version i another app and it builds archive Ios withouth any issues. 

I have the text here and below the actual screenshot:

Cannot create an IOS archive 'KaBom.iOS'. 
Process cannot be executed on XMA server.
There was an error unzipping the file C\Users\karitalltmp\2022-11-06\f1a083d2.zip; Could not find a part of the path 'C:\Users\karitall\AppData\Local\Temp\Xamarin\,Extractions\de6cbab4-b7ca-48a1-b1a8-dBef4856aa91\KaBomiOS 11-06-22 5.26 
PM.xcarchive\Products\Applications'\KaBom.iOS,app\ GoogleMapsbundle\GMSCoreResources.bundle\ic_covid_checkpoint_waypoint_alert_night_32pt@3x.png". 

### ACTUAL SCREENSHOTS/STACKTRACE

<[
![Archive build error](https://user-images.githubusercontent.com/111995338/200867226-995309b7-13c5-4025-b5a1-f855090836be.PNG)
](!-- Let me show your actual  screenshots or stacktrace. If you want to capture simulator screen to animation GIF, I recomend to [LICEcap](http://www.cockos.com/licecap/). -->

![something_image](your_image.png) 

```
// paste stacktrace)
```

### EXPECTED BEHAVIOR

Archive build Ios created

### HOW TO REPRODUCE

Just doing a archive build in Ios project

**Comment by themronion** [comment]
update to the latest vs version

**Comment by karitall56** [comment]
Hi, 
The upgrade to latest VS solved the problem.
