### ISSUE TITLE
UiSettings class support

### ISSUE THREAD

**Issue by amay077** [amay077/Xamarin.Forms.GoogleMaps#8]
UISetting is settings for the user interface of a GoogleMap.

Contains any gesture enabled and control visible.

`Map.HasZoomEnabled`, `HasScrollEnabled` are use for simple or keep compatibility.
`UISetting` is full spec for map controls.
- Android - [UiSettings  |  Google APIs for Android  |  Google Developers](https://developers.google.com/android/reference/com/google/android/gms/maps/UiSettings#public-method-summary)
- iOS - [GMSUISettings Class Reference  |  Google Maps SDK for iOS  |  Google Developers](https://developers.google.com/maps/documentation/ios-sdk/reference/interface_g_m_s_u_i_settings)

**Comment by deextercz** [comment]
Changes made in #110, but it needs a little bit more testing

**Comment by amay077** [comment]
In comparison with UiSetting class and Map class properties.

|UiSettings class[NEW!]|Map class|Synchronize|
|--|--|--|
|CompassEnabled|N/A|N/A|
|RotateGesturesEnabled|HasRotationEnabled|Yes|
|MyLocationButtonEnabled|IsShowingUser|No|
|N/A|MyLocationEnabled[NEW!]|N/A|
|IndoorLevelPickerEnabled|N/A|N/A|
|ScrollGesturesEnabled|HasScrollEnabled|Yes|
|TiltGesturesEnabled|N/A|N/A|
|ZoomControlsEnabled|HasZoomEnabled|No|
|ZoomGesturesEnabled|HasZoomEnabled|No|

Synchronize - "Yes" means synchronize property value UiSettings and Map class.

```
map.UiSettings.RotateGesturesEnabled = true;
Debug.WriteLine(map.HasRotationEnabled); // true

map.HasRotationEnabled = false;
Debug.WriteLine(map.UiSettings.RotateGesturesEnabled); // false
```

**Comment by amay077** [comment]
Released in https://github.com/amay077/Xamarin.Forms.GoogleMaps/releases/tag/v2.1.0-beta2

**Comment by Shivaprabhu049** [comment]
Hi @amay077  im not able to show the Zoom Controls on both iOS and Android even after  map.UiSettings.ZoomControlsEnabled = true;
