### ISSUE TITLE
setMapToolbarEnabled to false on Android

### ISSUE THREAD

**Issue by SvenCarstensen** [amay077/Xamarin.Forms.GoogleMaps#80]
Hi all,

i would like to hide the Toolbar on Android that shows after click on a Pin.

It can be done by set setMapToolbarEnabled(false), as descriped here:
http://stackoverflow.com/questions/30430664/how-to-hide-navigation-and-gps-pointer-buttons-when-i-click-the-marker-on-th

Is this possible?

Regards 

Sven

**Comment by amay077** [comment]
Thanks.
Can't hide MapToobar currently.

I will always hide MapToolbar in android because Google Maps iOS does not support it.

**Comment by amay077** [comment]
Hi @SvenCarstensen ,

I deployed [1.7.0-beta2](https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/1.7.0-beta2).
Would you try it.

**Comment by woojung3** [comment]
Hi, 

Seems that the MapToolbar in Android seems to activated when the pin is clicked.
This behavior was not happened with the previous versions of GoogleMaps.

I think the latest Forms.GoogleMaps or GoogleMap itself has changed so the hide code is broken.

I would like to hide the toolbar as the previous versions were. Is this possible?

Best regards.

(I attached the situation screenshot from my app... hope it helps)

![screenshot_2017-09-15-10-28-04](https://user-images.githubusercontent.com/22045860/30462548-4fe8b61e-9a01-11e7-9263-72b21a2325f3.png)

at the bottom right of the google maps there is the toolbar behind floating action button. This was not happened until the latest update (of Forms.GoogleMaps or GoogleMap itself).

**Comment by woojung3** [comment]
Xamarin.Forms.GoogleMaps version: 2.1.0
Xamarin.Forms.Maps version: 2.3.4.270
Xamarin.GooglePlayServices.Maps version: 42.1021.1

**Comment by amay077** [comment]
Thanks, this is bug.
I will fix it soon. 👍

**Comment by amay077** [comment]
#374
