### ISSUE TITLE
Error compilation on iOS

### ISSUE THREAD

**Issue by thfaix** [amay077/Xamarin.Forms.GoogleMaps#81]
I have tried to test your library and everything was really nice until I tried to compile for iOS.
When I tried to do that there was this error : 
![error](https://cloud.githubusercontent.com/assets/17575835/19211138/ae1c9d60-8d35-11e6-9fb1-756746a5c203.PNG)
I tried to do what they asked me but no effects. By the way I don't know why but when I have tried to unzip the file it was necessary that it was run as an administrator.
If someone have an idea it would be grateful. thanks

**Comment by amay077** [comment]
Could you try delete nuget cache files.

see - [Android Build Failure. Unzipping failed. — Xamarin Forums](http://forums.xamarin.com/discussion/42982/android-build-failure-unzipping-failed)

**Comment by thfaix** [comment]
I have tried it. And in fact there is no effects.

**Comment by amay077** [comment]
Hmm..., I don't know what happened.

Could you try any Google Maps iOS SDK's sample or 
[GoogleMaps iOS SDK components](https://components.xamarin.com/view/googleiosmaps) .

**Comment by dapug** [comment]
I get this error when using Xamarin.Forms.GoogleMaps.iOS v2.1.0.  If I use v1.13.2.2 I do not get this error.  I assume Xamarin.Forms.GoogleMaps is not compatible with Xamarins 2.x library.

**Comment by deextercz** [comment]
Could you provide a solution where I will be able to induce?

**Comment by amay077** [comment]
This is no longer response.
I closed it.
