### ISSUE TITLE
Setting for removing default ground layers

### ISSUE THREAD

**Issue by avsazonov** [amay077/Xamarin.Forms.GoogleMaps#82]
Thanks for your plugin! It's very useful.
The situation mentioned in the title has place when using customized layers. The default ground layers from Google are loaded quicker than others, so customized layers become visible later. Doesn't look great...

**Comment by amay077** [comment]
I found ``MAP_TYPE_NONE(Android)`` and ``kGMSTypeNone(iOS)`` in native Google Maps API.

I plan add ``MapType.None`` that supports empty map.

**Comment by amay077** [comment]
Thank you for contributing!

I released [v1.6.1-beta3 to nuget](https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/1.6.1-beta3) that contains this feature.
I will make stable after few days.

**Comment by avsazonov** [comment]
Thanks! Will test it today on iOS 10 and Android 5 and give a feedback.

**Comment by avsazonov** [comment]
Tested MapType.None on both Android 5 phone and iOS 10 iPad, it works fine: no Google layers are visible (only provided tiles are). Thanks one more time for the quick reply and update.

**Comment by amay077** [comment]
Thanks.

[v1.6.1](https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/1.6.1) is now stable.

Thank again @avsazonov. 👍
