### ISSUE TITLE
[UWP]HasRotateEnabled property

### ISSUE THREAD

**Issue by urnfield0** [amay077/Xamarin.Forms.GoogleMaps#84]
Firstly, many thanks for this library, it's really useful and stable, nice high quality code.

My request, if possible, is for a HasRotationEnabled property, which if set to false would disable the two-finger twist gesture to rotate the map.

I haven't really found rotation to be useful, and there's no way that I can find to get the map exactly straight again.

Thanks again!

**Comment by dreamsystems** [comment]
Rotate gesture can be disabled with something like this in android :

`GoogleMap.getUiSettings.setRotateGesturesEnabled(false);`
https://developers.google.com/maps/documentation/android-api/controls

and on iOS

`GMSMapView.settings.rotateGestures = false;`
https://developers.google.com/maps/documentation/ios-sdk/reference/interface_g_m_s_u_i_settings

This can accelerate your research.

**Comment by amay077** [comment]
Exactly, @dreamsystems!

I plan to Add ``Map.HasRotationEnabled as bool`` that wrapped ``setRotateGesturesEnabled`` and ``rotateGestures``.

This is very easy way.
I hope someone send me Pull-request❤️ .

**Comment by urnfield0** [comment]
Many thanks to you both, I wasn't expecting such quick and perfect responses

**Comment by dreamsystems** [comment]
Thanks to you. I learn a lot these days, I hope to be ready soon to contribute to projects like this.

**Comment by amay077** [comment]
Current status:

## TASKS

* [x] Android implementation
* [x] iOS implementation
* [ ] UWP implementation
* [ ] Add samples

**Comment by amay077** [comment]
released at https://github.com/amay077/Xamarin.Forms.GoogleMaps/releases/tag/v1.8.0-beta6

**Comment by amay077** [comment]
I released [v1.8.0](https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/1.8.0) that contained it.
