### ISSUE TITLE
Request command equivalent to the most used events

### ISSUE THREAD

**Issue by dreamsystems** [amay077/Xamarin.Forms.GoogleMaps#88]
Hi, it would be nice to have a command equivalent to the most used events.

Today, many developers use the MVVM pattern and features such as Xamarin forms behavior 

to handle the case where a type does not implement the command equivalent of an event.

This property contribute to keep our code neat while using the MVVM pattern.

Thanks

**Comment by amay077** [comment]
You can use [EventToCommandBehavior](https://developer.xamarin.com/guides/xamarin-forms/behaviors/reusable/event-to-command-behavior/) that provides Event to Command comversion.

I agree to you but I hope keep clean in X.F.GoogleMaps.

I'm debating to add fully binding supports.

**Comment by dreamsystems** [comment]
I understand that you want to keep the `GoogleMaps` namespace clean. Today, who work with 

Xamarin forms and doesn't use the MVVM pattern ? It would be nice to poll developers for this.

**Comment by amay077** [comment]
ref #9

**Comment by amay077** [comment]
This discussion has been moved to #9 .
