### ISSUE TITLE
Add ctor MapRenderer(IntPtr javaReference, JniHandleOwnership transfer) to Xamarin.Forms.GoogleMaps.Android.MapRenderer

### ISSUE THREAD

**Issue by Exomode** [amay077/Xamarin.Forms.GoogleMaps#89]
Exception:

System.MissingMethodException: No constructor found for Xamarin.Forms.GoogleMaps.Android.MapRenderer::.ctor(System.IntPtr, Android.Runtime.JniHandleOwnership)

Android >= 5.0, Xamarin.Forms version: last stable.

**Comment by amay077** [comment]
Could you tell me X.F.GoogleMaps, Google play service and Xamarin.Forms version?

I think resolved this issue in [issue73](https://github.com/amay077/Xamarin.Forms.GoogleMaps/issues/73#issuecomment-247980349).

**Comment by Exomode** [comment]
X.F.GoogleMaps 1.6.1
Google play service 29.0.0.2
Xamarin.Forms 2.3.2.127

**Comment by amay077** [comment]
I deployed [1.7.0-beta3](https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/1.7.0-beta3) that includes this.
Please check it.
