### ISSUE TITLE
VisibleRegion doesn't update when moving the map with the MoveToRegion function on iOS.

### ISSUE THREAD

**Issue by VANtheSven** [amay077/Xamarin.Forms.GoogleMaps#90]
When moving the map with MoveToRegion, the VisibleRegion property doesn't get updated. Because of this, the property will stay null until the map is manually moved by touching it. This only happens on iOS however, Android does not have this problem.

Happens on both 1.6.0 and 1.6.1
XF version is 2.3.2.127

**Comment by amay077** [comment]
Thank you for your reporting.
I'll check it. 👍

**Comment by amay077** [comment]
I reproduced it on both iOS and Android.
I added display Lat/Lon at geo code in [BasicMapSample](https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/master/XFGoogleMapSample/XFGoogleMapSample/BasicMapPage.xaml.cs#L79).

REPRO for operations are listed below.

1. geocode to "new york"
2. label shows {41.89, 12.49} but New York's location is {40.71, -74.01}
3. push geocode again then shows {40.71, -74.01}

![untitled2](https://cloud.githubusercontent.com/assets/401369/19736809/d39eb798-9beb-11e6-97cf-9f4013cb35ed.gif)

I think ``MoveToRegion`` should wait for animation finished.
Or ``Map`` need ``CameraUpdate`` event.

ref - #7 CameraUpdate support

**Comment by LukasThijs** [comment]
You can fix this issue by making the MoveToUser a <task> like this:

  ```
  public async Task MoveToUser(Map map, BNPage page) {
            _map = map;
            try
            {

               // page.ShowMessage("Bezig met locatie ophalen");
                var locator = CrossGeolocator.Current;
                locator.DesiredAccuracy = 50;
                var location = await locator.GetPositionAsync(timeoutMilliseconds: 10000);
                _userPosition = new Position(location.Latitude, location.Longitude);
                map.MoveToRegion(MapSpan.FromCenterAndRadius(_userPosition, Distance.FromMeters(500)).WithZoom(1));
            }
            catch (TaskCanceledException)
            {
                page.ShowAlert("Ophalen afgebroken","Controleer uw internetverbinding en probeer het nogmaals","Ok");
            }

            catch (TimeoutException)
            {
                page.ShowAlert("Locatie ophalen mislukt",
                    "Controleer uw internetverbinding en probeer het nogmaals", "Ok");
            }
            catch (Exception)
            {
                page.ShowAlert("Locatie ophalen mislukt",
                    "Controleer uw internetverbinding en probeer het nogmaals of vul", "Ok");
            }
       //     page.ClearMessage();




        }
```

Then in the page itself (code behind) you use the public override to await the action before anything else happens for example:

```
  public partial class OverviewRelationMapPage : BNPage
    {
        /// <summary>
        /// Makes BNPage public and removes his protection level for the tabbed parent page.
        /// </summary>
        //public Map MapPageMapControl => this.map;

        public OverviewViewModel ParentViewModel;
        public OverviewRelationMapPage()
        {
            InitializeComponent();


        }

        protected override async void OnAppearing() {
            base.OnAppearing();
            ParentViewModel.ShowPins(this.map);
            await ParentViewModel.MoveToUser(this.map,this);
            
        }

       
    }
```

**Comment by amay077** [comment]
@LukasThijs, Thanks for workaround.

I will support ``CameraUpdate`` event. #7 
So I close this.
