### ISSUE TITLE
More than 1 pin with custom pin icon throws exception

### ISSUE THREAD

**Issue by deextercz** [amay077/Xamarin.Forms.GoogleMaps#91]
```
        var assembly = typeof(MapPage).GetTypeInfo().Assembly;
        var fileStream = assembly.GetManifestResourceStream($"iMHD.sample.png");

        foreach (var vehicle in _vehicles)
        {
            var pin = new Pin
            {
                Position = new Position(vehicle.Position.Latitude, vehicle.Position.Longitude),
                Label = $"Line {vehicle.Line}",
                Address = $"Delay: {vehicle.Delay/60} minutes",
                Icon = BitmapDescriptorFactory.FromStream(fileStream)
            };

            MhdMap.Pins.Add(pin);
        }
```

In second loop it throws and exception Java.Lang.NullPointerException: null reference
If I do same just with 1 item it works

**Comment by deextercz** [comment]
![screenshot 2016-10-25 09 29 36](https://cloud.githubusercontent.com/assets/23039506/19676632/bd1f2540-9a95-11e6-812e-2bffc83531f9.png)
Also with the same code iOS does not work, it just renderes default pins.

**Comment by amay077** [comment]
Thank you for your reporting.
I'll check it.

I wonder can't use same ``fileStream`` instance.

**Comment by deextercz** [comment]
I wanted to debug by my self, but without logging I think I am not able to debug.

**Comment by deextercz** [comment]
I tested with some changes:

            var assembly = typeof(MapPage).GetTypeInfo().Assembly;

            foreach (var vehicle in ServerCommunicatorClient.GetAllVehicles())
            {
                var fileStream = assembly.GetManifestResourceStream($"iMHD.sample.png");

                var pin = new Pin
                {
                    Position = new Position(vehicle.Position.Latitude, vehicle.Position.Longitude),
                    Label = $"Line",
                    Address = $"Delay: 0 minutes",
                    Icon = BitmapDescriptorFactory.FromStream(fileStream)
                };

                MhdMap.Pins.Add(pin);
            }
and it works, but I think it is still bug.

Anyway is it possible to create image from code? I want to draw triangle with number inside

**Comment by amay077** [comment]
You can user ``BitmapDescriptorFactory.FromView`` what can make Pin from your custom ``View``.

Sample code is [here](https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/master/XFGoogleMapSample/XFGoogleMapSample/BindingPinViewPage.xaml.cs#L26)!

**Comment by deextercz** [comment]
Is it possible to use
 `var iconImage = BitmapDescriptorFactory.FromBundle("symbol_fore_close.png");` ?
Because it does not work for me, even if i change Build Action for image to Embeded Resource.
Or the only way is to create view with my image/ Get stream of image

**Comment by deextercz** [comment]
Probably memery is destroyed after it is read.
