### ISSUE TITLE
Enable properties for ZoomControlsEnabled and ZoomGesturesEnabled in Custom Renderer

### ISSUE THREAD

**Issue by izefler** [amay077/Xamarin.Forms.GoogleMaps#92]
Hi, I need to disable the buttons Zoom, but allow Zoom through Gestures, but can not due to sharing the same property Map.HasZoomEnabled.

map.UiSettings.ZoomControlsEnabled = Map.HasZoomEnabled;
map.UiSettings.ZoomGesturesEnabled = Map.HasZoomEnabled;

**Comment by amay077** [comment]
Hi @izefler,
I have a plan for ``UISettings`` support what can individual settings access.

* #8 UiSettings class support

**Comment by amay077** [comment]
This discussion has been moved to #8 .
