### ISSUE TITLE
Receiving ClassCastException exception when using PushModalAsync for a page wrapped in a NavigationPage

### ISSUE THREAD

**Issue by izefler** [amay077/Xamarin.Forms.GoogleMaps#93]
I'm experiencing a problem when i'make a modal navigation to a form page from the map page.

Even has an open bug for Xamarin, about the problem.

https://bugzilla.xamarin.com/show_bug.cgi?id=43692

I believe that is not associated with this component, but if you can help me will be of great value.

Thank you.

**Comment by izefler** [comment]
The following repository with project with the reproduction of the error:

Use version Android
https://github.com/izefler/PrismUnityApp1

**Comment by amay077** [comment]
I reproduced too.
I think this is not associated with this component as you said.

I tried to debug with X.F.GoogleMaps source code, but debugger does not stop into my code.

I will watch bugzilla and X.F.Maps original code.
If I found solution then apply X.F.GoogleMaps.

**Comment by izefler** [comment]
Thanks for the feedback.

Actually the problem is reallocated to XF, and I did not get the problem, a bug was opened in Xamarin matins, and to get around the problem, I changed my browsing strategy.
