### ISSUE TITLE
Pin rotation

### ISSUE THREAD

**Issue by deextercz** [amay077/Xamarin.Forms.GoogleMaps#95]
Hello,
when I have pin icon where it matters a rotation, could I rotate with pin like in native?
Or it is only option to rotate with image before putting to map?
Also it must be re-rendered after tilt.
https://developers.google.com/maps/documentation/android-api/marker

**Comment by amay077** [comment]
Thanks, I will add plan it. 👍

**Comment by amay077** [comment]
ref [#PR102](https://github.com/amay077/Xamarin.Forms.GoogleMaps/pull/102)

**Comment by amay077** [comment]
I deployed [1.7.0-beta4](https://www.nuget.org/packages/Xamarin.Forms.GoogleMaps/1.7.0-beta4) that includes this.
Please check it.
